// P08B.4 preview-only V2 presentation. The live order-confirmation sender still uses confirmation.ts.
export const v2Kinds=['order_confirmed','in_production','ready_to_dispatch','dispatched','full_refund'] as const;
export type V2Kind=typeof v2Kinds[number];
export const emailAssets=Object.freeze({logo:'https://apparitioninstruments.co.uk/assets/apparition-logo-email.png',violinist:'https://apparitioninstruments.co.uk/assets/the-violinist-email.png',inProduction:'https://apparitioninstruments.co.uk/assets/in-production-email.png',readyToDispatch:'https://apparitioninstruments.co.uk/assets/ready-to-dispatch-email.png',dispatched:'https://apparitioninstruments.co.uk/assets/dispatched-email.png'});
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const money=(p:number)=>'£'+(p/100).toFixed(2);
const config:Record<V2Kind,{heading:string;subject:string;intro:string;next:string;art:keyof typeof emailAssets|null}>={
 order_confirmed:{heading:'ORDER CONFIRMED',subject:'confirmed',intro:'Thank you for your order. We have received your payment.',next:'We will prepare your order and send another update when it enters production.',art:'violinist'},
 in_production:{heading:'YOUR ORDER IS IN PRODUCTION',subject:'in production',intro:'We have started preparing your Apparition Instruments order.',next:'We will let you know when it is ready to dispatch.',art:'inProduction'},
 ready_to_dispatch:{heading:'READY TO DISPATCH',subject:'ready to dispatch',intro:'Preparation is complete. Your order is ready to leave Apparition Instruments.',next:'We will let you know when your order has actually been dispatched.',art:'readyToDispatch'},
 dispatched:{heading:'YOUR ORDER IS ON ITS WAY',subject:'dispatched',intro:'Your order has been dispatched.',next:'If you need help with delivery, please contact us.',art:'dispatched'},
 full_refund:{heading:'YOUR REFUND HAS BEEN PROCESSED',subject:'refunded',intro:'Your full refund has been processed to the original payment method.',next:'Your bank or card provider may take additional time to show the funds. Please contact us if you need help.',art:null}
};
const safeTracking=url=>{try{const parsed=new URL(url);return parsed.protocol==='https:'&&parsed.username===''&&parsed.password===''&&url.length<=500?parsed.href:null;}catch{return null;}};
export function renderEmailV2(kind:V2Kind,order:any,{preview=false}: {preview?:boolean}={}){
 if(!v2Kinds.includes(kind)||!order||!/^AI-\d+$/.test(order.reference)&&!(preview&&order.reference==='AI-PREVIEW'))throw Error('Order reference unavailable');
 if(!order.customer?.email||!order.customer.name||!Array.isArray(order.items)||!order.items.length)throw Error('Persisted Order contact or items unavailable');
 if(![order.subtotal_pence,order.delivery_pence,order.total_pence].every(v=>Number.isSafeInteger(v)&&v>=0)||order.subtotal_pence+order.delivery_pence!==order.total_pence)throw Error('Persisted Order total invalid');
 if(order.items.some(i=>!Number.isSafeInteger(i.quantity)||i.quantity<1||!Number.isSafeInteger(i.lineTotal)||i.lineTotal<0||!Number.isSafeInteger(i.unitPrice)||i.quantity*i.unitPrice!==i.lineTotal)||order.items.reduce((sum,i)=>sum+i.lineTotal,0)!==order.subtotal_pence)throw Error('Persisted item totals invalid');
 if(kind==='full_refund'&&(!Number.isSafeInteger(order.refunded_pence)||order.refunded_pence!==order.total_pence||order.payment_status!=='refunded'))throw Error('Authoritative full refund required');
 const first=String(order.customer.name).trim().split(/\s+/)[0],label=config[kind];
 const address=[order.delivery?.recipient,order.delivery?.line1,order.delivery?.line2,order.delivery?.city,order.delivery?.region,order.delivery?.postcode,order.delivery?.country==='GB'?'United Kingdom':order.delivery?.country].filter(Boolean);
 const dispatch=order.dispatch_details||{},carrier=typeof dispatch.carrier==='string'?dispatch.carrier.trim():'',tracking=typeof dispatch.tracking_reference==='string'?dispatch.tracking_reference.trim():'';
 const trackingUrl=typeof dispatch.tracking_url==='string'?safeTracking(dispatch.tracking_url):null;
 const lines=order.items.map(i=>`${i.quantity} × ${i.name} · ${money(i.lineTotal)}`);
 const totalLabel=kind==='order_confirmed'?'Total paid':'Original order total';
 const sections=[`ORDER ${order.reference}`,...(kind==='order_confirmed'||kind==='full_refund'?['',...lines,'',`Subtotal ${money(order.subtotal_pence)}`,`Delivery ${money(order.delivery_pence)}`,`${totalLabel} ${money(order.total_pence)}`]:[]),...(kind==='full_refund'?[`Refund processed ${money(order.refunded_pence)}`]:[]),...(kind==='dispatched'?[carrier&&`Carrier: ${carrier}`,tracking&&`Tracking reference: ${tracking}`,trackingUrl&&`Track your order: ${trackingUrl}`].filter(Boolean):[]),...(kind==='order_confirmed'&&address.length?['','DELIVERY ADDRESS',...address]:[])];
 const external=kind==='dispatched'&&order.sales_channel&&order.sales_channel!=='WEBSITE';
 const origin=external?`External ${order.sales_channel==='EBAY'?'eBay':order.sales_channel==='DIRECT'?'direct sale':'marketplace'} order${order.external_reference?' · '+order.external_reference:''}`:'';
 if(kind==='dispatched'&&order.sales_channel==='EBAY'){
  const support='For help with this order, contact Apparition Instruments through your eBay order messages.';
  const recorded=[carrier&&`Shipping service: ${carrier}`,tracking&&`Tracking reference: ${tracking}`].filter(Boolean);
  const text=['APPARITION INSTRUMENTS',label.heading,`Hi ${first},`,label.intro,`Order ${order.reference}`,origin,...lines,...recorded,support].join('\n');
  const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head><body style="background:#262621;color:#f4efe6;font-family:Arial,Helvetica,sans-serif;padding:24px"><p>APPARITION INSTRUMENTS</p><h1>${esc(label.heading)}</h1><p>Hi ${esc(first)},</p><p>${esc(label.intro)}</p><p>Order ${esc(order.reference)}<br>${esc(origin)}</p><ul>${lines.map(line=>`<li>${esc(line)}</li>`).join('')}</ul>${recorded.map(line=>`<p>${esc(line)}</p>`).join('')}<p>${esc(support)}</p><p>Apparition Instruments Limited · Company No. 17454761 · Registered in England &amp; Wales</p></body></html>`;
  return {to:order.customer.email,subject:`Apparition Instruments order ${order.reference} ${label.subject}`,text,html};
 }
 const text=['APPARITION INSTRUMENTS',label.heading,`Hi ${first},`,label.intro,...(external?[origin,...lines]:[]),...sections,'',label.next,'','Contact us: https://apparitioninstruments.co.uk/contact/','https://apparitioninstruments.co.uk','Apparition Instruments Limited · Company No. 17454761 · Registered in England & Wales'].join('\n');
 const items=(kind==='order_confirmed'||kind==='full_refund')?`<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="border-collapse:collapse;color:#f4efe6;font-size:14px"><tr><th align="left" style="padding:10px 0;border-bottom:1px solid #82643b">Item</th><th align="center" style="padding:10px 5px;border-bottom:1px solid #82643b">Qty</th><th align="right" style="padding:10px 0;border-bottom:1px solid #82643b">Total</th></tr>${order.items.map(i=>`<tr><td style="padding:11px 0;border-bottom:1px solid #41413b;overflow-wrap:anywhere">${esc(i.name)}</td><td align="center" style="padding:11px 5px;border-bottom:1px solid #41413b">${i.quantity}</td><td align="right" style="padding:11px 0;border-bottom:1px solid #41413b;white-space:nowrap">${money(i.lineTotal)}</td></tr>`).join('')}</table><p style="line-height:1.8;text-align:right">Subtotal ${money(order.subtotal_pence)}<br>Delivery ${money(order.delivery_pence)}<br><strong>${totalLabel} ${money(order.total_pence)}</strong>${kind==='full_refund'?`<br><strong>Refund processed ${money(order.refunded_pence)}</strong>`:''}</p>`:'';
 const dispatchHtml=kind==='dispatched'&&(carrier||tracking||trackingUrl)?`<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="border-collapse:collapse;color:#f4efe6;margin:22px 0"><tr><td style="border-top:1px solid #80643f;padding:16px 0 8px;color:#d7ad69;font-size:12px;letter-spacing:1px">DELIVERY DETAILS</td></tr>${carrier?`<tr><td style="padding:5px 0;font-size:14px;line-height:1.5">Carrier: ${esc(carrier)}</td></tr>`:''}${tracking?`<tr><td style="padding:5px 0;font-size:14px;line-height:1.5;word-break:break-all">Tracking reference: ${esc(tracking)}</td></tr>`:''}${trackingUrl?`<tr><td style="padding:16px 0 4px"><a style="display:inline-block;border:1px solid #c6a26b;color:#f4efe6;text-decoration:none;font-size:12px;letter-spacing:1px;padding:10px 16px" href="${esc(trackingUrl)}">TRACK YOUR ORDER</a></td></tr>`:''}</table>`:'';
 const addressHtml=kind==='order_confirmed'&&address.length?`<h2 style="font-size:15px;color:#d7ad69">DELIVERY ADDRESS</h2><p style="line-height:1.6">${address.map(esc).join('<br>')}</p>`:'';
 const portrait=label.art==='violinist';
 const footerArt=label.art?`<td align="right" valign="middle" width="35%" style="width:35%;padding:12px 12px 12px 0;vertical-align:middle"><img src="${emailAssets[label.art]}" alt="" width="${portrait?82:200}" height="${portrait?119:134}" style="display:block;border:0;${portrait?'width:82px;max-width:100%':'width:100%;max-width:200px'};height:auto" /></td>`:'';
 const footer=`<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="border-collapse:collapse;background:#1d1d1b;color:#d9d1c1"><tr><td valign="middle" width="${label.art?'65%':'100%'}" style="padding:20px 10px 20px 26px;font-size:12px;line-height:1.65;vertical-align:middle;overflow-wrap:anywhere;word-break:break-word"><strong style="color:#f4efe6">APPARITION INSTRUMENTS</strong><br><a href="https://apparitioninstruments.co.uk/contact/" style="color:#d7ad69">Contact us</a><br><a href="https://apparitioninstruments.co.uk" style="color:#d7ad69">apparitioninstruments.co.uk</a><br>Apparition Instruments Limited<br>Company No. 17454761 · Registered in England &amp; Wales</td>${footerArt}</tr></table>`;
 const html=`<!doctype html><html lang="en"><head><meta name="viewport" content="width=device-width,initial-scale=1"><meta charset="utf-8"></head><body style="margin:0;padding:0;background:#151514;color:#f4efe6;font-family:Arial,Helvetica,sans-serif"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#151514"><tr><td align="center" style="padding:22px 12px"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="max-width:600px;background:#262621;color:#f4efe6;border-collapse:collapse"><tr><td align="center" style="padding:27px 24px 24px;background:#20201c;text-align:center"><img src="${emailAssets.logo}" alt="Apparition Instruments" width="380" height="109" style="display:block;border:0;width:380px;max-width:100%;height:auto;margin:0 auto;color:#d7ad69;font-size:20px;font-weight:bold" /></td></tr><tr><td style="height:3px;background:#bd9354;font-size:1px">&nbsp;</td></tr><tr><td style="padding:28px 26px 34px"><p style="font-size:11px;color:#d7ad69;letter-spacing:2px;margin:0 0 12px">ORDER ${esc(order.reference)}</p><h1 style="font-size:23px;line-height:1.25;margin:0 0 22px;color:#faf3e6">${esc(label.heading)}</h1><p style="font-size:15px;line-height:1.65">Hi ${esc(first)},</p><p style="font-size:15px;line-height:1.65">${esc(label.intro)}</p>${external?`<p style="font-size:14px;line-height:1.6">${esc(origin)}</p><p style="font-size:14px;line-height:1.6">${lines.map(esc).join('<br>')}</p>`:''}${items}${kind==='full_refund'?`<p style="font-size:14px;line-height:1.6">Your full refund of ${money(order.refunded_pence)} was processed to the original payment method.</p>`:''}${dispatchHtml}${addressHtml}<p style="font-size:14px;line-height:1.65;margin-top:25px">${esc(label.next)}</p></td></tr><tr><td>${footer}</td></tr></table></td></tr></table></body></html>`;
 return {to:order.customer.email,subject:`Apparition Instruments order ${order.reference} ${label.subject}`,text,html};
}

export function previewFixture(kind:V2Kind,tracking=false){const order={reference:'AI-PREVIEW',payment_status:kind==='full_refund'?'refunded':'paid',refunded_pence:kind==='full_refund'?5498:0,customer:{name:'Luke Williams',email:'preview@example.invalid'},delivery:{recipient:'Luke Williams',line1:'46 Example Road',line2:'',city:'Nottingham',postcode:'NG1 1AA',country:'GB'},items:[{name:'Premium Duncan-Style Treble Bleed',quantity:2,unitPrice:750,lineTotal:1500},{name:'Prewired Les Paul Wiring Harness',quantity:1,unitPrice:3998,lineTotal:3998}],subtotal_pence:5498,delivery_pence:0,total_pence:5498,dispatch_details:kind==='dispatched'&&tracking?{carrier:'Example Carrier',tracking_reference:'PREVIEW-123',tracking_url:'https://example.invalid/preview-tracking'}:{}};return renderEmailV2(kind,order,{preview:true});}
