import assert from 'node:assert/strict';import {readFileSync as read,existsSync} from 'node:fs';import {execFileSync} from 'node:child_process';import {Window} from 'happy-dom';import {mountAdminShell,adminRoutes,workspaceFor} from '../dist/admin/application.mjs';import {stripWorkspaces} from '../scripts/content-platform/admin-workspaces.mjs';
const base='9e49f46ab4a63fc90e640e2d9c71ca769b00cf1b',pages=['index.html','orders/index.html','wiring-kit-master/index.html','catalogue-settings/index.html','hub-cms/index.html','site-operations/index.html','hub-media/index.html'];
const allowed=new Set([...pages.map(p=>'dist/admin/'+p),'dist/admin/workspaces.css','scripts/content-platform/admin-workspaces.mjs','tests/discovery-operations-v2.mjs','tests/admin-v2-e.mjs','tests/admin-v2-e-integrated.mjs','docs/admin-v2/CHECKPOINT-E.md']);
for(const p of execFileSync('git',['diff',base,'--name-only'],{encoding:'utf8'}).trim().split('\n').filter(Boolean))assert(allowed.has(p),'Protected source: '+p);
const settings={disableCSSFileLoading:true,disableJavaScriptFileLoading:true,disableJavaScriptEvaluation:true,disableIframePageLoading:true};
for(const route of adminRoutes){const url=new URL(route.href,'https://example.test'),path='dist'+url.pathname+'index.html';assert(existsSync(path),route.href);assert.equal(workspaceFor(url),route.id);const w=new Window({url:url.href,settings}),d=w.document;d.write(read(path,'utf8'));if(route.id==='conjure'){const before=d.body.innerHTML;assert.equal(mountAdminShell(d,d.createElement('button')),null);assert.equal(d.body.innerHTML,before);await w.happyDOM.close();continue;}const controls=[...d.querySelectorAll('form,input,select,textarea,button[id]')];mountAdminShell(d,d.createElement('button'));assert.equal(d.querySelectorAll('nav[aria-label="Admin workspaces"]').length,1);assert.equal(d.querySelectorAll('.admin-workspaces,.admin-navigation,nav.admin-tabs').length,0);assert.equal(d.querySelector('[aria-current=page]').dataset.workspace,route.id);for(const c of controls)assert(c.isConnected,'Removed functional control');assert(d.querySelector('.admin-page-header h1'));await w.happyDOM.close();}
for(const p of pages){const old=execFileSync('git',['show',base+':dist/admin/'+p],{encoding:'utf8'}),clean=stripWorkspaces(old).replace(/<nav class="(?:admin-navigation[^"]*|admin-tabs)"[^>]*>[\s\S]*?<\/nav>/g,'');assert.equal(read('dist/admin/'+p,'utf8'),clean,'Only superseded navigation may change');assert(!clean.includes('/admin/workspaces.css'));}
assert(!existsSync('dist/admin/workspaces.css'));const generator=read('scripts/content-platform/admin-workspaces.mjs','utf8');assert(!generator.includes('<details'));const css=read('dist/admin/application.css','utf8');for(const line of css.split('\n').filter(x=>x.includes('{')&&!x.startsWith('/*')))assert(line.startsWith('[data-admin-app]')||line.startsWith('@media'));for(const c of ['focus-visible','word-break:normal','overflow:auto','prefers-reduced-motion'])assert(css.includes(c));
console.log('E PASS: all 16 destinations/deep links, one authenticated shell, exact navigation-only HTML cleanup, controls retained, Conjure isolation, no generator relapse, scoped accessible/responsive presentation and protected source allowlist.');
