import assert from 'node:assert/strict';
import {createComponentStore,storageKey} from '../dist/admin/data.mjs';
import {catalogue} from '../dist/components/catalogue.mjs';
const memory=new Map(),storage={getItem:k=>memory.get(k)??null,setItem:(k,v)=>memory.set(k,v)};
let store=createComponentStore(storage),items=store.list();
for(const p of catalogue)assert(items.some(i=>i.id===p.id));
const expected={'bleed-prs':42,'bleed-cap':200,'bleed-duncan':81,'bleed-premium':0,'bleed-overkill':0,'pot-short-cts-a':5,'pot-short-alpha-a':10,'cde-022':20,'nissei-033':100,'cde-715p-600':2,'sbe-200':10,'sbe-600':100,'switch-epiphone':3};
for(const item of items)assert.equal(item.stock,expected[item.id]??0,item.id);
const created=store.save({sku:'test-part',name:'Test capacitor',manufacturer:'Test',category:'capacitors',description:'Initial',stock:2,active:true,individually:false,inKits:false,specs:{Value:'0.022µF'}});
store.save({...created,name:'Edited capacitor',description:'Updated',active:false,individually:true,inKits:true,specs:{Value:'0.033µF'}},created.id);
store.changeStock(created.id,10,'set');store.changeStock(created.id,-3,'adjust');store.changeStock(created.id,2,'adjust');
assert.throws(()=>store.changeStock(created.id,-10,'adjust'),/below zero/);assert.throws(()=>store.changeStock(created.id,-1,'set'),/below zero/);assert.throws(()=>store.changeStock(created.id,1.5),/whole number/);assert.throws(()=>store.changeStock(created.id,''),/whole number/);
assert.throws(()=>store.save({...created,stock:-1},created.id),/below zero/);assert.throws(()=>store.save({...created,sku:'BLEED-PRS'}),/already exists/);assert.throws(()=>store.save({...created,name:''},created.id),/component name/);
store=createComponentStore(storage);const saved=store.list().find(x=>x.id===created.id);assert.equal(saved.name,'Edited capacitor');assert.equal(saved.stock,9);assert.equal(saved.active,false);assert.equal(saved.individually,true);assert.equal(saved.inKits,true);assert.equal(saved.specs.Value,'0.033µF');
store.changeStock(created.id,0);store.save({...store.list().find(x=>x.id===created.id),active:true},created.id);assert(store.list().find(x=>x.id===created.id).active);
assert.equal(store.list().find(x=>x.id==='sbe-600').stock,100,'Reload never reseeds over saved data');
const corrupted={getItem:()=>'{broken',setItem:()=>assert.fail('Must not overwrite corrupt storage')};assert.throws(()=>createComponentStore(corrupted).list(),/preserved/);
assert.throws(()=>createComponentStore({getItem:()=>null,setItem:()=>{throw new Error();}}).list(),/could not be saved/);
console.log('Admin: existing catalogue, exact stock seed, add/edit, active and availability flags, set/adjust stock, invalid/negative rejection, refresh persistence and storage error handling passed.');
