import assert from 'node:assert/strict';
import {aftercareDatabase} from './fixtures/aftercare-database.mjs';
const {db,actor,create,one,query,stock}=await aftercareDatabase();
const scalar=async(sql,p=[])=>(await one(sql,p)).r;
const state=id=>scalar('select public.aftercare_state($1) r',[id]);
const summary=async id=>scalar('select public.aftercare_summary(public.aftercare_state($1)) r',[id]);
const action=async(id,kind,due=null,reason='Owner reviewed this follow-up',expected)=>scalar('select public.update_customer_aftercare($1,$2,$3,$4,$5) r',[id,JSON.stringify(expected||await summary(id)),kind,due,reason]);
async function fixture(channel='EBAY',at='2026-03-22T23:30:00Z'){
 const o=await create({requestId:crypto.randomUUID(),channel:channel==='WEBSITE'?'DIRECT':channel,externalReference:crypto.randomUUID(),orderDate:'2026-03-01',customerName:'Luke Fixture',postagePence:91,items:[{type:'component',productId:'a',quantity:1,unitPricePence:100}]});
 await db.query("update public.orders set status='dispatched',customer=customer||jsonb_build_object('email',$2::text),status_history=jsonb_build_array(jsonb_build_object('status','dispatched','event_id',gen_random_uuid(),'at',$3::text)),sales_channel=$4,external_reference=case when $4='WEBSITE' then null else external_reference end,order_date=case when $4='WEBSITE' then null else order_date end where id=$1",[o.id,channel==='EBAY'?'fixture@members.ebay.com':'fixture@example.test',at,channel]);
 return o.id;
}
const snapshot=()=>query('select (select jsonb_agg(to_jsonb(o)) from public.orders o) orders,(select jsonb_agg(to_jsonb(i)) from public.inventory i) stock');
const id=await fixture();let s=await state(id);assert.equal(s.defaultDue,'2026-03-29');assert.equal(s.route,'manual');assert(!s.order.customer.email);assert.deepEqual(s.order.delivery,{});
for(const [at,due] of [['2026-03-28T23:30:00Z','2026-04-04'],['2026-03-29T23:30:00Z','2026-04-06'],['2026-10-24T23:30:00Z','2026-11-01'],['2026-10-25T00:30:00Z','2026-11-01']]){assert.equal(await scalar("select ((public.aftercare_dispatch_at(jsonb_build_array(jsonb_build_object('status','dispatched','event_id','real','at',$1::text))) at time zone 'Europe/London')::date+7)::text r",[at]),due);}
for(const at of ['invalid','2026-99-90T23:30:00Z','infinity','2026-10-08']){const invalid=await fixture('DIRECT',at);assert.equal((await state(invalid)).dispatchAt,null);await assert.rejects(action(invalid,'reschedule','2026-10-15'));}
const und=await fixture();await db.query("update public.orders set status='pending' where id=$1",[und]);assert.equal((await state(und)).eligible,false);const list=await scalar('select public.get_customer_aftercare() r');assert(!list.some(r=>r.orderId===und));
const future=await fixture('DIRECT','2099-03-01T12:00:00Z');assert.equal((await state(future)).eligible,false);await assert.rejects(action(future,'handled'));
const partial=await fixture('DIRECT');await db.query("update public.orders set payment_status='partially_refunded',refunded_pence=1,latest_refund_at=clock_timestamp() where id=$1",[partial]);assert.equal((await state(partial)).eligible,false);await db.query('insert into public.partial_refund_reviews(order_id,refunded_pence,refund_at) select id,refunded_pence,latest_refund_at from public.orders where id=$1',[partial]);assert.equal((await state(partial)).eligible,true);
const before=await snapshot();await action(id,'reschedule','2026-10-15');assert.equal((await state(id)).dueDate,'2026-10-15');assert.equal((await summary(id)).state,'upcoming');assert.deepEqual(await snapshot(),before);
const stale=await summary(id);await action(id,'reschedule','2026-10-16');await assert.rejects(action(id,'skip',null,'Skip this order',stale));
await action(id,'handled');assert.equal((await summary(id)).state,'handled');assert.equal((await state(id)).followup.history.at(-1).manualConfirmation,true);assert.equal((await scalar("select count(*)::int r from public.order_email_deliveries where kind='aftercare'")),0);
const skipped=await fixture();await action(skipped,'skip');assert.equal((await summary(skipped)).state,'skipped');await assert.rejects(action(skipped,'handled'));
const direct=await fixture('DIRECT');const suppressed=await fixture('DIRECT');await action(direct,'suppress',null,'Customer asked for no follow-up');assert((await state(suppressed)).suppressed);assert.equal((await state(suppressed)).route,'manual');await assert.rejects(scalar('select public.get_aftercare_preview_context($1) r',[suppressed]));
const website=await fixture('WEBSITE');await db.query("update public.orders set customer=customer||'{\"email\":\"fresh@example.test\"}'::jsonb where id=$1",[website]);const c=await scalar('select public.get_aftercare_preview_context($1) r',[website]);assert.equal(c.route,'email');const unchanged=await snapshot();const op=crypto.randomUUID();
const claim=await scalar('select public.confirm_aftercare_preview($1,$2,$3,$4,$5) r',[website,actor,JSON.stringify(c),op,'aftercare-support-v1/prepared-v1']);assert(claim.claim);const ledger=await one("select * from public.order_email_deliveries where order_id=$1 and kind='aftercare'",[website]);assert.equal(ledger.automatic_delivery_eligible,false);assert.equal(ledger.operation_id,op);await assert.rejects(scalar('select public.confirm_aftercare_preview($1,$2,$3,$4,$5) r',[website,actor,JSON.stringify(c),crypto.randomUUID(),'aftercare-support-v1/prepared-v1']));assert.deepEqual(await snapshot(),unchanged);
assert.equal(await scalar("select public.mark_order_email_attempt($1,'aftercare',$2) r",[website,claim.claim]),true);assert.equal(await scalar("select public.finish_aftercare_delivery($1,$2,'failed','Mock failure') r",[website,claim.claim]),true);assert.equal((await summary(website)).state,'failed');await assert.rejects(scalar('select public.get_aftercare_preview_context($1) r',[website]));await action(website,'handled',null,'Resolved externally after failed email');assert.equal((await summary(website)).state,'handled');assert.equal((await one('select state from public.order_email_deliveries where id=$1',[ledger.id])).state,'failed');
const roles=await query("select p.proname,has_function_privilege('anon',p.oid,'execute') anon,has_function_privilege('authenticated',p.oid,'execute') authenticated,p.proconfig from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in ('confirm_aftercare_preview','aftercare_state','finish_aftercare_delivery','get_aftercare_preview_context','update_customer_aftercare','get_customer_aftercare')");for(const r of roles){assert(!r.anon);assert.deepEqual(r.proconfig,['search_path=""']);assert.equal(r.authenticated,r.proname.startsWith('get_')||r.proname==='update_customer_aftercare');}
await db.exec('set role anon');await assert.rejects(scalar('select public.get_customer_aftercare() r'));await db.exec('reset role');await db.exec("select set_config('request.jwt.claim.sub','10000000-0000-4000-8000-000000000099',false);set role authenticated");await assert.rejects(scalar('select public.get_customer_aftercare() r'));await assert.rejects(action(skipped,'skip'));assert.equal((await query('select * from public.order_aftercare')).length,0);await db.exec('reset role');
await db.close();console.log('Aftercare model PASS: calendar/DST boundaries, invalid/undispatched safety, persisted scheduling/skip/handled, suppression, no business writes, ledger/idempotency, failed outcome, Admin RPC and RLS gates.');
