import assert from 'node:assert/strict';
import {Window} from 'happy-dom';
import {readFileSync} from 'node:fs';
import {renderAftercareQueue,aftercareRows,aftercareDate,ukDay,mountAftercarePanel,aftercareActionDialog} from '../dist/admin/orders/customer-aftercare.mjs';
import {reviewDispatchEmail} from '../dist/admin/orders/email-review.mjs';
import {createAdminOrderRepository} from '../dist/backend/order-data.mjs';
const w=new Window({url:'https://apparitioninstruments.co.uk/admin/orders/'});globalThis.document=w.document;const tick=()=>new Promise(r=>setTimeout(r,0)),el=t=>w.document.createElement(t),root=el('section'),message=el('p');w.document.body.append(root,message);
const row={orderId:crypto.randomUUID(),reference:'AI-100001',customerName:'Luke Fixture',recipient:'buyer@example.test',channel:'WEBSITE',dispatchAt:'2026-03-29T23:30:00Z',defaultDue:'2026-04-06',dueDate:'2026-04-06',state:'due',route:'email',eligible:true,suppressed:false,history:[],shippingService:'Royal Mail 2nd Class',tracking:'Untracked service'};
const order={id:row.orderId,customer:{name:row.customerName,email:row.recipient},emailDeliveries:[]};
assert.equal(ukDay('2026-03-29T23:30:00Z'),'2026-03-30');assert.equal(aftercareDate('2026-04-06'),'6 Apr 2026');
const rows=[row,{...row,orderId:'later',reference:'AI-100002',dueDate:'2026-04-10'},{...row,orderId:'soon',state:'upcoming',dueDate:'2099-01-01'},{...row,orderId:'done',state:'sent'},{...row,orderId:'manual',state:'handled'},{...row,orderId:'skip',state:'skipped'},{...row,orderId:'failure',state:'failed'}];
assert.deepEqual(aftercareRows(rows).map(r=>r.orderId),[row.orderId,'failure','later']);assert.equal(aftercareRows(rows,'upcoming').length,1);assert.equal(aftercareRows(rows,'completed').length,2);assert.equal(aftercareRows(rows,'skipped').length,1);assert.equal(aftercareRows(rows,'all').length,7);
renderAftercareQueue(rows,{document:w.document,root});assert.equal(root.querySelectorAll('tbody tr').length,3);assert.match(root.textContent,/No messages are sent automatically|no messages are sent automatically/);const select=root.querySelector('select');select.value='completed';select.dispatchEvent(new w.Event('change'));assert.equal(root.querySelectorAll('tbody tr').length,2);renderAftercareQueue(rows,{document:w.document,root});assert.equal(root.querySelector('select').value,'completed');
let reviews=0,actions=[],refreshes=0;root.replaceChildren();mountAftercarePanel(order,row,{document:w.document,root,message,repository:{updateAftercare:async(...args)=>actions.push(args)},refresh:async()=>refreshes++,review:async(o,options)=>{assert.equal(options.kind,'aftercare');assert.equal(o,order);reviews++;return null;},actionDialog:async(r,a)=>({reason:'Owner reviewed '+a,dueDate:a==='reschedule'?'2026-10-15':null})});
const button=text=>[...w.document.querySelectorAll('button')].find(b=>b.textContent===text);button('Preview Thank-You').click();button('Preview Thank-You').click();await tick();assert.equal(reviews,1);assert.equal(actions.length,0);button('Reschedule').click();await tick();assert.equal(actions.at(-1)[2],'reschedule');assert.equal(actions.at(-1)[3].dueDate,'2026-10-15');button('Mark as Handled').click();await tick();assert.equal(actions.at(-1)[2],'handled');assert.match(message.textContent,/No message was sent/);
for(const state of ['upcoming','sent','skipped','failed','unknown','claimed','blocked']){root.replaceChildren();mountAftercarePanel(order,{...row,state},{document:w.document,root,message,repository:{},refresh:async()=>{}});assert(!button('Preview Thank-You'));}
root.replaceChildren();mountAftercarePanel(order,{...row,suppressed:true},{document:w.document,root,message,repository:{},refresh:async()=>{}});assert(!button('Preview Thank-You'));assert(!button('No Aftercare Email'));
let result=aftercareActionDialog(row,'handled',{document:w.document});let d=w.document.querySelector('dialog');assert(d.open);d.querySelector('textarea').value='Sent via original order conversation';d.querySelector('textarea').dispatchEvent(new w.Event('input',{bubbles:true}));assert(d.querySelector('button[type=submit]').disabled);d.querySelector('input').checked=true;d.querySelector('input').dispatchEvent(new w.Event('change',{bubbles:true}));assert(!d.querySelector('button[type=submit]').disabled);d.querySelector('form').dispatchEvent(new w.Event('submit',{cancelable:true}));assert.equal((await result).reason,'Sent via original order conversation');
result=aftercareActionDialog(row,'reschedule',{document:w.document});d=w.document.querySelector('dialog');assert.equal(d.querySelector('input').min,'2026-03-30');d.dispatchEvent(new w.Event('cancel',{cancelable:true}));assert.equal(await result,null);
const prepared={previewIdentity:'signed',expires:Date.now()+600000,kind:'aftercare',mode:'first',route:'manual',from:{name:'Apparition',email:'provider@example.test'},to:'eBay order conversation',subject:'A quick thank you from Apparition Instruments',html:'<html><head></head><body>Thank you</body></html>',text:'Hi Luke,\nHopefully your order has arrived safely by now.\nContact us through your eBay order messages.',orderReference:row.reference,channel:'EBAY',notice:'Use the original eBay order conversation.'};
let requests=[],copies=[];result=reviewDispatchEmail(order,{document:w.document,kind:'aftercare',request:async(a,p)=>{requests.push({a,p});return prepared;},copyText:async text=>copies.push(text)});await tick();d=w.document.querySelector('dialog');assert.equal(requests[0].a,'prepare-aftercare');assert(button('Confirm & Send Email').hidden);assert(!button('Copy Message').hidden);button('Copy Message').click();await tick();assert.deepEqual(copies,[prepared.text]);assert.match(d.textContent,/No message has been sent and aftercare is still outstanding/);assert.equal(requests.length,1);button('Cancel').click();assert.equal(await result,null);
// The website variant uses the same recipient confirmation and signed-identity request contract.
result=reviewDispatchEmail(order,{document:w.document,kind:'aftercare',request:async(a,p)=>{requests.push({a,p});return a==='prepare-aftercare'?{...prepared,route:'email',to:row.recipient,channel:'WEBSITE'}:{state:'sent',message:'Provider accepted. Inbox delivery is not confirmed.'};}});await tick();d=w.document.querySelector('dialog');assert(button('Confirm & Send Email').disabled);d.querySelector('input[type=checkbox]').checked=true;d.querySelector('input').dispatchEvent(new w.Event('change'));button('Confirm & Send Email').click();assert.match(await result,/Inbox delivery is not confirmed/);assert.equal(requests.at(-1).a,'confirm-aftercare');assert.deepEqual(requests.at(-1).p,{orderId:order.id,previewIdentity:'signed',recipientConfirmed:true});assert(!requests.at(-1).p.html);
let captured=[];const repository=createAdminOrderRepository({send:async(resource,options)=>{captured.push({resource,options});return Response.json(resource.includes('get_customer_aftercare')?[row]:true);}});assert.equal((await repository.aftercare())[0].orderId,row.orderId);await repository.updateAftercare(row.orderId,row,'skip',{reason:'Owner skipped follow-up'});assert.equal(captured[1].options.body.p_action,'skip');assert.deepEqual(captured[1].options.body.p_expected,row);
const app=readFileSync('dist/admin/orders/app.mjs','utf8');assert.match(app,/mountAftercarePanel/);assert.match(app,/renderAftercareQueue/);assert.doesNotMatch(app,/setInterval|setTimeout.*send/);
await w.happyDOM.close();console.log('Aftercare Admin PASS: UK dates, queue sorting/filters/retention, order panel gating, recipient confirmation, cancellation, copy-only draft, explicit external handling, audited action transport and shared preview integration.');
