import assert from 'node:assert/strict';
import {readFileSync as read} from 'node:fs';
import {execFileSync} from 'node:child_process';
import {Window} from 'happy-dom';
import {mountAnnouncement,bootOperations} from '../dist/operations/public.mjs';
import {activeAnnouncement} from '../dist/operations/model.mjs';
import {bootOperationsAdmin} from '../dist/admin/site-operations/operations.mjs';
const settings={disableCSSFileLoading:true,disableJavaScriptFileLoading:true,disableJavaScriptEvaluation:true},now=Date.now(),iso=t=>new Date(t).toISOString(),open={desired_state:'OPEN',state:'OPEN',pause_from:null,resume_at:null,customer_title:'Ordering paused',customer_message:'Saved basket',updated_at:iso(now),observed_at:iso(now)},post={id:'fixture-zero',slug:'fixture-zero',title:'Fixture workshop update',excerpt:'Compact excerpt only',message:'Compact excerpt only',body:'FULL BODY MUST NOT APPEAR',publication_at:iso(now-1000),expires_at:iso(now+3600000),status:'PUBLISHED',announcement:true,priority:0,dismissible:true};
for(const width of [320,390,768,1400]){
 const win=new Window({url:'https://fixture.test/',settings});win.happyDOM.setWindowSize({width,height:900});const doc=win.document;doc.write(read('dist/index.html','utf8'));const style=doc.createElement('style');style.textContent=['style.css','brand.css','customer-ui.css','operations/operations.css'].map(p=>read('dist/'+p,'utf8')).join('\n').replace(/@media\(/g,'@media (');doc.head.append(style);
 const header=doc.querySelector('.site-header'),navigation=doc.querySelector('#mobile-nav'),original=header.outerHTML,main=doc.querySelector('.hero').outerHTML,baseTop=win.getComputedStyle(navigation).top;let height=width<=600?136:52;const observers=[];win.ResizeObserver=class{constructor(callback){this.callback=callback;this.disconnected=false;observers.push(this);}observe(){}disconnect(){this.disconnected=true;}};
 header.getBoundingClientRect=()=>({height:102});win.HTMLElement.prototype.getBoundingClientRect=function(){return {height:this.matches('.site-announcement')?height:102};};const memory=new Map(),storage={getItem:k=>memory.get(k)||null,setItem:(k,v)=>memory.set(k,v)};
 mountAnnouncement(doc,post,storage);let banner=doc.querySelector('[data-site-announcement]');assert.equal(banner.nextElementSibling,header);assert.equal(header.outerHTML,original);assert.equal(doc.querySelector('.hero').outerHTML,main);assert(doc.body.classList.contains('has-site-announcement'));assert.equal(doc.body.style.getPropertyValue('--site-announcement-height'),height+'px');assert.equal(doc.body.style.getPropertyValue('--site-announcement-header-height'),'102px');assert.equal(win.getComputedStyle(header).position,'absolute');assert.equal(win.getComputedStyle(banner).position,'relative');assert.equal(win.getComputedStyle(banner).flexWrap,width<=600?'wrap':'nowrap');assert.equal(win.getComputedStyle(banner).boxSizing,'border-box');assert.equal(win.getComputedStyle(banner).width,'100%');assert.equal(win.getComputedStyle(banner.querySelector('div')).minWidth,'0');assert.equal(win.getComputedStyle(banner.querySelector('div')).overflowWrap,'anywhere');assert.match(banner.textContent,/Fixture workshop update.*Compact excerpt only/);assert(!banner.textContent.includes(post.body));assert(!banner.querySelector('a'));assert(banner.querySelector('button[aria-label]'));
 height+=40;observers.at(-1).callback();assert.equal(doc.body.style.getPropertyValue('--site-announcement-height'),height+'px');banner.querySelector('button').click();assert(observers.at(-1).disconnected);assert(!doc.querySelector('[data-site-announcement]'));assert(!doc.body.classList.contains('has-site-announcement'));assert.equal(doc.body.style.getPropertyValue('--site-announcement-height'),'');assert.equal(header.outerHTML,original);assert.equal(win.getComputedStyle(navigation).top,baseTop);mountAnnouncement(doc,post,storage);assert(!doc.querySelector('[data-site-announcement]'));
 mountAnnouncement(doc,{...post,id:'different',cta_url:'/news/',cta_label:'Read News'},storage);banner=doc.querySelector('[data-site-announcement]');assert.equal(banner.querySelector('a').getAttribute('href'),'/news/');assert.equal(win.getComputedStyle(banner.querySelector('a')).minHeight,'44px');assert.equal(win.getComputedStyle(banner.querySelector('a')).maxWidth,'100%');mountAnnouncement(doc,{...post,id:'nondismissible',dismissible:false,cta_url:'javascript:bad()'},storage);assert(!doc.querySelector('[data-site-announcement] button'));assert(!doc.querySelector('[data-site-announcement] a'));mountAnnouncement(doc,null,storage);assert(!doc.querySelector('[data-site-announcement]'));assert(!doc.body.classList.contains('has-site-announcement'));await win.happyDOM.close();
}
assert.equal(activeAnnouncement(open,[post],now).id,post.id);const higher={...post,id:'higher',priority:50};assert.equal(activeAnnouncement(open,[post,higher],now).id,'higher');const newer={...post,id:'newer',publication_at:iso(now-500)};assert.equal(activeAnnouncement(open,[post,newer],now).id,'newer');const alpha={...post,id:'alpha',slug:'alpha'},zulu={...post,id:'zulu',slug:'zulu'};for(const items of [[alpha,zulu],[zulu,alpha]])assert.equal(activeAnnouncement(open,items,now).id,'alpha');for(const change of [{publication_at:iso(now+1)},{expires_at:iso(now)},{announcement:false},{status:'DRAFT'},{status:'ARCHIVED'}])assert.equal(activeAnnouncement(open,[{...post,...change}],now),null);assert.equal(open.state,'OPEN');
const w=new Window({url:'https://fixture.test/admin/site-operations/',settings}),d=w.document;d.write(read('dist/admin/site-operations/index.html','utf8'));let writes=[],posts=[],allow=true,fail=false,release=null,confirmations=[];const repo={store:async()=>open,posts:async()=>posts,audit:async()=>[],savePost:async p=>{writes.push(p);if(fail)throw Error('Fixture request failed');if(release===true)await new Promise(r=>release=r);const result={...p,id:'saved',publication_at:p.status==='PUBLISHED'?iso(Date.now()):p.publication_at,updated_at:iso(Date.now())};posts=[result];return result;}};const ui=bootOperationsAdmin({document:d,repo,confirm:message=>{confirmations.push(message);return allow;}});await ui.ready;const form=d.querySelector('#news-form'),f=name=>form.elements.namedItem(name),feedback=d.querySelector('#news-action-status'),tick=()=>new Promise(r=>setTimeout(r,0)),fill=()=>{d.querySelector('#new-post').click();for(const [name,value] of Object.entries({title:'Fixture',slug:'fixture',excerpt:'Fixture excerpt',body:'Fixture body',priority:'0',publication_at:'',expires_at:'',cta_label:'',cta_url:''}))f(name).value=value;f('announcement').checked=true;},submit=state=>form.dispatchEvent(new w.SubmitEvent('submit',{cancelable:true,bubbles:true,submitter:form.querySelector('button[value="'+state+'"]')}));
assert.match(d.querySelector('#announcement-priority-help').textContent,/highest priority.*Zero is valid/s);assert.equal(f('priority').getAttribute('aria-describedby'),'announcement-priority-help');fill();assert(form.checkValidity());f('title').value='';submit('PUBLISHED');assert.equal(writes.length,0);assert.equal(confirmations.length,0);assert.match(feedback.textContent,/Title/);assert.equal(feedback.dataset.feedback,'error');assert.equal(f('title').getAttribute('aria-invalid'),'true');f('title').value='Fixture';f('title').dispatchEvent(new w.Event('input',{bubbles:true}));assert(!f('title').hasAttribute('aria-invalid'));
for(const value of ['','-1','101','0.5']){fill();f('priority').value=value;submit('PUBLISHED');assert.equal(writes.length,0);assert.equal(feedback.dataset.feedback,'error');}fill();allow=false;submit('PUBLISHED');assert.match(feedback.textContent,/cancelled.*Nothing was saved/);assert.equal(writes.length,0);allow=true;fail=true;submit('PUBLISHED');await tick();assert.equal(writes[0].priority,0);assert.match(feedback.textContent,/Fixture request failed/);assert.equal(feedback.dataset.feedback,'error');fail=false;
for(const state of ['DRAFT','PUBLISHED','SCHEDULED','ARCHIVED']){fill();if(state==='SCHEDULED')f('publication_at').value='2027-10-06T12:00';submit(state);await tick();assert.equal(writes.at(-1).priority,0);assert.equal(writes.at(-1).status,state);assert.equal(feedback.dataset.feedback,'success');assert.match(feedback.textContent,new RegExp('News saved: '+state));}assert(confirmations.some(m=>m.includes('Effective posts are public')));
fill();release=true;const before=writes.length;submit('PUBLISHED');assert.equal(feedback.dataset.feedback,'loading');assert.equal(feedback.getAttribute('aria-busy'),'true');assert(form.querySelector('button[value=PUBLISHED]').disabled);submit('PUBLISHED');assert.equal(writes.length,before+1);release();await tick();assert.equal(feedback.getAttribute('aria-busy'),'false');assert.equal(feedback.dataset.feedback,'success');await w.happyDOM.close();
const baseline='b334ccb3e0f449e432518c5b30e79a07a3e35e85',allowed=new Set(['dist/operations/public.mjs','dist/operations/operations.css','dist/admin/site-operations/operations.mjs','dist/admin/site-operations/index.html','tests/announcement-hotfix.mjs','tests/announcement-priority-db.mjs','docs/announcement-hotfix.md']);for(const path of execFileSync('git',['diff',baseline,'--name-only'],{encoding:'utf8'}).trim().split('\n').filter(Boolean))assert(allowed.has(path),'Unrelated change '+path);console.log('Announcement hotfix: above-header flow/offsets, resize/mobile, unchanged header/hero, dismissal, compact/optional content, priority 0/ties, all action feedback and protected scope PASS');
