import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createAssemblyStore,assemblyStorageKey,lesPaulKitDefinitionId,kitReferenceStatus} from '../dist/admin/assemblies.mjs';
import {createComponentStore,storageKey} from '../dist/admin/data.mjs';
import {kitDefinitions} from '../dist/wiring-kits/kit-seed.mjs';
const memory=new Map(),storage={getItem:k=>memory.get(k)??null,setItem:(k,v)=>memory.set(k,v)};
const liveBuilderBefore=JSON.stringify(kitDefinitions);const components=createComponentStore(storage);const inventory=components.list(),before=memory.get(storageKey);let store=createAssemblyStore(storage),kit=store.list().find(a=>a.id===lesPaulKitDefinitionId);
assert.equal(kit.kind,'wiring-kit');assert.equal(kit.kitDefinition.family,'les-paul');assert.equal(kit.kitDefinition.basePrice,5999);assert.equal(kit.kitDefinition.showOnWiringKits,true);assert.equal(kit.kitDefinition.builderEnabled,true);assert.equal(kit.kitDefinition.defaults.wiring,'50s');assert.equal(kit.kitDefinition.defaults.componentIds.potentiometers,'pot-short-cts-a');assert.equal(kit.kitDefinition.builderOptions.find(group=>group.key==='pots').defaultValue,'CTS');assert.equal(kit.kitDefinition.componentResolvers[0].key,'potentiometers');assert(kit.kitDefinition.permittedComponentIds.includes('pot-short-cts-a'));assert.deepEqual(kit.bom,[{componentId:'pot-short-cts-a',quantity:4},{componentId:'sbe-200',quantity:1},{componentId:'cde-047',quantity:1}]);
kit=store.save({...kit,active:false,kitDefinition:{...kit.kitDefinition,showOnWiringKits:false,builderEnabled:false,permittedComponentIds:[...kit.kitDefinition.permittedComponentIds,'pot-short-alpha-a'],defaults:{...kit.kitDefinition.defaults,componentIds:{...kit.kitDefinition.defaults.componentIds,potentiometers:'pot-short-alpha-a'}}}},kit.id);
kit=createAssemblyStore(storage).list().find(a=>a.id===lesPaulKitDefinitionId);assert.equal(kit.active,false);assert.equal(kit.kitDefinition.showOnWiringKits,false);assert.equal(kit.kitDefinition.builderEnabled,false);assert.equal(kit.kitDefinition.defaults.componentIds.potentiometers,'pot-short-alpha-a');assert(kit.kitDefinition.permittedComponentIds.includes('pot-short-alpha-a'));
assert.throws(()=>store.save({...kit,kitDefinition:{...kit.kitDefinition,defaults:{...kit.kitDefinition.defaults,componentIds:{...kit.kitDefinition.defaults.componentIds,neckCapacitor:'not-permitted'}}}},kit.id),/also be permitted/);
const withMissing={...kit,kitDefinition:{...kit.kitDefinition,permittedComponentIds:[...kit.kitDefinition.permittedComponentIds,'missing-component']}};assert.deepEqual(kitReferenceStatus(withMissing,inventory).missing,['missing-component']);
let a=store.save({name:'Test harness',sku:'test-assembly',category:'Wiring Kit',active:true,bom:[{componentId:inventory[0].id,quantity:2}]});
a=store.save({...a,name:'Edited assembly',active:false,bom:[...a.bom,{componentId:inventory[1].id,quantity:4}]},a.id);a.bom[0].quantity=3;a.bom.splice(1,1);store.save(a,a.id);
store=createAssemblyStore(storage);a=store.list().find(item=>item.id===a.id);assert.equal(a.name,'Edited assembly');assert.equal(a.active,false);assert.equal(a.kind,'assembly');assert.deepEqual(a.bom,[{componentId:inventory[0].id,quantity:3}]);
for(const quantity of [0,-1,1.5,'',Infinity])assert.throws(()=>store.save({...a,bom:[{componentId:inventory[0].id,quantity}]},a.id),/positive whole/);
assert.throws(()=>store.save({...a,sku:'TEST-ASSEMBLY'}),/already exists/);
assert.equal(memory.get(storageKey),before,'Assembly operations never modify component records');
store.remove(a.id);assert.equal(createAssemblyStore(storage).list().length,1);assert.equal(memory.get(storageKey),before);
assert.throws(()=>createAssemblyStore({getItem:()=>'{bad',setItem:()=>assert.fail()}).list(),/No data was reset/);
const legacyRecord={id:'legacy',name:'Legacy assembly',sku:'LEGACY',category:'Other',active:true,bom:[{componentId:'pot-short-cts-a',quantity:1}]},legacyMemory=new Map([[assemblyStorageKey,JSON.stringify({version:1,items:[legacyRecord]})]]),legacyStore=createAssemblyStore({getItem:k=>legacyMemory.get(k)??null,setItem:(k,v)=>legacyMemory.set(k,v)}),migrated=legacyStore.list();assert.deepEqual(migrated.find(item=>item.id==='legacy'),legacyRecord);assert(migrated.some(item=>item.id===lesPaulKitDefinitionId));assert.equal(JSON.parse(legacyMemory.get(assemblyStorageKey)).version,3);
assert.equal(JSON.stringify(kitDefinitions),liveBuilderBefore,'P03A must not alter the live Builder configuration');
const adminMarkup=await readFile(new URL('../dist/admin/index.html',import.meta.url),'utf8'),adminUI=await readFile(new URL('../dist/admin/assembly-ui.mjs',import.meta.url),'utf8');for(const control of ['name="kind"','name="basePrice"','name="showOnWiringKits"','name="builderEnabled"','id="kit-permitted-components"','id="kit-builder-options"','id="kit-variant-mappings"','id="kit-default-components"'])assert(adminMarkup.includes(control),control+' Admin control missing');assert(adminUI.includes('kitReferenceStatus'));
console.log('Assemblies and Kit Definitions: legacy compatibility, Les Paul seed/BOM, flags, base price, generic Builder options/mappings, safe references, edits and persistence passed.');
const {calculateBuildable}=await import('../dist/admin/assemblies.mjs');
const parts=[{id:'pot',name:'CTS A500k',active:true,stock:20},{id:'cap',name:'Tone capacitor',active:true,stock:40}];
const bom=[{componentId:'pot',quantity:4},{componentId:'cap',quantity:2}];
let result=calculateBuildable(bom,parts);assert.equal(result.quantity,5);assert.deepEqual(result.limiting.map(p=>p.id),['pot']);
parts[0].stock=10;assert.equal(calculateBuildable(bom,parts).quantity,2);parts[0].stock=0;assert.equal(calculateBuildable(bom,parts).quantity,0);
assert.equal(calculateBuildable([],parts).quantity,null);assert.equal(calculateBuildable([{componentId:'missing',quantity:1}],parts).quantity,null);
parts[0].active=false;assert.match(calculateBuildable(bom,parts).warnings.join(),/Inactive component/);parts[0].active=true;parts[0].stock=10;
assert.equal(calculateBuildable([{componentId:'pot',quantity:4},{componentId:'pot',quantity:4}],parts).quantity,1,'Duplicate rows must aggregate their requirements');
assert.equal(calculateBuildable([{componentId:'pot',quantity:0}],parts).quantity,null);assert.equal(calculateBuildable([{componentId:'pot',quantity:1.5}],parts).quantity,null);
assert.equal(calculateBuildable([{componentId:'pot',quantity:true}],parts).quantity,null);
assert.equal(calculateBuildable([{componentId:'pot',quantity:Number.MAX_SAFE_INTEGER},{componentId:'pot',quantity:1}],parts).quantity,null);
parts[0].stock=NaN;assert.match(calculateBuildable(bom,parts).warnings.join(),/Invalid stock/);
parts[0].stock=42;parts[1].stock=100;assert.equal(calculateBuildable([{componentId:'pot',quantity:1},{componentId:'cap',quantity:1}],parts).quantity,42);
const live=store.save({name:'Live central stock check',sku:'live',category:'Other',active:true,bom:[{componentId:'pot-short-cts-a',quantity:4}]});assert.equal(calculateBuildable(live.bom,components.list()).quantity,1);
components.changeStock('pot-short-cts-a',10);assert.equal(calculateBuildable(live.bom,components.list()).quantity,2);components.changeStock('pot-short-cts-a',0);assert.equal(calculateBuildable(live.bom,components.list()).quantity,0);
const centralSnapshot=memory.get(storageKey);calculateBuildable(live.bom,components.list());store.remove(live.id);assert.equal(memory.get(storageKey),centralSnapshot);
console.log('Buildable: limiting component, round down, live central stock, zero stock, empty/missing/inactive/invalid BOM, duplicate rows, overflow and no deductions passed.');
