import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {assemblyStorageKey,lesPaulKitAssembly} from '../dist/admin/assemblies.mjs';
import {prepareAssemblyExport,validateAssemblyExport} from '../dist/admin/assembly-export.mjs';

const memory=new Map();let writes=0;
const storage={getItem:key=>memory.get(key)??null,setItem:(key,value)=>{writes++;memory.set(key,value);}};
assert.throws(()=>prepareAssemblyExport(storage),/No saved Assembly record/);
assert.equal(writes,0,'Absent browser data must not seed default Assemblies.');
const kit=structuredClone(lesPaulKitAssembly);
kit.kitDefinition.basePrice=7777;
kit.kitDefinition.defaults.pots='Alpha';
kit.kitDefinition.permittedComponentIds.push('custom-component');
kit.kitDefinition.metadata={...kit.kitDefinition.metadata,privateBusinessNote:'original'};
const raw=JSON.stringify({version:3,items:[kit]});memory.set(assemblyStorageKey,raw);
const before=writes,{payload,summary}=prepareAssemblyExport(storage,{now:()=> '2026-09-24T19:00:00.000Z'});
assert.equal(writes,before,'Preview/export must be read-only.');
assert.equal(memory.get(assemblyStorageKey),raw,'The original record stays byte-for-byte unchanged.');
assert.equal(payload.raw,raw);
assert.equal(payload.format,'apparition-assembly-kit-export-v1');
assert.equal(payload.storageKey,assemblyStorageKey);
assert.deepEqual([summary.assemblyCount,summary.kitDefinitionCount,summary.bomRows,summary.storedVersion,summary.lesPaulFound],[1,1,kit.bom.length,3,true]);
assert.deepEqual(JSON.parse(payload.raw).items[0],kit,'All defaults, permitted IDs, pricing and private metadata remain intact.');
const invalid=change=>{const data=JSON.parse(raw);change(data);assert.throws(()=>validateAssemblyExport(JSON.stringify(data)));};
invalid(data=>{data.items.push(structuredClone(data.items[0]));});
invalid(data=>{data.items[0].bom[0].quantity=-1;});
invalid(data=>{data.items[0].kitDefinition.basePrice=-100;});
invalid(data=>{data.items[0].kitDefinition.showOnWiringKits='yes';});
assert.throws(()=>validateAssemblyExport('{'),/unreadable/);
memory.set(assemblyStorageKey,'{');assert.throws(()=>prepareAssemblyExport(storage),/unreadable/);
assert.equal(memory.get(assemblyStorageKey),'{','Unreadable data must not be overwritten.');
const html=readFileSync(new URL('../dist/admin/index.html',import.meta.url),'utf8');
assert.match(html,/id="preview-assembly-export"/);
assert.match(html,/id="download-assembly-export"[^>]*hidden/);
assert.match(html,/admin-gate\.mjs/);
const admin=readFileSync(new URL('../dist/admin/admin.mjs',import.meta.url),'utf8');
assert.match(admin,/latest\.payload\.raw!==pendingAssemblyExport\.payload\.raw/);
assert.doesNotMatch(admin,/createAssemblyStore/);
console.log('P05C private Assembly capture: no seed/write, exact source preservation, malformed-record rejection, authenticated Admin entry, preview/download and stale-preview guard passed.');
