import assert from 'node:assert/strict';
import {createAssemblyStore,assemblyStorageKey} from '../dist/admin/assemblies.mjs';
import {createComponentStore,storageKey} from '../dist/admin/data.mjs';
const memory=new Map(),storage={getItem:k=>memory.get(k)??null,setItem:(k,v)=>memory.set(k,v)};
const components=createComponentStore(storage);const inventory=components.list(),before=memory.get(storageKey);let store=createAssemblyStore(storage);assert.deepEqual(store.list(),[]);
let a=store.save({name:'Test harness',sku:'test-assembly',category:'Wiring Kit',active:true,bom:[{componentId:inventory[0].id,quantity:2}]});
a=store.save({...a,name:'Edited assembly',active:false,bom:[...a.bom,{componentId:inventory[1].id,quantity:4}]},a.id);a.bom[0].quantity=3;a.bom.splice(1,1);store.save(a,a.id);
store=createAssemblyStore(storage);assert.equal(store.list()[0].name,'Edited assembly');assert.equal(store.list()[0].active,false);assert.deepEqual(store.list()[0].bom,[{componentId:inventory[0].id,quantity:3}]);
for(const quantity of [0,-1,1.5,'',Infinity])assert.throws(()=>store.save({...a,bom:[{componentId:inventory[0].id,quantity}]},a.id),/positive whole/);
assert.throws(()=>store.save({...a,sku:'TEST-ASSEMBLY'}),/already exists/);
assert.equal(memory.get(storageKey),before,'Assembly operations never modify component records');
store.remove(a.id);assert.deepEqual(createAssemblyStore(storage).list(),[]);assert.equal(memory.get(storageKey),before);
assert.throws(()=>createAssemblyStore({getItem:()=>'{bad',setItem:()=>assert.fail()}).list(),/No data was reset/);
console.log('Assemblies: create/edit/BOM add/edit/remove, unique SKU, quantity validation, delete, persistence and unchanged central inventory passed.');
const {calculateBuildable}=await import('../dist/admin/assemblies.mjs');
const parts=[{id:'pot',name:'CTS A500k',active:true,stock:20},{id:'cap',name:'Tone capacitor',active:true,stock:40}];
const bom=[{componentId:'pot',quantity:4},{componentId:'cap',quantity:2}];
let result=calculateBuildable(bom,parts);assert.equal(result.quantity,5);assert.deepEqual(result.limiting.map(p=>p.id),['pot']);
parts[0].stock=10;assert.equal(calculateBuildable(bom,parts).quantity,2);parts[0].stock=0;assert.equal(calculateBuildable(bom,parts).quantity,0);
assert.equal(calculateBuildable([],parts).quantity,null);assert.equal(calculateBuildable([{componentId:'missing',quantity:1}],parts).quantity,null);
parts[0].active=false;assert.match(calculateBuildable(bom,parts).warnings.join(),/Inactive component/);parts[0].active=true;parts[0].stock=10;
assert.equal(calculateBuildable([{componentId:'pot',quantity:4},{componentId:'pot',quantity:4}],parts).quantity,1,'Duplicate rows must aggregate their requirements');
assert.equal(calculateBuildable([{componentId:'pot',quantity:0}],parts).quantity,null);assert.equal(calculateBuildable([{componentId:'pot',quantity:1.5}],parts).quantity,null);
assert.equal(calculateBuildable([{componentId:'pot',quantity:true}],parts).quantity,null);
assert.equal(calculateBuildable([{componentId:'pot',quantity:Number.MAX_SAFE_INTEGER},{componentId:'pot',quantity:1}],parts).quantity,null);
parts[0].stock=NaN;assert.match(calculateBuildable(bom,parts).warnings.join(),/Invalid stock/);
parts[0].stock=42;parts[1].stock=100;assert.equal(calculateBuildable([{componentId:'pot',quantity:1},{componentId:'cap',quantity:1}],parts).quantity,42);
const live=store.save({name:'Live central stock check',sku:'live',category:'Other',active:true,bom:[{componentId:'pot-short-cts-a',quantity:4}]});assert.equal(calculateBuildable(live.bom,components.list()).quantity,1);
components.changeStock('pot-short-cts-a',10);assert.equal(calculateBuildable(live.bom,components.list()).quantity,2);components.changeStock('pot-short-cts-a',0);assert.equal(calculateBuildable(live.bom,components.list()).quantity,0);
const centralSnapshot=memory.get(storageKey);calculateBuildable(live.bom,components.list());store.remove(live.id);assert.equal(memory.get(storageKey),centralSnapshot);
console.log('Buildable: limiting component, round down, live central stock, zero stock, empty/missing/inactive/invalid BOM, duplicate rows, overflow and no deductions passed.');
