import assert from 'node:assert/strict';
import {buildContext,assemblyLines,buildSheetURL} from '../dist/admin/orders/build-sheet/model.mjs';
import {createKitSnapshot} from '../dist/les-paul-kits/snapshot.mjs';
const snap=createKitSnapshot({wiring:'modern',bleed:'duncan',matching:'precision'});
const order={id:'order-1',reference:'AI-10001',createdAt:'2026-09-17T10:00:00Z',channel:'MANUAL',status:'PAID',customer:{name:'Test customer'},items:[{type:'component'},{type:'kit',name:'Purchased kit',quantity:2,snapshot:snap}]};
const before=JSON.stringify(order),c=buildContext(order,null,2);
assert.equal(c.itemIndex,1);assert.equal(c.customer,'Test customer');assert.equal(c.reference,'AI-10001');assert.equal(c.kitName,snap.kitName);assert.equal(c.unit,2);assert.equal(assemblyLines(order).length,1);assert.equal(assemblyLines({items:[{type:'component'}]}).length,0);
assert.throws(()=>buildContext(order,0),/does not require/);assert.throws(()=>buildContext(order,1,3),/within/);
c.snapshot.configuration.wiring='50s';assert.equal(JSON.stringify(order),before);assert(buildSheetURL(order.id,1,2).includes('unit=2'));
console.log('Build Sheet foundation: saved order identity, customer, platform, per-unit isolation and component-only exclusion passed.');
import {pickList,captureBOM} from '../dist/admin/orders/build-sheet/model.mjs';
import {createProductionStore} from '../dist/admin/orders/build-sheet/production.mjs';
const context=buildContext(order,1,1),rows=pickList(context);
assert.equal(rows.find(r=>r.role==='potentiometers').quantity,4);assert.equal(rows.filter(r=>r.role.includes('ToneCapacitor')).reduce((n,r)=>n+r.quantity,0),2);assert(!rows.some(r=>r.role==='selector'));
const inv=[{id:'cap',sku:'CAP',name:'1nF',active:true,stock:20,specs:{Value:'1nF'}},{id:'res',sku:'RES',name:'150kΩ',active:true,stock:10,specs:{Resistance:'150kΩ'}}],bom={id:'a',name:'Duncan assembly',sku:'ASSY',active:true,bom:[{componentId:'cap',quantity:1},{componentId:'res',quantity:1}]};
const plan=captureBOM(bom,inv,2);assert.deepEqual(plan.parts.map(p=>p.quantity),[2,2]);bom.bom[0].quantity=50;inv[0].name='Renamed';assert.equal(plan.parts[0].quantity,2);assert.equal(plan.parts[0].name,'1nF');assert.throws(()=>captureBOM({...bom,bom:[]},inv,2),/empty/);
const memory=new Map(),storage={getItem:k=>memory.get(k)??null,setItem:(k,v)=>memory.set(k,v)},lock=async(k,fn)=>fn(),production=createProductionStore(storage,{lock});
await production.update(context,r=>{r.picked[rows[0].id]=true;r.bomPlans.bleed=plan;});assert.equal(createProductionStore(storage,{lock}).get(context).picked[rows[0].id],true);assert.deepEqual(production.get(buildContext(order,1,2)).picked,{});assert.equal(JSON.stringify(order),before);assert.equal(inv[0].stock,20);
console.log('Picking: supplied quantities, per-unit persisted states, captured existing BOM expansion, historical separation and no stock deductions passed.');
import {savedDiagram} from '../dist/admin/orders/build-sheet/wiring.mjs';
const frozen=JSON.stringify(context.snapshot);assert(savedDiagram(context).includes('<svg'));assert.equal(JSON.stringify(context.snapshot),frozen);
assert.equal(savedDiagram({...context,snapshot:{...context.snapshot,diagram:null}}),null);
const unsupported=structuredClone(context);unsupported.snapshot.diagram.circuit.state.guitar='prs';assert.equal(savedDiagram(unsupported),null);
await production.update(context,r=>{r.assemblyNotes='Check orientation.\nRetain customer hardware.';});assert.equal(createProductionStore(storage,{lock}).get(context).assemblyNotes,'Check orientation.\nRetain customer hardware.');assert.equal(JSON.stringify(order),before);
console.log('Wiring: saved circuit rendering, unsupported fallback, immutable purchase and persisted assembly notes passed.');
import {qcDefinition,validateQC} from '../dist/admin/orders/build-sheet/qc-model.mjs';
const qdef=qcDefinition(context);assert.equal(qdef.measurements.length,6);assert(qdef.checks.some(([k])=>k==='matching'));assert(qdef.checks.some(([k])=>k==='bleedOperation'));
const standard=structuredClone(context);standard.snapshot.configuration.matching='standard';standard.snapshot.components=standard.snapshot.components.filter(p=>p.role!=='trebleBleeds');assert(!qcDefinition(standard).checks.some(([k])=>['matching','bleedOperation'].includes(k)));
const qc={builder:'Builder',buildDate:'2026-09-22',status:'READY FOR QC',result:'NOT TESTED',person:'',date:'',notes:'Check on bench',checks:{picked:true},measurements:{[qdef.measurements[0].id]:'501.8'}};validateQC(qc,qdef);assert.throws(()=>validateQC({...qc,status:'QC PASSED'},qdef),/agree/);assert.throws(()=>validateQC({...qc,measurements:{[qdef.measurements[0].id]:'-2'}},qdef),/positive/);
await production.update(context,r=>{r.qc=qc;});assert.deepEqual(createProductionStore(storage,{lock}).get(context).qc,qc);assert.equal(JSON.stringify(order),before);assert.equal(inv[0].stock,20);
console.log('QC: conditional checks, dynamic measurements, validation, persistence and immutable purchase passed.');
import {printValue} from '../dist/admin/orders/build-sheet/print.mjs';
assert.equal(printValue({type:'checkbox',checked:true}),'[X]');assert.equal(printValue({type:'checkbox',checked:false}),'[ ]');assert.equal(printValue({tagName:'TEXTAREA',value:'First\nSecond'}),'First\nSecond');assert.equal(printValue({tagName:'INPUT',value:'501.8'}),'501.8');assert.equal(printValue({tagName:'SELECT',selectedOptions:[{textContent:'QC PASSED'}]}),'QC PASSED');
console.log('Print values: checked/unchecked state, multiline notes, measurements and status preserved.');
