import assert from 'node:assert/strict';
import {createComponentStore,storageKey} from '../dist/admin/data.mjs';
import {prepareComponentExport,validateComponentExport} from '../dist/admin/component-export.mjs';
import {readFileSync} from 'node:fs';

const memory=new Map(),storage={getItem:key=>memory.get(key)??null,setItem:(key,value)=>{writes++;memory.set(key,value);}};
let writes=0;
assert.throws(()=>prepareComponentExport(storage),/No saved Component record/);
assert.equal(writes,0,'Export must never trigger a seed write.');
createComponentStore(storage).list();
const original=JSON.parse(memory.get(storageKey));
original.items[0]={...original.items[0],stock:23,active:false,inKits:true,individually:false,salePrice:1550,kitPrice:299,internalUnitCost:80,image:'data:image/png;base64,iVBORw0KGgo='};
original.items[1]={...original.items[1],image:{kind:'object',key:'components/example.png',url:'https://example.org/example.png'}};
const raw=JSON.stringify(original);memory.set(storageKey,raw);
const before=writes,{payload,summary}=prepareComponentExport(storage,{now:()=> '2026-09-24T00:00:00.000Z'});
assert.equal(writes,before,'Export must not modify existing records.');assert.equal(memory.get(storageKey),raw,'Original envelope stays byte-exact.');
assert.equal(payload.raw,raw);assert.equal(payload.storageKey,storageKey);
assert.equal(payload.format,'apparition-component-inventory-export-v1');
assert.equal(summary.componentCount,original.items.length);assert.equal(summary.inventoryCount,original.items.length);
assert.deepEqual(summary.embeddedImages,[original.items[0].id]);assert.deepEqual(summary.objectImages,[original.items[1].id]);
const first=JSON.parse(payload.raw).items[0];
for(const field of ['id','sku','stock','active','inKits','individually','salePrice','kitPrice','internalUnitCost','image'])assert.deepEqual(first[field],original.items[0][field]);
const invalid=mutate=>{const data=structuredClone(original);mutate(data);assert.throws(()=>validateComponentExport(JSON.stringify(data)));};
invalid(data=>{data.items[1].id=data.items[0].id;});invalid(data=>{data.items[1].sku=data.items[0].sku.toUpperCase();});
invalid(data=>{data.items[1].stock=-1;});invalid(data=>{data.items[1].stock=1.5;});
invalid(data=>{delete data.items[1].active;});invalid(data=>{data.items[1].kitPrice=-10;});
invalid(data=>{data.items[1].specs=[];});invalid(data=>{data.items[1].image='bad image';});
assert.throws(()=>validateComponentExport('{'),/unreadable/);
memory.set(storageKey,'{');assert.throws(()=>prepareComponentExport(storage),/unreadable/);assert.equal(memory.get(storageKey),'{');
const html=readFileSync(new URL('../dist/admin/index.html',import.meta.url),'utf8');
assert.match(html,/id="preview-component-export"/);assert.match(html,/id="download-component-export"[^>]*hidden/);
const admin=readFileSync(new URL('../dist/admin/admin.mjs',import.meta.url),'utf8');
assert.match(admin,/latest\.payload\.raw!==pendingExport\.payload\.raw/);
console.log('P05B export bridge: no seeding or writes, exact data preservation, inventory and images, invalid-record rejection, explicit Admin preview/download and stale-preview guard passed.');
