import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {Window} from 'happy-dom';
import {createForgeProjectApp} from '../dist/forge-pro/app.mjs';import {capabilities} from '../dist/forge-pro/capabilities.mjs';import {createSnapshot} from '../dist/forge-pro/domain.mjs';import {createProjectStore} from '../dist/electronics/state/project.mjs';import {mountProfessionalBridge} from '../dist/forge-pro/editor-bridge.mjs';import {forgeCircuit} from '../dist/circuit-forge/model.mjs';import {createForgeRepository} from '../dist/forge-pro/repository.mjs';
const win=new Window({url:'https://fixture.test/circuit-forge/projects/',settings:{disableCSSFileLoading:true,disableJavaScriptFileLoading:true,disableJavaScriptEvaluation:true}}),doc=win.document;doc.write(readFileSync('dist/circuit-forge/projects/index.html','utf8'));const root=doc.getElementById('forge-pro-root'),status=doc.getElementById('forge-pro-status'),owner='10000000-0000-4000-8000-000000000001';
const auth={getUser:async()=>({data:{user:{id:owner,email_confirmed_at:'2026-10-01',is_anonymous:false}}}),onAuthStateChange(fn){this.listener=fn;return {data:{subscription:{unsubscribe(){}}}}}},db={projects:[],revisions:[],templates:[],measurements:[],documents:[]};let sequence=0,grants=Object.values(capabilities),calls=[];
const uuid=()=> '20000000-0000-4000-8000-'+String(++sequence).padStart(12,'0');
const repository={capabilities:async()=>grants,list:async()=>structuredClone(db.projects),project:async id=>structuredClone(db.projects.find(p=>p.id===id)),revisions:async id=>structuredClone(db.revisions.filter(r=>r.project_id===id).sort((a,b)=>b.sequence-a.sequence)),templates:async()=>structuredClone(db.templates),measurements:async id=>structuredClone(db.measurements.filter(m=>m.project_id===id)),documents:async id=>structuredClone(db.documents.filter(d=>d.project_id===id)),command:async(action,data)=>{calls.push({action,data});if(action==='create'){const id=uuid(),rid=uuid(),s=data.snapshot,p={id,owner_id:owner,title:s.metadata.title,notes:s.metadata.notes,instrument:s.metadata.instrument,lifecycle:'ACTIVE',version:1,current_revision_id:rid,updated_at:'2026-10-07T10:00:00Z'};db.projects.push(p);db.revisions.push({id:rid,project_id:id,sequence:1,name:data.name,snapshot:s,created_at:p.updated_at});return structuredClone(p);}const p=db.projects.find(p=>p.id===data.project_id);if(action==='open')return p;if(action==='save'){const id=uuid();p.version++;p.current_revision_id=id;p.title=data.snapshot.metadata.title;p.instrument=data.snapshot.metadata.instrument;db.revisions.push({id,project_id:p.id,sequence:p.version,name:data.name,note:data.note,snapshot:data.snapshot,created_at:p.updated_at});return structuredClone(p);}if(action==='measurement'){const m={...data,id:uuid(),revision_id:p.current_revision_id};db.measurements.push(m);return m;}if(action==='template'){const t={id:uuid(),name:data.name,snapshot:db.revisions.find(r=>r.id===p.current_revision_id).snapshot};db.templates.push(t);return t;}if(action==='document'){const r=db.revisions.find(r=>r.id===data.revision_id),d={id:uuid(),project_id:p.id,kind:'TECHNICAL_BUILD_SHEET',created_at:p.updated_at,payload:{schema:1,snapshot:r.snapshot,revision:{id:r.id,name:r.name,sequence:r.sequence},measurements:structuredClone(db.measurements)}};db.documents.push(d);return d;}if(action==='archive'){p.lifecycle='ARCHIVED';return p;}throw Error('Fixture action unavailable');}};
let downloaded='';const app=createForgeProjectApp({root,status,auth,repository,storage:win.localStorage,session:win.sessionStorage,location:win.location,navigate:()=>{},download:html=>{downloaded=html;}});
await app.start();assert.match(status.textContent,/library is ready/);const tick=async()=>{for(let i=0;i<30;i++){await new Promise(r=>setTimeout(r,0));if(root.getAttribute('aria-busy')!=='true')return;}throw Error('UI did not settle');};
function reveal(b){const view=b.closest('[data-shell-view]')?.dataset.shellView||'instrument';const tab=[...root.querySelectorAll('.forge-shell-views button')].find(n=>n.getAttribute('aria-controls')===b.closest('[data-shell-view]')?.id)||[...root.querySelectorAll('.forge-shell-views button')].find(n=>n.textContent==='Instrument');tab?.click();}
function submit(text,values={}){const b=[...root.querySelectorAll('button')].find(n=>n.textContent===text),form=b.closest('form');reveal(b);assert(b&&!b.disabled);for(const [key,v] of Object.entries(values))form.elements.namedItem(key).value=v;if(text==='Save new revision')[...root.querySelectorAll('.forge-shell-appbar button')].find(n=>n.textContent==='Save cloud revision').click();else form.dispatchEvent(new win.Event('submit',{bubbles:true,cancelable:true}));}
submit('Create project',{title:'Bench HH'});await tick();assert.equal(app.state().project.title,'Bench HH');assert(root.querySelector('.forge-pro-detail'));assert(root.querySelector('.forge-app-shell'));assert.equal(doc.activeElement,root.querySelector('.forge-shell-workspace>h2'));assert.equal(app.state().activeView,'instrument');assert.equal(root.getAttribute('data-project-id'),app.state().project.id);const created=app.state().project;[...root.querySelectorAll('button')].find(b=>b.textContent==='Back to Projects').click();await tick();assert.equal(app.state().project,null);assert(!win.location.search.includes('project='));[...root.querySelectorAll('button')].find(b=>b.textContent==='Open project').click();await tick();assert.equal(app.state().project.id,created.id);assert.equal(app.state().activeView,'instrument');assert(win.location.search.includes(created.id));assert([...root.querySelectorAll('.forge-shell-views button')].find(b=>b.textContent==='Compare').disabled);
const draft=root.querySelector('[data-project-metadata] [name="notes"]');draft.value='Not saved yet';draft.dispatchEvent(new win.Event('input',{bubbles:true}));const beforeSwitch=calls.length;[...root.querySelectorAll('.forge-shell-views button')].find(b=>b.textContent==='Measurements').click();[...root.querySelectorAll('.forge-shell-views button')].find(b=>b.textContent==='Instrument').click();assert.equal(root.querySelector('[data-project-metadata] [name="notes"]'),draft);assert.equal(draft.value,'Not saved yet');assert.equal(calls.length,beforeSwitch);assert(root.querySelector('.forge-shell-appbar').textContent.includes('Unsaved'));
submit('Save new revision',{title:'Customer final',instrument_manufacturer:'PRS',instrument_year:'2025',revision_name:'V2'});await tick();assert.equal(app.state().project.version,2);assert.equal(app.state().project.instrument.year,2025);
const metadataNotes=root.querySelector('[data-project-metadata] [name="notes"]');metadataNotes.value='Uncommitted bench notes';metadataNotes.dispatchEvent(new win.Event('input',{bubbles:true}));submit('Record measurement',{value:'487.6123',nominal:'500',unit:'kohm'});await tick();assert.equal(db.measurements[0].value,487.6123);assert.equal(root.querySelector('[data-project-metadata] [name="notes"]').value,'Uncommitted bench notes');assert.notEqual(db.projects[0].notes,'Uncommitted bench notes');submit('Save as personal template',{template_name:'Standard HH'});await tick();assert.equal(db.templates.length,1);
const click=text=>{const b=[...root.querySelectorAll('button')].find(n=>n.textContent.startsWith(text));assert(b&&!b.disabled);reveal(b);b.click();};click('Compare structured');await tick();assert(root.textContent.includes('instrument/project.title'));click('Generate current');await tick();click('Download / print');await tick();assert(downloaded.includes('<svg'));assert(downloaded.includes('487.6123'));
const ids=[...root.querySelectorAll('[id]')].map(n=>n.id);assert.equal(ids.length,new Set(ids).size);for(const n of root.querySelectorAll('input,select,textarea'))assert(n.closest('label'));
const p=app.state().project,local={version:1,electronics:{version:1}};win.sessionStorage.setItem('apparition.forge-pro.pending',JSON.stringify({owner_id:owner,project_id:p.id,version:1,local}));await app.start();const before=calls.length;submit('Save new revision');await tick();assert.match(status.textContent,/changed while/);assert.equal(calls.length,before);assert(win.sessionStorage.getItem('apparition.forge-pro.pending'));
assert.equal(root.querySelector('.forge-pro-detail [name="title"]').value,'Customer final');const edit=root.querySelector('.forge-pro-detail [name="title"]');edit.value='UNSAVED FORM VALUE';submit('Save new revision');await tick();assert.equal(root.querySelector('.forge-pro-detail [name="title"]').value,'UNSAVED FORM VALUE');
assert.equal([...root.querySelectorAll('button')].find(b=>b.textContent==='Open circuit in Forge').disabled,true);click('Fork pending design');await tick();assert.equal(db.projects.length,2);assert.notEqual(app.state().project.id,p.id);assert(!win.sessionStorage.getItem('apparition.forge-pro.pending'));
// V2 list details and filters are read-only UI operations over the loaded owned list.
const actionsBeforeDetails=calls.length,search=root.querySelector('[name=search]'),filter=root.querySelector('[name=filter]');search.value='no-such-fixture';search.dispatchEvent(new win.Event('input'));assert(root.querySelector('.forge-pro-project-list').textContent.includes('No matching projects'));search.value='';search.dispatchEvent(new win.Event('input'));filter.value='ARCHIVED';filter.dispatchEvent(new win.Event('change'));assert(root.querySelector('.forge-pro-project-list').textContent.includes('No matching projects'));filter.value='ALL';filter.dispatchEvent(new win.Event('change'));const rowDetails=root.querySelector('.forge-project-details');rowDetails.querySelector('summary').click();assert(rowDetails.open);assert(rowDetails.textContent.includes(db.projects[0].current_revision_id));assert.equal(calls.length,actionsBeforeDetails,'filters/details do not open or save projects');
const originalList=repository.list;repository.list=async()=>{throw Error('Fixture network unavailable');};await app.start();assert(root.textContent.includes('Project access could not be loaded'));assert(status.textContent.includes('Fixture network unavailable'));assert(!root.textContent.includes('No projects yet'));assert(!root.hasAttribute('aria-busy'));repository.list=originalList;await app.start();assert(root.querySelector('.forge-app-shell'));
auth.listener('SIGNED_OUT');assert(!root.textContent.includes('Customer final'));assert(!win.sessionStorage.getItem('apparition.forge-pro.pending'));grants=[];await app.start();assert.match(root.textContent,/No plan can be purchased/);assert(!root.querySelector('form'));auth.getUser=async()=>({data:{user:null}});await app.start();assert(root.querySelector('.forge-app-shell'));assert.match(root.textContent,/Sign in \/ create an account/);assert(!root.querySelector('form'));assert.equal(app.state().projects.length,0);app.destroy();
// Free bridge writes no cloud state and retains the local original.
const bridgeRoot=doc.createElement('div'),circuit=forgeCircuit().circuit;let navigated='';createProjectStore(win.localStorage).save({version:1,name:'Original',electronics:{version:1}},'local-original');const beforeLocal=win.localStorage.getItem('apparition.projects.v1');mountProfessionalBridge(bridgeRoot,{getCircuit:()=>circuit,session:win.sessionStorage,navigate:url=>{navigated=url;}});bridgeRoot.querySelector('button').click();await tick();assert(navigated.includes('/circuit-forge/projects/'));assert(win.sessionStorage.getItem('apparition.forge-pro.import'));assert.equal(win.localStorage.getItem('apparition.projects.v1'),beforeLocal);
let requests=0;const api=createForgeRepository({auth:{getSession:async()=>({data:{session:null}})},request:async()=>{requests++;}});await assert.rejects(api.list(),/Sign in/);assert.equal(requests,0);const requestAPI=createForgeRepository({auth:{getSession:async()=>({data:{session:{access_token:'test-token'}}})},config:{url:'https://fixture.test',publishableKey:'test-public'},request:async(url,options)=>{assert.equal(options.headers.Authorization,'Bearer test-token');assert.equal(options.cache,'no-store');return {ok:false,json:async()=>({code:'40001'})};}});await assert.rejects(requestAPI.command('save',{}),/another session/);
await win.happyDOM.close();console.log('Forge Pro UI: minimal project/metadata/revision, bench data, template, comparison, document, stale pending, signout, capability default, Free transfer and authenticated transport PASS');
