process.on('uncaughtException',e=>{console.error(JSON.stringify({message:e.message,code:e.code,where:e.where}));process.exit(1)});
import assert from 'node:assert/strict';import {readFileSync,readdirSync} from 'node:fs';import {PGlite} from '@electric-sql/pglite';
const db=new PGlite(),admin='10000000-0000-4000-8000-000000000001',customer='10000000-0000-4000-8000-000000000002';await db.exec(`create role anon;create role authenticated;create schema auth;create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth to anon,authenticated;grant execute on function auth.uid() to anon,authenticated;create table public.admin_members(user_id uuid primary key);alter table public.admin_members enable row level security;grant select on public.admin_members to authenticated;create policy own_membership on public.admin_members for select to authenticated using(user_id=auth.uid());insert into auth.users values('${admin}'),('${customer}');insert into public.admin_members values('${admin}');alter default privileges in schema public grant all on tables to anon,authenticated;alter default privileges in schema public grant all on sequences to anon,authenticated;`);
const file=readdirSync('supabase/migrations').find(f=>f.endsWith('_luthier_hub_cms_v2.sql'));try{await db.exec(readFileSync('supabase/migrations/'+file,'utf8'));}catch(e){console.error(JSON.stringify({message:e.message,code:e.code,position:e.position,where:e.where}));process.exit(1);}const rows=async(q,p=[])=>(await db.query(q,p)).rows,as=async(role,user='')=>db.exec(`reset role;set role ${role};select set_config('request.jwt.claim.sub','${user}',false)`),projection=async()=>(await rows('select public.public_hub_articles() as x'))[0].x;
for(const role of ['anon','authenticated']){await as(role,customer);assert.equal((await projection()).length,22);for(const table of ['hub_articles','hub_article_revisions','hub_article_library']){if(role==='anon')await assert.rejects(db.query('select * from public.'+table),e=>e.code==='42501');else assert.deepEqual(await rows('select * from public.'+table),[]);}await assert.rejects(db.query("select public.save_hub_article(null,null,'{}')"),e=>e.code==='42501');}
await as('authenticated',admin);const articles=await rows('select * from public.hub_article_library');assert.equal(articles.length,22);const existing=articles.find(a=>a.guide_key==='values'),initial=await projection(),count=async()=>(await rows('select count(*)::int as n from public.hub_article_revisions'))[0].n;
const save=async(a,c,action='DRAFT',rev=null)=>(await rows('select public.save_hub_article($1::uuid,$2::bigint,$3::jsonb,$4::text,$5::bigint) as x',[a?.id||null,a?.edit_version||null,JSON.stringify(c),action,rev]))[0].x;
const edited=structuredClone(existing.draft);edited.intro+=' Fixture edit.';let a=await save(existing,edited);assert.deepEqual(await projection(),initial,'Private draft cannot change published output');assert.equal(await count(),22);await assert.rejects(save(existing,edited),e=>e.code==='40001');
a=await save(a,edited,'PUBLISH');assert.equal(await count(),23);assert.equal((await projection()).find(r=>r.id===a.id).content.intro,edited.intro);const revisions=await rows('select * from public.hub_article_revisions where article_id=$1 order by revision_number',[a.id]);assert.equal(revisions.at(-1).actor,admin);assert.equal(revisions.at(-1).revision_number,2);
await assert.rejects(db.query('update public.hub_article_revisions set content=$1 where id=$2',[JSON.stringify(edited),revisions[0].id]),e=>e.code==='42501');await db.exec('reset role');await assert.rejects(db.query('delete from public.hub_article_revisions where id=$1',[revisions[0].id]),e=>e.code==='42501');await as('authenticated',admin);
a=await save(a,revisions[0].content,'RESTORE',revisions[0].id);assert.equal(await count(),24);assert.equal((await projection()).find(r=>r.id===a.id).content.intro,existing.draft.intro);assert.equal((await rows('select revision_number from public.hub_article_revisions where id=$1',[a.published_revision_id]))[0].revision_number,3);
const before=await projection(),num=await count();for(const change of [{slug:'categories'},{slug:'another-published-slug'},{primary_intent:'another-family'},{body:{version:1,slots:{main:{type:'doc',content:[{type:'script'}]}}}}])await assert.rejects(save(a,{...a.draft,...change},'PUBLISH'));assert.deepEqual(await projection(),before);assert.equal(await count(),num,'Failed publish cannot create partial revision');
const generic=JSON.parse(readFileSync('dist/hub-cms/presentation/generic.json')),newContent={...generic.baseline,title:'Fixture draft',slug:'fixture-draft',intro:'Fixture only',seo_title:'Fixture draft',meta_description:'Fixture draft description',body:{version:1,slots:{main:{type:'doc',content:[{type:'paragraph',content:[{type:'text',text:'Fixture body.'}]}]}}}};
let draft=await save(null,newContent);assert.equal((await projection()).length,22);assert(!JSON.stringify(await projection()).includes('Fixture draft'));await assert.rejects(save(null,newContent),e=>e.code==='23505');await assert.rejects(save(draft,{...draft.draft,slug:existing.draft.slug}),e=>e.code==='23505');
for(const bad of [{type:'paragraph',attrs:{onclick:'bad()'}},{type:'paragraph',content:[{type:'text',text:'Unsafe',marks:[{type:'link',attrs:{href:'javascript:bad()'}}]}]},{type:'protected',attrs:{ref:'forged'}},{type:'paragraph',content:[{type:'table'}]}])await assert.rejects(save(draft,{...draft.draft,body:{version:1,slots:{main:{type:'doc',content:[bad]}}}},'PUBLISH'));
draft=await save(draft,draft.draft,'PUBLISH');assert.equal((await projection()).length,23);assert((await projection()).find(r=>r.id===draft.id).content.published_at);const publicData=JSON.stringify(await projection());for(const key of ['seed_context','actor','revision_number','edit_version','published_revision_id'])assert(!publicData.includes('"'+key+'"'));await db.exec(`reset role;delete from public.admin_members where user_id='${admin}'`);await as('authenticated',admin);assert.deepEqual(await rows('select * from public.hub_article_library'),[]);await assert.rejects(save(a,a.draft),e=>e.code==='42501');
await db.close();console.log('Isolated CMS migration: 22 published imports, Admin CRUD, anon/non-Admin denial, private drafts/history, immutable snapshots, optimistic concurrency, slug/intent safety, server sanitization, atomic failure, publish/new revision and restore/new revision PASS. No production test records.');
