import assert from 'node:assert/strict';import {readFileSync as read} from 'node:fs';import {Window} from 'happy-dom';import {bootCMS} from '../dist/admin/hub-cms/admin.mjs';import {exportDOCX} from '../dist/admin/hub-cms/docx.mjs';import {libraryRows,articleState,readableDate} from '../dist/admin/hub-cms/library.mjs';import {stable} from '../dist/hub-cms/body.mjs';
const seeds=JSON.parse(read('scripts/hub-cms/seed.json')),w=new Window({url:'https://apparitioninstruments.co.uk/admin/hub-cms/',settings:{disableCSSFileLoading:true,disableJavaScriptFileLoading:true,disableJavaScriptEvaluation:true,disableIframePageLoading:true}}),previous={window:globalThis.window,document:globalThis.document,navigator:globalThis.navigator};for(const [key,value] of Object.entries({window:w,document:w.document,navigator:w.navigator}))Object.defineProperty(globalThis,key,{value,writable:true,configurable:true});
try{w.document.write(read('dist/admin/hub-cms/index.html','utf8'));let articles=seeds.map((s,i)=>({id:s.id,guide_key:s.guide_key,draft:structuredClone(s.content),published_content:structuredClone(s.content),published_revision_id:i+1,edit_version:1,updated_at:'2026-10-05T09:00:00Z',seed_context:{template_key:s.template_key}})),imports=[],saved=[];const repo={list:async()=>articles,history:async()=>[],imports:async()=>imports,save:async()=>{throw Error('This import must not call publish/save RPC');},importDraft:async(a,c)=>{saved.push({id:a.id,content:c});const row={...a,draft:c,edit_version:a.edit_version+1};articles=articles.map(x=>x.id===a.id?row:x);imports.push({content:c,edit_version:row.edit_version,created_at:'2026-10-05T10:00:00Z'});return row;}};const app=await bootCMS({document:w.document,repo,request:async path=>({ok:true,json:async()=>JSON.parse(read('dist'+path))})});
for(const a of articles){await app.select(a);assert.equal(stable(app.content()),stable(a.draft),'Opening article must not reorder/rewrite fields: '+a.guide_key);}const a=articles.find(a=>a.guide_key==='pots');await app.select(a);
assert.equal(articleState(a),'Published');assert.equal(articleState({...a,published_revision_id:null}),'Never published');assert.equal(articleState({...a,draft:{...a.draft,intro:'Changed'}}),'Draft changes pending');assert.equal(readableDate(null),'Date not recorded');assert.equal(readableDate('2026-10-04'),'4 Oct 2026');assert(readableDate('2026-10-05T09:00:00Z').includes('10:00'));assert.equal(libraryRows(articles,{search:a.draft.slug}).length,1);assert(libraryRows(articles,{category:'potentiometers'}).every(a=>a.draft.category==='potentiometers'));assert.equal(libraryRows(articles,{state:'Published'}).length,22);
const query=w.document.querySelector('#cms-search');query.value=a.draft.slug;query.dispatchEvent(new w.Event('input'));assert.equal(w.document.querySelectorAll('#cms-library tr').length,1);query.value='';query.dispatchEvent(new w.Event('input'));
const before=[...app.content().related],search=w.document.querySelector('#cms-related-search');search.value='Ground';search.dispatchEvent(new w.Event('input'));assert.deepEqual(app.content().related,before);const add=w.document.querySelector('[data-cms-choices=related] input:not(:checked)');assert(add);const id=add.value;add.checked=true;add.dispatchEvent(new w.Event('change'));assert.deepEqual(app.content().related,[...before,id]);const remove=[...w.document.querySelectorAll('[data-cms-choices=related] input')].find(n=>n.value===id);remove.checked=false;remove.dispatchEvent(new w.Event('change'));assert.deepEqual(app.content().related,before);
const intent=w.document.querySelector('select[name=primary_intent]');assert(intent.disabled);assert.deepEqual([...intent.options].map(o=>o.value),['','pots']);assert(![...intent.options].some(o=>o.value==='arbitrary'));
let opened;w.open=()=>{opened=new Window({settings:{disableIframePageLoading:true,disableJavaScriptFileLoading:true}});Object.defineProperty(opened,'opener',{value:w,writable:true,configurable:true});return opened;};w.document.querySelector('#cms-preview-button').click();assert(opened);assert.equal(opened.opener,null);assert.equal(opened.document.querySelector('meta[name=robots]').content,'noindex,nofollow');assert(opened.document.querySelector('iframe').srcdoc.includes('noindex,nofollow'));assert.equal(saved.length,0);
const bytes=await exportDOCX(a,app.content()),review=await app.reviewDOCX(bytes);assert.deepEqual(review.errors,[]);assert.equal(saved.length,0);await assert.rejects(app.acceptImport(),/acknowledge/);w.document.querySelector('#cms-import-confirm').checked=true;await app.acceptImport();assert.equal(saved.length,1);assert.equal(articles.find(x=>x.id===a.id).published_revision_id,a.published_revision_id);assert(w.document.querySelector('#cms-import-history').textContent.includes('DOCX import'));assert(w.document.querySelector('#cms-status').textContent.includes('published revision is unchanged'));assert(w.document.querySelector('.cms-toolbar [aria-label="Text"]'));assert(w.document.querySelector('.cms-toolbar [aria-label="History"]'));await opened.happyDOM.close();console.log('CMS UX PASS: 22 no-op editor opens preserve all fields/relationship ordering; search/category/state/date controls; related add/remove; controlled intent; explicit private separate-window preview; DOCX review/acknowledgement/import draft only with provenance; grouped toolbar.');
}finally{await w.happyDOM.close();for(const [key,value] of Object.entries(previous))Object.defineProperty(globalThis,key,{value,writable:true,configurable:true});}
