import assert from 'node:assert/strict';
import {createReference,normaliseInstrument,validateInstrument,pickupLayouts,controlLayouts,selectorSelections,instrumentCapabilities,generatorConfiguration,publicInstrument,instrumentFromLegacy} from '../dist/electronics/instrument/configuration.mjs';
import {makeInstrumentCircuit,instrumentCircuitState} from '../dist/electronics/instrument/circuit.mjs';
import {captureCircuitState,normaliseCircuitState,readCircuitState,circuitStateURL,wiringHandoff,designerHandoff,kitHandoff} from '../dist/electronics/state/circuit-state.mjs';
import {forgeResponse} from '../dist/circuit-forge/response.mjs';
import {forgeCircuit} from '../dist/circuit-forge/model.mjs';
import {createProjectStore,projectFromCircuit,projectURL,shareProjectURL,readProject} from '../dist/electronics/state/project.mjs';
const ids=['les-paul','tele','strat','hss','prs-hh'];
for(const id of ids){const i=createReference(id);assert.deepEqual(createReference(id),i);assert.deepEqual(normaliseInstrument(JSON.parse(JSON.stringify(i))),i);const c=makeInstrumentCircuit(i),state=captureCircuitState(c);assert.deepEqual(normaliseCircuitState(state),state);assert.deepEqual(readCircuitState(new URL(circuitStateURL('/circuit-forge/',state),'https://test').search).state,state);const caps=instrumentCapabilities(i);assert.equal(caps.canGenerateWiring,['les-paul','tele','strat','hss','prs-hh'].includes(id));assert.equal(forgeResponse(c).supported,['les-paul','tele','strat','hss','prs-hh'].includes(id));assert.equal(Boolean(wiringHandoff(c)),caps.canGenerateWiring);assert.equal(Boolean(designerHandoff(c).url),caps.canOpenTrebleBleedDesigner);assert.equal(Boolean(kitHandoff(c).url),id==='les-paul');i.label='Private guitar';i.extensions={future:{notes:'private'}};const named=makeInstrumentCircuit(i),p=projectFromCircuit(named,{name:'Private project',extensions:{notes:'secret'}}),map=new Map(),store=createProjectStore({getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,v),removeItem:k=>map.delete(k)}),key=store.save(p);assert.deepEqual(store.restore(key),p);const shared=shareProjectURL(p);assert(!decodeURIComponent(shared).includes('Private'));assert(!decodeURIComponent(shared).includes('secret'));assert(!decodeURIComponent(shared).includes('private'));assert.equal(readProject(new URL(shared,'https://test').search).project.electronics.instrument.reference,id);}
for(const [layout,types] of Object.entries(pickupLayouts)){let i=createReference('tele');i.reference=undefined;i.layout=layout;i.pickups=Object.entries(types).map(([position,type])=>({position,type,assumption:type==='single'?'single':'generic',modification:'full'}));for(const c of i.controls)c.assignments=Object.keys(types);assert(validateInstrument(i).valid);assert.equal(normaliseInstrument(i).pickups.length,Object.keys(types).length);}
for(const [layout,[v,t]] of Object.entries(controlLayouts)){let i=createReference('tele');delete i.reference;i.controlLayout=layout;i.controls=[];for(let n=0;n<v;n++)i.controls.push({id:'volume'+n,role:'volume',assignments:['neck','bridge'],pot:250,position:7,bleed:'none'});for(let n=0;n<t;n++)i.controls.push({id:'tone'+n,role:'tone',assignments:['neck','bridge'],pot:250,position:10,capacitor:'0.047',capacitorGroup:'cap'+n});assert(validateInstrument(i).valid);assert.equal(instrumentCapabilities(i).canGenerateWiring,false);}
for(const change of [i=>i.version=2,i=>i.pickups.pop(),i=>i.pickups[1].position='neck',i=>i.pickups[0].type='active',i=>i.controls.pop(),i=>i.controls[0].assignments=['middle'],i=>i.selector.family='super-switch',i=>i.selector.selection=9,i=>i.load.cableC=999,i=>i.extensions=JSON.parse('{"__proto__":{}}')]){const i=createReference();change(i);assert.equal(validateInstrument(i).valid,false);}
const lp=createReference();lp.selector.selection=2;assert.match(forgeResponse(makeInstrumentCircuit(lp)).reason,/coupled/);lp.selector.family='3-way-blade';assert.equal(instrumentCapabilities(lp).canGenerateWiring,false);lp.selector.family='3-way-toggle';lp.pickups[0].modification='partial-split';assert.equal(instrumentCapabilities(lp).canAnalyseResponse,false);
const strat=createReference('strat');strat.selector.selection=1;assert.equal(instrumentCapabilities(strat).canAnalyseResponse,false,'No substitute tone circuit for bridge without tone');strat.selector.selection=3;assert.equal(instrumentCapabilities(strat).canAnalyseResponse,false,'Middle is deliberately outside existing response segment');strat.selector.selection=2;assert.match(forgeResponse(makeInstrumentCircuit(strat)).reason,/coupled/);
for(const wiring of ['modern','50s','60s']){const c=forgeCircuit({position:'neck',wiring}).circuit,legacy=captureCircuitState(c);assert.equal(legacy.version,1);assert.deepEqual(normaliseCircuitState(legacy),legacy);assert.equal(instrumentFromLegacy(legacy).wiring,wiring);}
const c=forgeCircuit({position:'neck',bleed:'duncan'}).circuit,old=forgeResponse(c),i=instrumentFromLegacy(captureCircuitState(c)),next=forgeResponse(makeInstrumentCircuit(i));assert.deepEqual(next.state,old.state);assert.deepEqual(next.points,old.points,'Legacy equations unchanged');
const tele=createReference('tele');tele.controls.find(c=>c.role==='volume').pot=300;tele.controls.find(c=>c.role==='tone').pot=1000;tele.controls.find(c=>c.role==='tone').capacitor='0.015';const response=forgeResponse(makeInstrumentCircuit(tele));assert.equal(response.state.volumePot,300);assert.equal(response.state.tonePot,1000);assert.equal(response.state.toneCap,15);assert.equal(response.state.pickupL,2.2);
console.log('Instrument V2.5 schema, references, capabilities, state, projects, privacy, legacy equivalence and truthful limits: PASS');
// Legacy illustrative source choices do not rewrite the physical HH architecture.
const legacySingle=forgeCircuit({position:'neck'}).circuit;legacySingle.state.responseAssumptions.channels.neck.pickup='single';const migratedSingle=instrumentFromLegacy(captureCircuitState(legacySingle));assert.equal(migratedSingle.layout,'HH');assert.equal(migratedSingle.pickups[0].assumption,'single');assert.deepEqual(forgeResponse(makeInstrumentCircuit(migratedSingle)).state,forgeResponse(legacySingle).state);
const {reconcileKitProject}=await import('../dist/knowledge/kit-project.mjs');const {normaliseKit}=await import('../dist/les-paul-kits/config.mjs');const lpProject=projectFromCircuit(makeInstrumentCircuit(createReference('les-paul')));const reconciled=reconcileKitProject(lpProject,normaliseKit({}));assert.equal(reconciled.electronics.instrument.reference,'les-paul');assert(reconciled.electronics.instrument.controls.every(c=>c.pot===500));assert.throws(()=>reconcileKitProject(projectFromCircuit(makeInstrumentCircuit(createReference('tele'))),normaliseKit({})),/No matching Kit Definition/);console.log('Instrument Kit Definition reconciliation and unsupported-kit boundary: PASS');
