import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {spawnSync} from 'node:child_process';
import {Window} from 'happy-dom';
import {createReference} from '../dist/electronics/instrument/configuration.mjs';
import {makeInstrumentCircuit} from '../dist/electronics/instrument/circuit.mjs';
import {projectFromCircuit,projectURL,readProject,projectStorageKey,shareProjectURL} from '../dist/electronics/state/project.mjs';
import {wiringHandoff,designerHandoff} from '../dist/electronics/state/circuit-state.mjs';
const mode=process.argv[2];if(!mode){for(const scenario of ['les-paul','tele','strat','hss','prs-hh','generator-tele','generator-strat','designer-tele','mobile-320','mobile-390','mobile-768','desktop-1400','hub']){const r=spawnSync(process.execPath,[new URL(import.meta.url).pathname,scenario],{encoding:'utf8',timeout:45000});assert.equal(r.status,0,scenario+'\n'+r.stdout+'\n'+r.stderr);console.log(r.stdout.trim());}process.exit(0);}
if(mode==='hub'){const win=new Window({url:'https://fixture.test/luthier-hub/selectors/',settings:{disableCSSFileLoading:true,disableJavaScriptFileLoading:true,disableJavaScriptEvaluation:true}});globalThis.document=win.document;globalThis.fetch=async()=>{throw Error('Network forbidden');};document.write(readFileSync('dist/luthier-hub/selectors/index.html','utf8'));await import('../dist/luthier-hub/instrument-context.mjs');const links=[...document.querySelectorAll('[data-instrument-references] a')];assert.equal(links.length,3);assert.deepEqual(links.map(a=>readProject(new URL(a.href).search).project.electronics.instrument.reference),['les-paul','tele','strat']);await win.happyDOM.close();console.log('Instrument Hub contextual references: PASS');process.exit(0);}
const id=mode.includes('tele')?'tele':mode.includes('strat')?'strat':['les-paul','hss','prs-hh'].includes(mode)?mode:'les-paul',instrument=createReference(id);instrument.label='Private instrument';instrument.controls.find(c=>c.role==='volume').pot=300;
const c=makeInstrumentCircuit(instrument),p=projectFromCircuit(c,{name:'Private project',extensions:{notes:'secret'}}),session=new Map();globalThis.sessionStorage={getItem:k=>session.get(k)??null,setItem:(k,v)=>session.set(k,v)};
const tool=mode.startsWith('generator')?'wiring-generator':mode.startsWith('designer')?'treble-bleed-designer':'circuit-forge',url=projectURL(tool==='wiring-generator'?wiringHandoff(c):tool==='treble-bleed-designer'?designerHandoff(c).url:'/circuit-forge/?mode=signal',p);
const win=new Window({url:'https://fixture.test'+url,settings:{disableCSSFileLoading:true,disableJavaScriptFileLoading:true,disableJavaScriptEvaluation:true}});const width=Number(mode.split('-').at(-1))||1400;win.happyDOM.setWindowSize({width,height:900});for(const key of ['window','document','localStorage','location','history','navigator','CSS','Event','MouseEvent','Node','HTMLElement','CustomEvent'])Object.defineProperty(globalThis,key,{value:key==='window'?win:win[key],configurable:true,writable:true});globalThis.matchMedia=win.matchMedia.bind(win);globalThis.fetch=async()=>{throw Error('No network allowed');};document.write(readFileSync('dist/'+tool+'/index.html','utf8'));const $=s=>document.querySelector(s);await import('../dist/'+tool+'/app.mjs?instrument='+mode);await new Promise(r=>setTimeout(r,10));
if(tool==='circuit-forge'){
 assert.equal($('#forge-reference').value,id);assert.equal($('#forge-instrument-label').value,'Private instrument');assert.equal($('#forge-instrument').open,false);assert.equal($('#forge-response-lab').hidden,false);assert.match($('#forge-instrument-summary').textContent,new RegExp(instrument.layout));assert.equal($('#forge-controls').elements.position.value,id==='les-paul'?'neck':String(instrument.selector.selection));assert.equal($('#forge-view-wiring').hidden,['hss','prs-hh'].includes(id));assert.equal(!!$('#forge-diagram svg'),!['hss','prs-hh'].includes(id));assert.equal($('#forge-design-bleed').hidden,['hss','prs-hh'].includes(id));
 const current=readProject(window.location.search).project;assert.equal(current.electronics.instrument.label,'Private instrument');assert.equal(current.electronics.instrument.controls.find(c=>c.role==='volume').pot,300);assert(!decodeURIComponent(shareProjectURL(current)).includes('Private'));
 const saved=$('.local-projects');saved.querySelector('input').value='Saved fixture';[...saved.querySelectorAll('button')].find(b=>b.textContent==='Save current').click();await new Promise(r=>setTimeout(r,0));assert.equal(JSON.parse(localStorage.getItem(projectStorageKey)).entries[0].project.electronics.instrument.reference,id);
 $('[data-forge-mode="physical"]').click();assert.equal(readProject(location.search).project.electronics.instrument.reference,id);$('[data-forge-mode="signal"]').click();
 $('#forge-reference-reset').click();assert.equal(readProject(location.search).project.electronics.instrument.controls.find(c=>c.role==='volume').pot,createReference(id).controls.find(c=>c.role==='volume').pot);
 $('#forge-reference').value='hss';$('#forge-reference').dispatchEvent(new Event('change',{bubbles:true}));assert.equal(readProject(location.search).project.electronics.instrument.reference,'hss');assert.equal($('#forge-view-wiring').hidden,true);assert.match($('#forge-response-summary').textContent,/not yet modelled/);
 $('#forge-reference').value='tele';$('#forge-reference').dispatchEvent(new Event('change',{bubbles:true}));assert.equal($('#forge-view-wiring').hidden,false);assert.equal($('#forge-controls').elements.position.value,'3');assert.equal(readProject(location.search).project.electronics.instrument.pickups[0].assumption,'single');
 const valueInput=$('#forge-response-volume');valueInput.value='4';valueInput.dispatchEvent(new Event('input',{bubbles:true}));const latest=readProject(new URL($('#forge-view-wiring').href).search).project;assert.equal(latest.electronics.instrument.controls.find(c=>c.role==='volume').position,4);
 const css=readFileSync('dist/circuit-forge/forge.css','utf8');assert.match(css,/forge-instrument select.*min-width:0/);assert.match(css,/min-height:44px/);assert($('#forge-reference').closest('label'));assert($('#forge-instrument-label').closest('label'));
}else if(tool==='wiring-generator'){
 assert($('#generator-mount svg'));assert.equal($('#generator-form').elements.guitar.value,id);assert.equal($('#generator-form').elements.position.value,String(instrument.selector.selection));const returned=readProject(new URL($('#generator-source-circuit').href).search).project;assert.equal(returned.electronics.instrument.reference,id);assert.equal(returned.electronics.instrument.label,'Private instrument');assert.equal(returned.electronics.instrument.controls.find(c=>c.role==='volume').pot,300);assert.equal(returned.extensions.notes,'secret');const pos=$('#generator-form').elements.position;pos.value='1';pos.dispatchEvent(new Event('change',{bubbles:true}));const changed=readProject(new URL($('#generator-source-circuit').href).search).project;assert.equal(changed.electronics.instrument.selector.selection,1);
}else{assert.equal(readProject(new URL($('#designer-source-circuit').href).search).project.electronics.instrument.reference,'tele');assert.equal(readProject(new URL($('#designer-source-circuit').href).search).project.electronics.instrument.label,'Private instrument');}
await win.happyDOM.close();console.log('Instrument DOM '+mode+': PASS');process.exit(0);
