import assert from 'node:assert/strict';
import {readFileSync,existsSync} from 'node:fs';
import {Window} from 'happy-dom';
import {mountHubSearch,mountHubSignal} from '../dist/luthier-hub/hub.mjs';
import {readCircuitState} from '../dist/electronics/state/circuit-state.mjs';
const html=readFileSync('dist/luthier-hub/index.html','utf8'),css=readFileSync('dist/luthier-hub/hub-v4.css','utf8');
function fixture(reduced=false){const win=new Window({url:'https://fixture.test/luthier-hub/',settings:{disableCSSFileLoading:true,disableJavaScriptFileLoading:true,disableJavaScriptEvaluation:true}});win.fetch=()=>{throw Error('Network forbidden');};win.document.write(html);const media={matches:reduced,addEventListener:(type,fn)=>media.change=fn};win.matchMedia=()=>media;return {win,doc:win.document,media};}
const {win,doc,media}=fixture();
assert.equal(doc.querySelectorAll('main').length,1);assert.equal(doc.querySelectorAll('h1').length,1);assert.match(doc.querySelector('h1').textContent,/Understand.*your guitar.*Build with.*confidence/s);assert.equal(doc.querySelectorAll('script[src$="hub.mjs"]').length,1);assert.equal(doc.querySelectorAll('.hub-intent').length,5);assert.equal(doc.querySelectorAll('.hub-learning-path').length,3);assert.equal(doc.querySelectorAll('[data-signal-panel]').length,5);assert([...doc.querySelectorAll('[data-signal-panel]')].every(p=>!p.hidden),'No-JS content complete');assert.equal(doc.querySelectorAll('[data-search]').length,16);assert.match(doc.querySelector('#follow-signal').textContent,/tone circuit is a branch.*educational map, not an electrical simulation/s);
const ids=[...doc.querySelectorAll('[id]')].map(n=>n.id);assert.equal(new Set(ids).size,ids.length,'Unique anchors');
for(const a of doc.querySelectorAll('main a[href]')){const u=new URL(a.href);assert.equal(u.origin,'https://fixture.test');assert(existsSync('dist'+u.pathname+'index.html')||existsSync('dist'+u.pathname),'Missing route '+u.pathname);if(u.hash&&u.pathname==='/luthier-hub/')assert(doc.getElementById(u.hash.slice(1)),'Missing anchor '+u.hash);if(u.searchParams.has('sf')){const source=readCircuitState(u.search);assert(source.state);assert.equal(source.state.configuration.position,'neck');}}
assert(!/passport|QR identities|create an account|all circuits.*response/i.test(doc.querySelector('main').textContent));assert.match(doc.querySelector('#intent-kit').textContent,/Les Paul Kit Builder.*optional split circuits do not imply a matching kit/s);
mountHubSearch(doc);for(const term of ['500k','0.022','treble bleed','hum','ground','pickup colours','selector']){const input=doc.querySelector('#hub-search');input.value=term;input.dispatchEvent(new win.Event('input'));assert([...doc.querySelectorAll('[data-search]')].some(n=>!n.hidden),term);}doc.querySelector('#hub-topic').value='pots';doc.querySelector('#hub-search').value='';doc.querySelector('#hub-topic').dispatchEvent(new win.Event('change'));assert.equal([...doc.querySelectorAll('[data-search]')].filter(n=>!n.hidden).length,3);doc.querySelector('#hub-search').value='no-result-fixture';doc.querySelector('#hub-search').dispatchEvent(new win.Event('input'));assert.equal(doc.querySelector('#hub-empty').hidden,false);
mountHubSignal(doc);const links=[...doc.querySelectorAll('[data-signal-step]')];for(const link of links){link.focus();assert.equal(link.getAttribute('aria-current'),'step');assert.equal(doc.querySelectorAll('[data-signal-panel]:not([hidden])').length,1);assert.equal(doc.querySelector('[data-signal-panel]:not([hidden])').dataset.signalPanel,link.dataset.signalStep);assert.equal(doc.querySelector('[data-signal-stage][data-active=true]').dataset.signalStage,link.dataset.signalStep);link.dispatchEvent(new win.Event('pointerenter'));link.click();assert.equal(win.location.hash,'','Enhanced interaction does not jump the page');}
media.matches=true;media.change();assert([...doc.querySelectorAll('[data-signal-panel]')].every(p=>!p.hidden),'Dynamic reduced motion restores complete static content');assert(!doc.querySelector('.hub-signal-panels').classList.contains('is-enhanced'));
for(const width of [320,390,768,1024,1400,1920]){win.happyDOM.setWindowSize({width,height:900});assert(doc.querySelector('meta[name=viewport]'));assert(doc.querySelectorAll('.hub-intent>summary').length===5);assert(doc.querySelector('label[for=hub-search]'));assert(doc.querySelector('label[for=hub-topic]'));assert(css.includes('minmax(0,1fr)'));assert(css.includes('width:calc(100% - 32px)'));assert(css.includes('min-height:44px'));assert(css.includes('overflow-wrap:anywhere'));}
for(const rule of ['@media(max-width:1024px)','@media(max-width:768px)','@media(max-width:390px)','prefers-reduced-motion','focus-visible','[hidden]','counter(hub-step,decimal-leading-zero)'])assert(css.includes(rule));
const source=readFileSync('dist/luthier-hub/hub.mjs','utf8');assert(!/fetch\(|requestAnimationFrame|setInterval|localStorage|supabase|IntersectionObserver/.test(source));assert(!/@import|url\(/.test(css));assert(!/video|canvas/i.test(doc.querySelector('main').innerHTML));
await win.happyDOM.close();const reduced=fixture(true);mountHubSignal(reduced.doc);assert([...reduced.doc.querySelectorAll('[data-signal-panel]')].every(p=>!p.hidden));await reduced.win.happyDOM.close();console.log('Luthier Hub V4: all 16 guides preserved, routes/anchors and single-pickup tool context valid, five intents, five-stage pointer/focus/touch parity, no-JS and reduced-motion complete, search, semantic structure and six responsive CSS/DOM contracts PASS; no network/storage/dependencies');
