// Current Hub contract; supersedes the former V4 landing composition checks.
import assert from 'node:assert/strict';
import {readFileSync,existsSync,mkdtempSync,mkdirSync,writeFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {spawnSync} from 'node:child_process';
import {Window} from 'happy-dom';
import {guides,categories,tools,components,legacyCategories} from '../scripts/luthier-hub/content.mjs';
import {mountHubSearch} from '../dist/luthier-hub/hub.mjs';
const legacy=JSON.parse(readFileSync('scripts/luthier-hub/legacy.json','utf8'));
const library=[...guides,...legacy.map(a=>({...a,category:legacyCategories[a.id]}))];
const paths=['/luthier-hub/',...categories.map(c=>`/luthier-hub/categories/${c.id}/`),...library.map(a=>`/luthier-hub/${a.slug}/`)];
const css=readFileSync('dist/luthier-hub/reference.css','utf8');
const docs=new Map(),titles=new Set(),canonicals=new Set();
const winOptions={settings:{disableCSSFileLoading:true,disableJavaScriptFileLoading:true,disableJavaScriptEvaluation:true}};
for(const path of paths){const win=new Window({url:'https://apparitioninstruments.co.uk'+path,...winOptions});win.fetch=()=>{throw Error('Network forbidden');};const html=readFileSync('dist'+path+'index.html','utf8');win.document.write(html);const doc=win.document;docs.set(path,{win,doc,html});
 assert.equal(doc.querySelectorAll('main').length,1,path+' main');assert.equal(doc.querySelectorAll('h1').length,1,path+' h1');assert.equal(doc.querySelectorAll('.site-header').length,1);assert.equal(doc.querySelectorAll('#mobile-nav').length,1);assert.equal(doc.querySelectorAll('footer').length,1);assert(doc.querySelector('.skip[href="#main"]'));assert(doc.querySelector('script[src="/site.mjs"]'));assert.equal(doc.querySelectorAll('script[src="/site.mjs"]').length,1);
 const ids=[...doc.querySelectorAll('[id]')].map(n=>n.id);assert.equal(new Set(ids).size,ids.length,path+' unique IDs');
 const canonical=doc.querySelector('link[rel=canonical]').href;assert.equal(canonical,'https://apparitioninstruments.co.uk'+path);assert(!canonicals.has(canonical));canonicals.add(canonical);assert(!titles.has(doc.title));titles.add(doc.title);assert(doc.querySelector('meta[name=description]').content.length>=30);assert.equal(doc.querySelector('meta[property="og:url"]').content,canonical);assert(doc.querySelector('meta[name=viewport]'));
 const graph=JSON.parse(doc.querySelector('script[type="application/ld+json"]').textContent)['@graph'];const breadcrumb=graph.find(x=>x['@type']==='BreadcrumbList');assert(breadcrumb);assert.equal(breadcrumb.itemListElement.at(-1).item,canonical);
 const article=library.find(a=>path===`/luthier-hub/${a.slug}/`);if(article){const schema=graph.find(x=>x['@type']==='Article');assert(schema,path+' Article');assert.equal(schema.headline,article.title);assert.equal(schema.articleSection,categories.find(c=>c.id===article.category).title);assert(doc.querySelector('[data-hub-article]'));assert(doc.querySelector('nav[aria-label="Table of contents"]'));assert(doc.querySelector('#next-steps'));assert(doc.querySelector('.hub-article-body').textContent.trim().length>300);if(guides.includes(article)){assert(doc.querySelector('.hub-article-body').textContent.trim().split(/\s+/).length>=450,path+' cornerstone depth');assert(!doc.querySelector('script[src$="articles.mjs"]'),'New guides static without article client');assert.equal(doc.querySelectorAll('.hub-article-body>section[id]').length,article.sections.length+1);assert(schema.datePublished||schema.dateModified);}}
 for(const table of doc.querySelectorAll('main table')){if(guides.includes(article)){assert(table.querySelector('caption'));assert(table.querySelector('th[scope]'));assert(table.closest('[tabindex="0"]'));}}
}
for(const [path,{doc}] of docs){for(const a of doc.querySelectorAll('main a[href]')){const url=new URL(a.href);if(url.origin!=='https://apparitioninstruments.co.uk'){assert(url.protocol==='https:');continue;}const file='dist'+url.pathname+(url.pathname.endsWith('/')?'index.html':'');assert(existsSync(file),'Missing route '+a.href+' on '+path);if(url.hash){const target=docs.get(url.pathname)?.doc; if(target)assert(target.getElementById(decodeURIComponent(url.hash.slice(1))),'Missing anchor '+a.href+' on '+path);}}}
assert.equal(categories.length,6);assert.equal(guides.length,7);assert.equal(library.length,16);assert.equal(new Set(library.map(a=>a.id)).size,16);for(const a of guides){assert(categories.some(c=>c.id===a.category));assert(a.related.length>=2);for(const id of a.related)assert(library.some(x=>x.id===id)&&id!==a.id);for(const tool of a.tools)assert(tools[tool]);assert(components[a.component]);const category=docs.get(`/luthier-hub/categories/${a.category}/`).doc;assert(category.querySelector(`a[href="/luthier-hub/${a.slug}/"]`));}
const landing=docs.get('/luthier-hub/');assert.equal(landing.doc.querySelectorAll('.hub-subjects li').length,6);assert.equal(landing.doc.querySelectorAll('#cornerstones li').length,7);assert.equal(landing.doc.querySelectorAll('#hub-results [data-search]').length,16);assert.equal(landing.doc.querySelectorAll('script[src$="hub.mjs"]').length,1);
mountHubSearch(landing.doc);const input=landing.doc.querySelector('#hub-search'),select=landing.doc.querySelector('#hub-topic');for(const term of ['500k','0.022','treble bleed','ground','pickup']){input.value=term;input.dispatchEvent(new landing.win.Event('input'));assert([...landing.doc.querySelectorAll('#hub-results [data-search]')].some(n=>!n.hidden),term);}input.value='';select.value='potentiometers';select.dispatchEvent(new landing.win.Event('change'));assert.equal([...landing.doc.querySelectorAll('#hub-results [data-search]')].filter(n=>!n.hidden).length,3);input.value='zz-no-result';input.dispatchEvent(new landing.win.Event('input'));assert.equal(landing.doc.querySelector('#hub-empty').hidden,false);
for(const token of ['@media(max-width:1024px)','@media(max-width:768px)','@media(max-width:390px)','minmax(0,1fr)','width:calc(100% - 32px)','focus-visible','min-height:48px','prefers-reduced-motion','overflow-x:auto','overflow-wrap:anywhere'])assert(css.includes(token),token);
for(const id of ['pots','lugs']){const doc=docs.get('/luthier-hub/'+guides.find(g=>g.id===id).slug+'/').doc;const text=doc.querySelector('main').textContent;assert(text.includes('pickup/selector → volume lug 3 → wiper/lug 2 → output jack TIP'));assert(text.includes('sleeve'));assert(text.includes('Lug 1')&&text.includes('Ground'));}
const sitemap=readFileSync('dist/sitemap.xml','utf8');for(const path of paths)assert(sitemap.includes('<loc>https://apparitioninstruments.co.uk'+path+'</loc>'));
// SEO refresh must retain generator-owned Article/Breadcrumb schema, and discover new routes.
const temp=mkdtempSync(join(tmpdir(),'hub-seo-'));try{for(const [path,{html}] of docs){const folder=join(temp,path.slice(1));mkdirSync(folder,{recursive:true});writeFileSync(join(folder,'index.html'),html);}const program=`import importlib.util, pathlib\nspec=importlib.util.spec_from_file_location('seo','scripts/generate-seo.py')\nseo=importlib.util.module_from_spec(spec);spec.loader.exec_module(seo)\nseo.ROOT=pathlib.Path(${JSON.stringify(temp)})\nseo.main()\n`;const result=spawnSync('python',['-c',program],{encoding:'utf8'});assert.equal(result.status,0,result.stderr);for(const [path,{html}] of docs)assert.equal(readFileSync(join(temp,path.slice(1),'index.html'),'utf8'),html,'SEO preserves Hub metadata '+path);const generated=readFileSync(join(temp,'sitemap.xml'),'utf8');for(const path of paths)assert(generated.includes('https://apparitioninstruments.co.uk'+path));}finally{rmSync(temp,{recursive:true,force:true});}
for(const {win} of docs.values())await win.happyDOM.close();
console.log('Luthier Hub V1 PASS: 23 routes, 16 shared articles, seven substantial cornerstones, six categories, relations, links/anchors, no-JS reading, search, shell/semantic/responsive contracts, Article/Breadcrumb metadata and shared SEO sitemap preservation.');
