import assert from 'node:assert/strict';
import {createMigrationDatabase} from './fixtures/migration-database.mjs';
const {db,migrations}=await createMigrationDatabase(),rows=async(s,p=[])=>(await db.query(s,p)).rows;
const admin='10000000-0000-4000-8000-000000000001',customer='10000000-0000-4000-8000-000000000002';
await db.exec(`insert into auth.users values('${admin}'),('${customer}');insert into public.admin_members(user_id) values('${admin}');`);
const as=async(role,user='')=>db.exec(`reset role;set role ${role};select set_config('request.jwt.claim.sub','${user}',false);`),state=async()=>(await rows('select public.get_site_operations() as x'))[0].x;
await as('anon');const initial=await state();assert.equal(initial.store.state,'OPEN');assert(!JSON.stringify(initial).includes('internal_reason'));assert(!JSON.stringify(initial).includes('updated_by'));assert.deepEqual(await rows('select * from public.public_news()'),[]);
for(const table of ['site_operations','news_posts','site_operations_audit'])await assert.rejects(db.query('select * from public.'+table),e=>e.code==='42501');
for(const role of ['anon','authenticated']){await as(role,customer);for(const name of ['set_store_operations','save_news_post'])await assert.rejects(db.query(`select public.${name}('{}')`),e=>e.code==='42501');await assert.rejects(db.query('select public.assert_store_accepting_orders()'),e=>e.code==='42501');await assert.rejects(db.query("select public.create_guest_kit_order('{}')"),e=>e.code==='42501');}
await as('authenticated',customer);for(const table of ['site_operations','news_posts','site_operations_audit'])assert.equal((await rows('select * from public.'+table)).length,0);await db.exec(`select set_config('request.jwt.claims','{"user_metadata":{"role":"admin"}}',false)`);await assert.rejects(db.query("select public.set_store_operations('{}')"),e=>e.code==='42501');
await as('authenticated',admin);await assert.rejects(db.query("update public.site_operations set desired_state='OPEN'"),e=>e.code==='42501');
const mutate=async(change)=>(await rows('select public.set_store_operations($1::jsonb) as x',[JSON.stringify({expected_updated_at:(await state()).store.updated_at,...change})]))[0].x;
const future=new Date(Date.now()+86400000).toISOString(),end=new Date(Date.now()+172800000).toISOString();
await mutate({desired_state:'ORDERS_PAUSED',mode:'schedule',pause_from:future,resume_at:end,customer_title:'Workshop break',customer_message:'Save your basket.',internal_reason:'PRIVATE'});assert.equal((await state()).store.state,'OPEN');
await assert.rejects(mutate({desired_state:'ORDERS_PAUSED',mode:'schedule',pause_from:new Date(0).toISOString()}),/future/);
await mutate({desired_state:'ORDERS_PAUSED',mode:'now',resume_at:end});assert.equal((await state()).store.state,'ORDERS_PAUSED');await assert.rejects(db.query('select public.set_store_operations($1::jsonb)',[JSON.stringify({expected_updated_at:initial.store.updated_at,desired_state:'OPEN'})]),e=>e.code==='40001');
await as('service_role');const businessBefore=(await rows(`select jsonb_build_object('orders',(select jsonb_agg(o) from public.orders o),'inventory',(select jsonb_agg(i) from public.inventory i),'emails',(select jsonb_agg(e) from public.order_email_deliveries e)) as x`))[0].x;
await assert.rejects(db.query('select public.assert_store_accepting_orders()'),/temporarily paused/);await assert.rejects(db.query("select public.create_guest_kit_order('{}')"),/temporarily paused/,'Guard precedes all checkout initiation validations');
assert.deepEqual((await rows(`select jsonb_build_object('orders',(select jsonb_agg(o) from public.orders o),'inventory',(select jsonb_agg(i) from public.inventory i),'emails',(select jsonb_agg(e) from public.order_email_deliveries e)) as x`))[0].x,businessBefore);
await as('authenticated',admin);await mutate({desired_state:'OPEN'});await as('service_role');assert.equal((await rows('select public.assert_store_accepting_orders() as x'))[0].x.store.state,'OPEN');await assert.rejects(db.query("select public.create_guest_kit_order('{}')"),e=>!e.message.includes('temporarily paused'),'Open path resumes existing validation');
// Evaluate scheduled boundaries with isolated rows; no sleeps or external cron.
await db.exec('reset role');for(const [start,finish,expected] of [[86400000,172800000,'OPEN'],[-86400000,86400000,'ORDERS_PAUSED'],[-172800000,-86400000,'OPEN'],[-86400000,null,'ORDERS_PAUSED']]){await db.query("update public.site_operations set desired_state='ORDERS_PAUSED',pause_from=clock_timestamp()+$1*interval '1 millisecond',resume_at=case when $2::bigint is null then null else clock_timestamp()+$2*interval '1 millisecond' end",[start,finish]);assert.equal((await state()).store.state,expected);}
await as('authenticated',admin);await mutate({desired_state:'OPEN'});
const post={slug:'first-update',title:'First update',excerpt:'A useful update.',body:'# News\n\nRead **this**.',category:'NEWS',status:'DRAFT',publication_at:null,expires_at:null,announcement:true,priority:10,dismissible:true,cta_label:'Browse',cta_url:'/components/'};
const save=async(p)=>(await rows('select public.save_news_post($1::jsonb) as x',[JSON.stringify(p)]))[0].x;
let p=await save(post);assert.equal(p.created_by,admin);assert.equal((await rows('select * from public.public_news()')).length,0);p=await save({...p,expected_updated_at:p.updated_at,status:'SCHEDULED',publication_at:future,expires_at:end});assert.equal((await rows('select * from public.public_news()')).length,0);
p=await save({...p,expected_updated_at:p.updated_at,status:'PUBLISHED'});assert(Date.parse(p.publication_at)<=Date.now(),'Publish now does not retain a future schedule');let pub=await rows('select * from public.public_news()');assert.equal(pub.length,1);assert(!JSON.stringify(pub).includes('created_by'));assert(!JSON.stringify(pub).includes('status'));
await assert.rejects(save({...p,expected_updated_at:p.updated_at,slug:'new-route'}),/immutable/);await assert.rejects(save({...p,expected_updated_at:initial.store.updated_at}),e=>e.code==='40001');
await assert.rejects(save({...post,slug:'unsafe-link',status:'PUBLISHED',cta_url:'javascript:alert(1)'}),e=>e.code==='23514');await assert.rejects(save({...post,slug:'unsafe-link',status:'PUBLISHED',cta_url:'https://user@example.org/'}),e=>e.code==='23514');await assert.rejects(save({...post,slug:'unsafe-link',status:'PUBLISHED',cta_url:'/\\evil.example'}),e=>e.code==='23514');
await db.exec('reset role');await db.query("update public.news_posts set publication_at=clock_timestamp()-interval '2 days',expires_at=clock_timestamp()-interval '1 day' where id=$1",[p.id]);assert.equal((await rows('select * from public.public_news()')).length,1,'Expired News stays archive');p=(await rows('select * from public.news_posts where id=$1',[p.id]))[0];await as('authenticated',admin);p=await save({...p,expected_updated_at:p.updated_at,status:'ARCHIVED'});assert.equal((await rows('select * from public.public_news()')).length,0);
const audit=await rows('select * from public.site_operations_audit order by id');assert(audit.length>=8);for(const a of audit){assert.equal(a.actor,admin);assert(a.created_at&&a.action&&a.after_state);}assert(audit.some(a=>a.before_state&&a.action==='NEWS_PUBLISHED'));
await db.exec(`reset role;delete from public.admin_members where user_id='${admin}';`);await as('authenticated',admin);await assert.rejects(save(post),e=>e.code==='42501','Revoked membership blocks stale token');
await db.exec('reset role;delete from public.site_operations');await as('service_role');await assert.rejects(db.query('select public.assert_store_accepting_orders()'),/unavailable/,'Missing singleton fails closed');
await db.close();console.log('Operations V1: '+migrations.length+' migrations; membership/RLS, public projections, UTC schedules, guard/no business writes, News lifecycle/stable slug, optimistic concurrency and audit PASS');
