import assert from 'node:assert/strict';
import {createOrderStore,componentOrderItem,kitOrderItem,orderStorageKey} from '../dist/admin/orders/model.mjs';
import {createKitSnapshot} from '../dist/les-paul-kits/snapshot.mjs';
import {initialComponents} from '../dist/admin/data.mjs';
const map=new Map(),storage={getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,v)};
let queue=Promise.resolve();const lock=(key,fn)=>{const work=queue.then(fn);queue=work.catch(()=>{});return work;};
const store=createOrderStore(storage,{lock});const stock=initialComponents(),original=JSON.stringify(stock);
const component=stock.find(x=>x.id==='bleed-prs'),kit=createKitSnapshot({wiring:'modern',bleed:'duncan',matching:'precision',jack:'pureTone'});
const input={customer:{name:'Test Customer'},delivery:{postcode:'NG1',country:'UK'},channel:'MANUAL',status:'DRAFT',deliveryPrice:300,items:[componentOrderItem(component,2),kitOrderItem(kit,1)]};
const first=await store.create(input,'request1');assert.equal(first.reference,'AI-10001');assert.equal(first.pricing.total,first.items.reduce((n,i)=>n+i.lineTotal,300));assert.deepEqual(first.items[1].snapshot,kit);
assert.equal((await store.create(input,'request1')).id,first.id);assert.equal(store.list().length,1);
component.name='Changed';component.salePrice=999999;kit.pricing.total=1;input.items[0].snapshot.name='Changed';
assert.equal(store.get(first.id).items[0].name,first.items[0].name);assert.deepEqual(store.get(first.id).items[1].snapshot,first.items[1].snapshot);
await store.setStatus(first.id,'PAID');assert.deepEqual(store.get(first.id).items,first.items);assert.equal(store.get(first.id).statusHistory.length,2);
const [a,b]=await Promise.all([store.create(input,'request2'),createOrderStore(storage,{lock}).create(input,'request3')]);assert.deepEqual([a.reference,b.reference],['AI-10002','AI-10003']);
await store.setStatus(a.id,'CANCELLED');assert.equal((await store.create(input,'request4')).reference,'AI-10004');
assert.deepEqual(createOrderStore(storage,{lock}).list(),store.list());
await assert.rejects(store.create({...input,items:[]},'bad'),/Add between/);
await assert.rejects(store.create({...input,deliveryPrice:-1},'bad'),/non-negative/);
await assert.rejects(store.create({...input,items:[{...input.items[0],quantity:1.5}]},'bad'),/whole number/);
await assert.rejects(store.setStatus(first.id,'NO'),/valid order status/);
await assert.rejects(createOrderStore(storage).create(input,'nolock'),/lock support/);
const quota=createOrderStore({getItem:()=>null,setItem:()=>{throw new Error();}},{lock});await assert.rejects(quota.create(input,'quota'),/could not be saved/);
const corrupted=new Map([[orderStorageKey,'{broken']]);await assert.rejects(createOrderStore({getItem:k=>corrupted.get(k),setItem:()=>assert.fail('must not overwrite')},{lock}).create(input,'corrupt'),/could not be read/);
const clean=initialComponents();assert.equal(JSON.stringify(clean),original,'No central stock data changed');
console.log('Orders: mixed snapshots, independent historical content/pricing, reload, unique serialized references, retry idempotence, cancellation without reuse, status history, safe failures and no stock writes passed.');

// Real basket handoff, without rewriting basket or central inventory.
import {basketOrderItems} from '../dist/admin/orders/handoff.mjs';
import {createComponentStore,storageKey} from '../dist/admin/data.mjs';
import {addKit,addComponent,readBasket} from '../dist/commerce.mjs';
const browserMap=new Map();globalThis.localStorage={getItem:k=>browserMap.get(k)??null,setItem:(k,v)=>browserMap.set(k,v)};globalThis.window=new EventTarget();
const central=createComponentStore(localStorage),seed=central.list();central.save(seed[0],seed[0].id);
addKit({wiring:'60s',bleed:'premium',selector:'switchcraft'});addComponent('bleed-prs');
const inventoryBefore=localStorage.getItem(storageKey),basketBefore=localStorage.getItem('apparition.basket.v1');
const orders=createOrderStore(localStorage,{lock});
const handoff=await orders.create({...input,items:basketOrderItems(readBasket(),central.list()),channel:'WEBSITE'},'basket-order');
assert.equal(handoff.items.length,2);assert.equal(handoff.items[0].type,'kit');assert.equal(handoff.items[1].type,'component');
assert.equal(localStorage.getItem(storageKey),inventoryBefore);assert.equal(localStorage.getItem('apparition.basket.v1'),basketBefore);
const live=central.list().find(p=>p.id==='bleed-prs');central.save({...live,name:'Renamed after order',productTitle:'Different title',salePrice:99999},live.id);
assert.notEqual(orders.get(handoff.id).items[1].name,'Different title');assert.equal(orders.get(handoff.id).items[1].unitPrice,handoff.items[1].unitPrice);
const afterAdmin=localStorage.getItem(storageKey);await orders.setStatus(handoff.id,'DISPATCHED');assert.equal(localStorage.getItem(storageKey),afterAdmin);
assert.throws(()=>basketOrderItems([],central.list()),/empty/);
assert.throws(()=>basketOrderItems([{product:'component',sku:'missing',quantity:1}],central.list()),/active/);
assert.throws(()=>kitOrderItem({...handoff.items[0].snapshot,schemaVersion:2}),/older kit/);
assert.throws(()=>componentOrderItem(live,1,null),/GBP/);
console.log('Actual mixed basket handoff, existing central inventory persistence, subsequent Admin edits and no basket/stock writes passed.');
