import assert from 'node:assert/strict';
import {contactFromStripeSession,storeVerifiedContact} from '../supabase/functions/stripe-webhook/contact.ts';
import {syncOrderContact} from '../supabase/functions/sync-order-contact/index.ts';
const id='12345678-1234-1234-1234-123456789012';
const session={id:'cs_live_0123456789abcdef',livemode:true,payment_status:'paid',amount_total:400,currency:'gbp',payment_intent:'pi_0123456789abcdef',client_reference_id:'AI-010010',metadata:{order_id:id,order_reference:'AI-010010'},customer_details:{name:'A Person',email:'person@example.test'},collected_information:{shipping_details:{name:'Recipient',address:{line1:'10 Street',line2:null,city:'Nottingham',postal_code:'NG1 1AA',country:'GB'}}}};
const contact=contactFromStripeSession(session);
assert.deepEqual(contact,{customer:{name:'A Person',email:'person@example.test'},delivery:{recipient:'Recipient',line1:'10 Street',city:'Nottingham',postcode:'NG1 1AA',country:'GB'}});
assert.equal(contactFromStripeSession({...session,livemode:false}),null);
assert.equal(contactFromStripeSession({...session,collected_information:{shipping_details:{...session.collected_information.shipping_details,address:{country:'GB'}}}}),null);
const env={get:key=>({SUPABASE_URL:'https://example.supabase.co',SUPABASE_ANON_KEY:'public-key',SUPABASE_SERVICE_ROLE_KEY:'private-service',STRIPE_SECRET_KEY:'rk_live_fixture'})[key]};
const calls=[];
const request=async(url,init)=>{calls.push({url,init});if(url.endsWith('/auth/v1/user'))return Response.json({id});if(url.includes('/admin_members?'))return Response.json([{user_id:id}]);if(url.includes('/rest/v1/orders?'))return Response.json([{id,reference:'AI-010010',status:'pending',payment_status:'paid',stripe_checkout_session_id:session.id,stripe_payment_intent_id:session.payment_intent,total_pence:400}]);if(url.startsWith('https://api.stripe.com/'))return Response.json(session);if(url.endsWith('/rpc/save_stripe_order_contact'))return Response.json('saved');throw Error(url);};
const input=(reference='AI-010010',token='admin-token')=>new Request('https://example.supabase.co/functions/v1/sync-order-contact',{method:'POST',headers:{Origin:'https://apparitioninstruments.co.uk',Authorization:'Bearer '+token},body:JSON.stringify({reference,customer:{name:'Evil'},delivery:{line1:'Evil'}})});
assert.equal((await syncOrderContact(input(),env,request)).status,200);
assert.equal(calls.length,5);
const payload=JSON.parse(calls.at(-1).init.body);assert.deepEqual(payload.p_customer,contact.customer);assert.deepEqual(payload.p_delivery,contact.delivery);
assert(!JSON.stringify(calls.at(-1)).includes('Evil'));
assert.equal((await syncOrderContact(input('AI-010010','bad'),env,async()=>new Response('',{status:401}))).status,403);
assert.equal((await syncOrderContact(input(),env,async(url)=>url.endsWith('/auth/v1/user')?Response.json({id}):Response.json([]))).status,403);
const repeat=[];assert.equal(await storeVerifiedContact(session,env,async(url,init)=>{repeat.push({url,init});return Response.json('already_saved');}),true);
assert.equal(repeat.length,1,'Contact retry calls only the contact RPC, never inventory fulfilment');
console.log('P07B.4: trusted Stripe customer/shipping, optional line2, Admin membership, ignored browser fields, idempotent contact-only sync PASS');
