import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {routeEmailRequest} from '../supabase/functions/transactional-email/index.ts';
const canary=readFileSync('supabase/migrations/20260926232000_p08b5a_ai010010_canary.sql','utf8');
const retirement=readFileSync('supabase/migrations/20260927112500_p08b5b_global_activation.sql','utf8');
assert.match(canary,/ai010010-lifecycle-email-canary/);
assert.match(retirement,/cron\.unschedule\('ai010010-lifecycle-email-canary'\)/);
assert.match(retirement,/drop function public\.get_ai010010_canary_token/);
const response=await routeEmailRequest(new Request('https://example.invalid/functions/v1/transactional-email/canary',{method:'POST'}),{get:()=>undefined});
assert.equal(response.status,404);
console.log('P08B.5A: historic canary retired without changing its ledger evidence PASS');
