import assert from 'node:assert/strict';
import {readFileSync,readdirSync} from 'node:fs';
import {execFileSync} from 'node:child_process';
import {Window} from 'happy-dom';
import {makeCircuit} from '../dist/wiring-generator/model.mjs';
import {drawCircuit} from '../dist/wiring-generator/render.mjs';
import {forgeDiagram} from '../dist/circuit-forge/presentation.mjs';
import {componentTitlePosition} from '../dist/wiring-generator/composition.mjs';
import {createAuthenticatedRepositoryTransport} from '../dist/backend/providers.mjs';
import {createAdminOptionRepository} from '../dist/backend/catalogue-options.mjs';
const read=p=>readFileSync(p,'utf8'),settings={disableCSSFileLoading:true,disableJavaScriptFileLoading:true,disableJavaScriptEvaluation:true};
const files=[];function walk(dir){for(const e of readdirSync(dir,{withFileTypes:true}))e.isDirectory()?walk(dir+'/'+e.name):e.name.endsWith('.html')&&files.push(dir+'/'+e.name);}walk('dist');
function styles(win,path){for(const link of win.document.querySelectorAll('link[rel=stylesheet]')){const href=link.getAttribute('href').split('?')[0],file=href.startsWith('/')?'dist'+href:new URL(href,'file://'+process.cwd()+'/'+path).pathname;if(!file.endsWith('.css'))continue;const s=win.document.createElement('style');s.textContent=read(file).replace(/@media\(/g,'@media (').replace(/@import[^;]+;/g,'');win.document.head.append(s);}}
let disclosures=0;
for(const path of files){const w=new Window({width:1400,settings});w.document.write(read(path));const d=w.document;if(!d.querySelector('.nav-components')){w.close();continue;}styles(w,path);
 for(const detail of d.querySelectorAll('.nav-components')){detail.open=true;const menu=detail.querySelector('.components-menu'),links=[...menu.querySelectorAll(':scope>a')];assert.equal(links.length,4,path);assert.equal(w.getComputedStyle(menu).display,'grid',path+' disclosure layout');for(const link of links.slice(0,3)){assert.equal(w.getComputedStyle(link).display,'flex',path+' item layout');assert.equal(w.getComputedStyle(link).gap,'14px');assert.equal(w.getComputedStyle(link.querySelector('strong')).display,'block');assert.equal(w.getComputedStyle(link.querySelector('small')).display,'block');assert.equal(w.getComputedStyle(link.querySelector('small')).marginTop,'5px');assert.equal(w.getComputedStyle(link).whiteSpace,'normal');}disclosures++;}
 w.close();
}
assert(disclosures>=100);
// Real shared site listeners: native disclosure, keyboard, hover, and mobile.
const w=new Window({width:1400,settings,url:'https://apparitioninstruments.co.uk/'});w.document.write(read('dist/index.html'));const queries=new Map();w.matchMedia=q=>{if(!queries.has(q))queries.set(q,{matches:q.includes('1181')||q.includes('prefers-reduced-motion'),addEventListener(){}});return queries.get(q);};Object.assign(globalThis,{window:w,document:w.document,matchMedia:w.matchMedia,requestAnimationFrame:()=>{}});await import('../dist/site.mjs?platform-qa');const detail=w.document.querySelector('.site-header .nav-components'),summary=detail.querySelector('summary'),links=[...detail.querySelectorAll('a')];detail.dispatchEvent(new w.Event('pointerenter'));assert(detail.open);summary.focus();summary.dispatchEvent(new w.KeyboardEvent('keydown',{key:'ArrowDown',bubbles:true}));assert.equal(w.document.activeElement,links[0]);links[0].dispatchEvent(new w.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));assert(!detail.open);assert.equal(w.document.activeElement,summary);const mobile=w.document.querySelector('#mobile-nav'),button=w.document.querySelector('.menu-button');button.click();assert(!mobile.hidden);w.document.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));assert(mobile.hidden);assert.equal(w.document.activeElement,button);assert([...queries.keys()].some(q=>q.includes('1181')));assert(![...queries.keys()].some(q=>q.includes('1101')));w.close();
// Label ownership and geometry in all three presentations; preserve useful values.
const parser=new Window({settings});for(const guitar of ['les-paul','sg','tele','strat']){const c=makeCircuit({guitar}),before=JSON.stringify(c);for(const mode of ['trace','build','explain']){const d=new parser.DOMParser().parseFromString(drawCircuit(c,{mode}),'image/svg+xml');for(const p of c.components.filter(p=>p.type==='pot')){const title=d.querySelectorAll(`text[data-label-component="${p.id}"][data-label-role="title"]`),value=d.querySelectorAll(`text[data-label-component="${p.id}"].part-value`);assert.equal(title.length,1);assert.equal(value.length,1);assert.equal(title[0].textContent,p.label);assert.equal(value[0].textContent,p.value.replace('CTS ',''));assert(Number(value[0].getAttribute('y'))-componentTitlePosition(p).y>=24,'Title/value line boxes must not overlap');assert.equal(d.querySelectorAll(`[data-component="${p.id}"] .pot-solder-lug`).length,3);}}
 const forge=new parser.DOMParser().parseFromString(forgeDiagram(c),'image/svg+xml');for(const p of c.components.filter(p=>p.type==='pot'))assert.equal(forge.querySelectorAll(`text[data-label-component="${p.id}"].part-value`).length,1);assert.equal(JSON.stringify(c),before);
}
// Inline renderer CSS must not repaint unrelated editorial/response SVG text.
parser.document.body.innerHTML='<svg><text id="outside" class="part-title">Editorial</text></svg><p class="muted" id="outside-muted">Supporting text</p>';const oldFill=parser.getComputedStyle(parser.document.querySelector('#outside')).fill,oldOpacity=parser.getComputedStyle(parser.document.querySelector('#outside-muted')).opacity;const isolated=new parser.DOMParser().parseFromString(drawCircuit(makeCircuit()),'image/svg+xml').documentElement;parser.document.body.append(isolated);const isolatedStyle=parser.document.createElement('style');isolatedStyle.textContent=isolated.querySelector('style').textContent;parser.document.head.append(isolatedStyle);assert.equal(parser.getComputedStyle(parser.document.querySelector('#outside')).fill,oldFill);assert.equal(parser.getComputedStyle(parser.document.querySelector('#outside-muted')).opacity,oldOpacity);parser.close();
// Dedicated cream showcase: validate resolved palette and contrast at the actual responsible nodes.
const home=new Window({width:1400,settings});home.document.write(read('dist/index.html'));styles(home,'dist/index.html');const section=home.document.querySelector('.forge-reveal');section.classList.add('has-circuit','is-animated');const mounted=new home.DOMParser().parseFromString(read('dist/assets/signal-forge-full.svg'),'image/svg+xml').documentElement;section.querySelector('.forge-reveal-circuit').replaceChildren(mounted);const mountedStyle=home.document.createElement('style');mountedStyle.textContent=mounted.querySelector('style').textContent;home.document.head.append(mountedStyle);section.querySelector('.forge-reveal-response').innerHTML='<svg><text class="response-axis">dB</text><text class="response-tick">1 kHz</text></svg><div class="forge-reveal-response-context"><small>Electrical model</small></div>';const get=e=>home.getComputedStyle(e),bg=get(section).backgroundColor;
const rgb=s=>s.startsWith('#')?s.slice(1).match(/../g).map(x=>parseInt(x,16)):s.match(/[\d.]+/g)?.slice(0,3).map(Number);const lum=s=>{const v=rgb(s);assert(v?.length===3,'Resolvable colour '+s);const a=v.map(x=>{x/=255;return x<=.04045?x/12.92:((x+.055)/1.055)**2.4;});return .2126*a[0]+.7152*a[1]+.0722*a[2];};const contrast=(a,b)=>(Math.max(lum(a),lum(b))+.05)/(Math.min(lum(a),lum(b))+.05);
assert.equal(section.querySelector('svg[data-diagram-surface]').dataset.diagramSurface,'cream');assert.equal(bg,'#eee8db');for(const disc of section.querySelectorAll('.forge-crossing circle'))assert.equal(get(disc).fill,bg,'Crossing clearance uses the editorial surface');for(const stage of ['0','1','2','3']){section.dataset.stage=stage;const opacity=get(section.querySelector('.forge-reveal-circuit')).opacity;assert(opacity===''||Number(opacity)===1,'No whole-diagram disabled opacity');}for(const sel of ['.response-axis','.response-tick','.home-editorial-path text'])assert(contrast(get(section.querySelector(sel)).fill,bg)>=4.5,sel+' foreground/surface contrast');assert(contrast(get(section.querySelector('.forge-reveal-response-context small')).color,bg)>=4.5);const crossingProbe=new home.DOMParser().parseFromString(drawCircuit(makeCircuit(),{palette:'editorial',surface:'dark'}),'image/svg+xml').documentElement;section.append(crossingProbe);const probeStyle=home.document.createElement('style');probeStyle.textContent=crossingProbe.querySelector('style').textContent;home.document.head.append(probeStyle);const probeDiscs=crossingProbe.querySelectorAll('.forge-crossing circle');assert(probeDiscs.length>0);for(const disc of probeDiscs)assert.equal(get(disc).fill,'#171a17','Technical crossings preserve their dark surface');home.close();
assert(!read('dist/customer-ui.css').includes('.site-ui.home-page .forge-reveal{'),'No contradictory outer-only palette override');assert(!read('dist/knowledge.css').includes('.components-menu'),'Category disclosure belongs to shell');assert(read('dist/forge-reveal.mjs').includes('asset.search=new URL(import.meta.url).search'),'Generated SVG follows build cache identity');
assert(!read('scripts/generate-signal-forge-preview.mjs').includes('filter:'),'Do not generate the unreferenced filtered preview');
// Repository through the real transport: the previously omitted action is sent once.
let calls=0;const transport=createAuthenticatedRepositoryTransport({accessToken:async()=>'fixture-user'},{request:async(url,opts)=>{calls++;assert(url.endsWith('/rpc/delete_unused_catalogue_option'));assert.equal(opts.method,'POST');assert.equal(opts.headers.Authorization,'Bearer fixture-user');assert.deepEqual(JSON.parse(opts.body),{p_set:'manufacturer',p_key:'unused'});return {ok:true,json:async()=>({deleted:true})};}});assert.equal((await createAdminOptionRepository(transport).remove('manufacturer','unused')).deleted,true);assert.equal(calls,1);await assert.rejects(transport.send('rpc/arbitrary_privileged_action'),/Unsupported/);assert.equal(calls,1);await assert.rejects(createAuthenticatedRepositoryTransport({accessToken:async()=>{throw Error('Session expired');}},{request:async()=>{throw Error('Must not request');}}).send('rpc/delete_unused_catalogue_option'),/Session expired/);
// Equation and commerce authorities are byte-preserved from the verified start.
for(const dir of ['dist/electronics','supabase/migrations','supabase/functions','dist/circuit-forge/response.mjs','dist/treble-bleed-designer/engine.mjs','dist/wiring-generator/model.mjs','dist/les-paul-kits/config.mjs','dist/admin/admin-auth.mjs','dist/backend/order-data.mjs']){for(const p of execFileSync('git',['ls-tree','-r','--name-only','2d8cf37f7dd082d5f4e6419738ea02201cf33b5d',dir],{encoding:'utf8'}).trim().split('\n').filter(Boolean)){if(['dist/electronics/presentation/homepage-state.mjs','supabase/functions/create-checkout/index.ts'].includes(p))continue;if(['20260925104500_p07b_qualify_delivery_country.sql','20260925151500_p07b2a_qualify_inventory_update.sql'].some(x=>p.endsWith('/'+x)))continue;assert.equal(read(p),execFileSync('git',['show','2d8cf37f7dd082d5f4e6419738ea02201cf33b5d:'+p],{encoding:'utf8'}),p);}}
console.log(JSON.stringify({dropdowns:disclosures,keyboard:'PASS',singleLabels:'PASS',editorialSurfaceAndContrast:'PASS',SVGStyleIsolation:'PASS',adminDispatch:'PASS',protectedAuthorities:'PASS'}));
