import assert from 'node:assert/strict';
import {readFileSync,existsSync} from 'node:fs';
import {Window} from 'happy-dom';
import {articles,topics,tools,paths,relationships,glossary,symptoms,articleURL,toolURL,exampleState,relationshipLinks} from '../dist/knowledge/registry.mjs';
import {normaliseProject,projectFromCircuit,projectURL,shareProjectURL,readProject,createProjectStore,projectStorageKey,instrumentDescription} from '../dist/electronics/state/project.mjs';
import {normaliseCircuitState,readCircuitState,readDesignerHandoff,wiringHandoff,kitHandoff,circuitStateSummary} from '../dist/electronics/state/circuit-state.mjs';
import {forgeCircuit} from '../dist/circuit-forge/model.mjs';
import {reconcileKitProject,kitProjectLink,projectKitHandoff} from '../dist/knowledge/kit-project.mjs';
import {configurationFromURL} from '../dist/les-paul-kits/config.mjs';
import {mountHubSearch} from '../dist/luthier-hub/hub.mjs';
import {mountProjectPanel} from '../dist/knowledge/project-panel.mjs';
import {productContext} from '../dist/products/model.mjs';
const circuit=forgeCircuit({position:'neck',bleed:'duncan'}).circuit;
const p=projectFromCircuit(circuit,{name:'Private instrument name',extensions:{future:{safe:true,notes:'Private bench notes'}}});
assert.equal(instrumentDescription(circuit).pickups.length,2);assert.equal(instrumentDescription(circuit).controls.length,4);
assert.deepEqual(normaliseProject(p),p);assert.throws(()=>normaliseProject({...p,version:99}));assert.throws(()=>normaliseProject({...p,electronics:null}));assert.throws(()=>normaliseProject({...p,name:'x'.repeat(81)}));assert.throws(()=>normaliseProject({...p,extensions:JSON.parse('{"__proto__":{}}')}));assert.throws(()=>normaliseProject({...p,electronics:{...p.electronics,configuration:{guitar:'strat'}}}));
const share=shareProjectURL(p);assert.equal(share,shareProjectURL(p));assert(share.length<16000);assert(!decodeURIComponent(share).includes(p.name));assert(!decodeURIComponent(share).includes('Private bench notes'));assert(!share.includes('wp='));assert.deepEqual(readProject(new URL(share,'https://example.test').search).project.electronics,p.electronics);
assert.deepEqual(readProject('?sf='+encodeURIComponent(JSON.stringify(p.electronics))).project.electronics,p.electronics);assert.equal(readProject('?ap=broken&sf='+encodeURIComponent(JSON.stringify(p.electronics))).project,null);assert.equal(readProject('?ap='+encodeURIComponent(JSON.stringify({...p,version:2}))).project,null);assert.equal(readProject('?ap='+'x'.repeat(16001)).project,null);assert.deepEqual(normaliseCircuitState({...p.electronics,future:true}),p.electronics);
const data=new Map(),storage={getItem:k=>data.get(k)??null,setItem:(k,v)=>data.set(k,v),removeItem:k=>data.delete(k)},store=createProjectStore(storage);assert.equal(store.list().entries.length,0);const id=store.save(p);assert.deepEqual(store.restore(id),p);store.rename(id,'My guitar');assert.equal(store.restore(id).name,'My guitar');const copy=store.duplicate(id);assert.notEqual(copy,id);assert.notEqual(store.restore(copy).contextId,p.contextId);assert.deepEqual(store.restore(copy).extensions,p.extensions);store.delete(id);assert.equal(store.list().entries.length,1);assert.throws(()=>store.restore(id));
storage.setItem(projectStorageKey,'broken');assert.match(store.list().notice,/could not/);assert.throws(()=>store.save(p));assert.equal(storage.getItem(projectStorageKey),'broken');store.clearInvalid();assert.equal(store.list().entries.length,0);
// Same-tab context is separate from public share state and permanent saves.
globalThis.sessionStorage=storage;const local=projectURL(wiringHandoff(circuit),p),localProject=readProject(new URL(local,'https://example.test').search).project;assert.equal(localProject.name,p.name);assert.deepEqual(localProject.extensions,p.extensions);const changed=forgeCircuit({position:'bridge',neckCap:'0.047'}).circuit;const next=projectFromCircuit(changed,localProject);const returned=readProject(new URL(projectURL('/circuit-forge/',next),'https://example.test').search).project;assert.equal(returned.electronics.configuration.position,'bridge');assert.deepEqual(returned.extensions,p.extensions);assert.equal(store.list().entries.length,0,'handoffs do not permanently save');
const kitURL=kitHandoff(circuit).url;assert(kitURL);const kit=configurationFromURL(new URL(kitURL,'https://example.test').search),reconciled=reconcileKitProject(p,kit);assert.deepEqual(reconciled.kitReference,{id:'kit-les-paul',family:'les-paul'});assert.deepEqual(reconciled.extensions.future,p.extensions.future);assert.equal(reconciled.extensions.kitSelection.family,'les-paul');assert(projectKitHandoff(circuit,reconciled).url.includes('config='));assert.deepEqual(reconciled.electronics,p.electronics);assert(readProject(new URL(kitProjectLink(kitURL,p,kit),'https://example.test').search).project);assert.equal(kitHandoff(forgeCircuit({position:'neck'},undefined,{channels:{neck:{pickup:'generic',volumePot:250,tonePot:500},bridge:{pickup:'generic',volumePot:500,tonePot:500}},cableC:500,loadR:1}).circuit).url,null);
assert.equal(circuitStateSummary(circuit),circuitStateSummary(circuit));assert.match(circuitStateSummary(circuit),/Modern/);
assert.equal(topics.length,8);assert.equal(new Set(articles.map(a=>a.id)).size,articles.length);assert.equal(glossary.length,25);assert.equal(symptoms.length,10);for(const [,ids] of paths)for(const id of ids)assert(articles.some(a=>a.id===id));
for(const [key,r] of Object.entries(relationships)){assert(articles.some(a=>a.id===r.article));assert(tools[r.tool]);assert(relationshipLinks(key).length>=2);}
for(const [id] of Object.entries(tools)){const url=toolURL(id);assert(existsSync('dist'+new URL(url,'https://example.test').pathname+'index.html'));if(['signal','circuit'].includes(id))assert(readCircuitState(new URL(url,'https://example.test').search).state);if(id==='bleed')assert(readDesignerHandoff(new URL(toolURL(id,'duncan'),'https://example.test').search).response);}
assert.equal(readCircuitState(new URL(toolURL('signal','250k'),'https://example.test').search).state.responseAssumptions.channels.neck.volumePot,250);assert.equal(readCircuitState(new URL(toolURL('signal','047'),'https://example.test').search).state.configuration.neckCap,'0.047');
for(const category of ['potentiometers','capacitors','treble-bleeds'])assert.deepEqual(productContext[category].links,relationshipLinks(category));
for(const item of articles){const path='dist/luthier-hub/'+item.slug+'/index.html',html=readFileSync(path,'utf8'),w=new Window({settings:{disableCSSFileLoading:true,disableJavaScriptEvaluation:true,disableJavaScriptFileLoading:true},url:'https://example.test/luthier-hub/'+item.slug+'/'});w.document.write(html);assert.equal(w.document.querySelectorAll('h1').length,1);assert(w.document.querySelector('meta[name=description]'));assert(w.document.querySelector('link[rel=canonical]'));assert(!w.document.body.textContent.includes('Circuit Forge'));
 for(const a of w.document.querySelectorAll('main a[href]')){const url=new URL(a.href);if(url.origin!=='https://example.test')continue;assert(existsSync('dist'+url.pathname+'index.html')||existsSync('dist'+url.pathname),item.id+' missing '+url.pathname);if(url.hash&&url.pathname===w.location.pathname)assert(w.document.getElementById(decodeURIComponent(url.hash.slice(1))),item.id+' missing anchor '+url.hash);}
 await w.happyDOM.close();}
const win=new Window({url:'https://example.test/luthier-hub/',settings:{disableCSSFileLoading:true,disableJavaScriptEvaluation:true,disableJavaScriptFileLoading:true}});win.document.write(readFileSync('dist/luthier-hub/index.html','utf8'));const doc=win.document;mountHubSearch(doc);for(const term of ['500k','0.022','treble bleed','hum','ground','pickup colours','selector']){doc.querySelector('#hub-search').value=term;doc.querySelector('#hub-search').dispatchEvent(new win.Event('input'));assert([...doc.querySelectorAll('[data-search]')].some(n=>!n.hidden),term);}doc.querySelector('#hub-search').value='no-match-unique';doc.querySelector('#hub-search').dispatchEvent(new win.Event('input'));assert.equal(doc.querySelector('#hub-empty').hidden,false);
const css=readFileSync('dist/knowledge.css','utf8');for(const width of [320,390,768,1400]){win.happyDOM.setWindowSize({width,height:800});assert(css.includes('grid-template-columns:repeat(2,minmax(0,1fr))'));assert(css.includes('@media(max-width:680px)'));assert(css.includes('overflow-wrap:anywhere'));assert(css.includes('max-width:100%;overflow-x:auto'));assert(doc.querySelector('label[for=hub-search]'));assert(doc.querySelector('label[for=hub-topic]'));}assert(css.includes(':focus-visible'));
// Explicit local project actions with fixture storage and isolated navigation.
for(const [key,value] of Object.entries({location:win.location,navigator:win.navigator}))Object.defineProperty(globalThis,key,{value,configurable:true,writable:true});const panel=doc.createElement('section');doc.body.append(panel);let context=p,destination='';mountProjectPanel(panel,{getCircuit:()=>circuit,getProject:()=>context,setProject:v=>context=v,reset:()=>context=null,navigate:url=>destination=url,storage});const click=async text=>{[...panel.querySelectorAll('button')].find(b=>b.textContent===text).click();await new Promise(r=>setTimeout(r,0));};assert.equal(store.list().entries.length,0);await click('Save current');assert.equal(store.list().entries.length,1);const selected=store.list().entries[0].id;panel.querySelector('select').value=selected;await click('Open');assert(readProject(new URL(destination,'https://example.test').search).project);await click('New / reset');assert.equal(context,null);assert.equal(store.list().entries.length,1);
await win.happyDOM.close();console.log('Platform V2: schema, legacy/URL/session continuity, private fields, local CRUD, kit compatibility, registry/routes/anchors, handoffs, search, semantic and responsive contracts PASS (isolated fixtures)');
