import assert from 'node:assert/strict';
import {spawnSync} from 'node:child_process';
import {readFileSync} from 'node:fs';
import {Window} from 'happy-dom';
import {forgeCircuit} from '../dist/circuit-forge/model.mjs';
import {projectFromCircuit,projectURL,readProject,projectStorageKey} from '../dist/electronics/state/project.mjs';
import {wiringHandoff,designerHandoff,readCircuitState,kitHandoff} from '../dist/electronics/state/circuit-state.mjs';
const scenario=process.argv[2];if(!scenario){for(const mode of ['forge','new-save','generator','generator-kit','designer','malformed','conductors','guide']){const r=spawnSync(process.execPath,[new URL(import.meta.url).pathname,mode],{encoding:'utf8',timeout:45000});assert.equal(r.status,0,mode+'\n'+r.stdout+'\n'+r.stderr);console.log(r.stdout.trim());}process.exit(0);}
const c=forgeCircuit({position:'neck',bleed:'duncan',neckProfile:'duncan',bridgeProfile:'dimarzio'}).circuit;c.state.controlPositions.neck.volume=4;c.state.responseAssumptions.cableC=800;
const p=projectFromCircuit(c,{name:'Private guitar',extensions:{future:{slot:'retained'}}});const store=new Map();globalThis.sessionStorage={getItem:k=>store.get(k)??null,setItem:(k,v)=>store.set(k,v),removeItem:k=>store.delete(k)};
const tool=['forge','new-save','malformed'].includes(scenario)?'circuit-forge':scenario.startsWith('generator')?'wiring-generator':scenario==='designer'?'treble-bleed-designer':scenario==='guide'?'luthier-hub/les-paul-installation':'luthier-hub/pickup-conductors';
const url=scenario==='guide'?projectURL(wiringHandoff(c).replace('/wiring-generator/','/luthier-hub/les-paul-installation/'),p):scenario==='new-save'?'/circuit-forge/':scenario==='conductors'?'/luthier-hub/pickup-conductors/':scenario==='malformed'?'/circuit-forge/?ap=broken&sf='+encodeURIComponent(JSON.stringify(p.electronics)):projectURL(scenario==='forge'?'/circuit-forge/?mode=signal':scenario==='generator-kit'?kitHandoff(c).url.replace('/les-paul-kits/','/wiring-generator/'):scenario==='generator'?wiringHandoff(c):designerHandoff(c).url,p);
const win=new Window({url:'https://example.test'+url,settings:{disableCSSFileLoading:true,disableJavaScriptFileLoading:true,disableJavaScriptEvaluation:true}});for(const key of ['window','document','localStorage','location','history','navigator','CSS','Event','MouseEvent','Node','HTMLElement','CustomEvent'])Object.defineProperty(globalThis,key,{value:key==='window'?win:win[key],configurable:true,writable:true});globalThis.matchMedia=win.matchMedia.bind(win);globalThis.fetch=async()=>{throw Error('Network forbidden in project fixture');};document.write(readFileSync('dist/'+tool+'/index.html','utf8'));
const $=s=>document.querySelector(s);
if(scenario==='guide'){await import('../dist/luthier-hub/articles.mjs');const link=$('[data-open-diagram]');assert(link);assert.deepEqual(readProject(new URL(link.href).search).project.extensions,p.extensions);assert($('[data-illustration] svg'));}
else if(scenario==='conductors'){await import('../dist/luthier-hub/conductors.mjs');assert($('[data-conductor-reference] table'));assert.match($('[data-conductor-reference]').textContent,/Seymour Duncan.*BLACK.*WHITE \+ RED/s);assert.match($('[data-conductor-reference]').textContent,/Model-specific \/ unresolved/);}
else{await import('../dist/'+tool+'/app.mjs?platform='+scenario);await new Promise(r=>setTimeout(r,5));
 if(scenario==='forge'){assert.equal($('#forge-response-lab').hidden,false);assert.equal($('.local-projects input').value,'Private guitar');assert.equal(localStorage.getItem(projectStorageKey),null);const handoff=readProject(new URL($('#forge-view-wiring').href).search).project;assert.equal(handoff.name,p.name);assert.deepEqual(handoff.extensions,p.extensions);assert.equal(handoff.electronics.responseAssumptions.cableC,800);assert.equal(readProject(new URL($('#forge-kit').href).search).project.electronics.controlPositions.neck.volume,4);assert($('a[href*="potentiometers-explained"]'));const button=[...$('.local-projects').querySelectorAll('button')].find(b=>b.textContent==='Save current');button.click();await new Promise(r=>setTimeout(r,0));assert.equal(JSON.parse(localStorage.getItem(projectStorageKey)).entries[0].project.name,p.name);}
 else if(scenario==='new-save'){const input=$('.local-projects input');input.value='New named circuit';[...$('.local-projects').querySelectorAll('button')].find(b=>b.textContent==='Save current').click();await new Promise(r=>setTimeout(r,0));assert.equal(readProject(new URL($('#forge-view-wiring').href).search).project.name,'New named circuit');assert.equal(readProject(window.location.search).project.name,'New named circuit');}
 else if(scenario.startsWith('generator')){if(scenario==='generator-kit'){assert.match($('#kit-transfer-note').textContent,/complete kit specification is retained/);assert(new URL($('#build-kit').href).searchParams.has('config'));}const returned=readProject(new URL($('#generator-source-circuit').href).search).project;assert.equal(returned.name,p.name);assert.deepEqual(returned.extensions,p.extensions);assert.deepEqual(returned.electronics,p.electronics);const form=$('#generator-form');form.elements.position.value='bridge';form.elements.position.dispatchEvent(new win.Event('change',{bubbles:true}));const changed=readProject(new URL($('#generator-source-circuit').href).search).project;assert.equal(changed.electronics.configuration.position,'bridge');assert.equal(changed.electronics.responseAssumptions.cableC,800);assert.deepEqual(changed.extensions,p.extensions);assert.equal(localStorage.getItem(projectStorageKey),null);}
 else if(scenario==='designer'){const returned=readProject(new URL($('#designer-source-circuit').href).search).project;assert.deepEqual(returned.extensions,p.extensions);assert.deepEqual(returned.electronics,p.electronics);const field=$('#designer-inputs').elements.volume;field.value=2;field.dispatchEvent(new win.Event('input',{bubbles:true}));assert.equal(readCircuitState(new URL($('#designer-source-circuit').href).search).state.controlPositions.neck.volume,4,'Designer experimental edits leave source intact');assert($('a[href*="luthier-hub/treble-bleeds"]'));}
 else{assert.match($('#forge-import-note').textContent,/Normal defaults/);assert.equal($('#forge-controls').elements.position.value,'both');}
}
if(scenario==='designer'){await Promise.allSettled([import('../dist/components/catalogue.mjs'),import('../dist/commerce.mjs')]);await new Promise(r=>setTimeout(r,10));}
await win.happyDOM.close();console.log('Platform project DOM '+scenario+': PASS');process.exit(0);
