import assert from 'node:assert/strict';
import {createComponentStore} from '../dist/admin/data.mjs';
import {moveSpecification} from '../dist/admin/product-content.mjs';
import {configuredKitDefinitions} from '../dist/wiring-kits/kit-data.mjs';
const memory=new Map(),storage={getItem:k=>memory.get(k)??null,setItem:(k,v)=>memory.set(k,v)};
const store=createComponentStore(storage),original=store.list().find(p=>p.id==='cde-022');
const beforeKit=configuredKitDefinitions(store.list());
let rows=[{label:'Manufacturer',value:'Cornell Dubilier'},{label:'Series',value:'225P'},{label:'Voltage',value:'200V'}];
let record=store.save({...original,productTitle:'Customer title',shortDescription:'Short copy',fullDescription:'First paragraph.\n\nSecond paragraph.',productSpecifications:rows},original.id);
assert.equal(record.name,original.name);assert.deepEqual(record.specs,original.specs);
rows=structuredClone(record.productSpecifications);rows[0].value='CDE';rows=moveSpecification(rows,2,-1);rows.splice(2,1);
store.save({...record,productSpecifications:rows},original.id);
record=createComponentStore(storage).list().find(p=>p.id===original.id);
assert.deepEqual(record.productSpecifications,[{label:'Manufacturer',value:'CDE'},{label:'Voltage',value:'200V'}]);
assert.equal(record.productTitle,'Customer title');assert.equal(record.shortDescription,'Short copy');assert.equal(record.fullDescription,'First paragraph.\n\nSecond paragraph.');
for(const key of ['name','sku','specs','stock','active','individually','inKits','salePrice','kitPrice','image'])assert.deepEqual(record[key],original[key],key);
const afterKit=configuredKitDefinitions(store.list());
// Public title/metadata now travel with customer kit snapshots; commercial and electrical fields stay unchanged.
assert.equal(afterKit['les-paul'].capacitors['225p-022'].label,'Customer title');
assert.equal(afterKit['les-paul'].capacitors['225p-022'].component.productTitle,'Customer title');
afterKit['les-paul'].capacitors['225p-022'].label=beforeKit['les-paul'].capacitors['225p-022'].label;
afterKit['les-paul'].capacitors['225p-022'].component.productTitle=beforeKit['les-paul'].capacitors['225p-022'].component.productTitle;
assert.deepEqual(afterKit,beforeKit);
assert.throws(()=>store.save({...record,productSpecifications:[{label:'Incomplete',value:''}]},record.id),/both a label/);
assert.equal(createComponentStore(storage).list().find(p=>p.id===record.id).productSpecifications.length,2);
store.save({...record,productTitle:'',shortDescription:'',fullDescription:'',productSpecifications:[]},record.id);
assert.deepEqual(store.list().find(p=>p.id===record.id).productSpecifications,[]);
console.log('Product content: independent fields, paragraph preservation, add/edit/remove/reorder rows, reload persistence, validation and unchanged stock/prices/images/kit data passed.');
const {storefrontProduct}=await import('../dist/components/catalogue.mjs');
const internal={...record,productTitle:'Product title',shortDescription:'Card copy',fullDescription:'Long copy\n\nNext paragraph',productSpecifications:[{label:'Second',value:'2'},{label:'First',value:'1'}]};
let product=storefrontProduct(internal);assert.equal(product.name,'Product title');assert.equal(product.cardDescription,'Card copy');assert.deepEqual(product.displaySpecifications,internal.productSpecifications);assert.deepEqual(product.specs,original.specs);assert.equal(product.price,original.salePrice);
product=storefrontProduct({...internal,productTitle:' ',shortDescription:''});assert.equal(product.name,original.name);assert.equal(product.cardDescription,internal.fullDescription);
product=storefrontProduct({...original,description:'Existing copy',productSpecifications:[]});assert.equal(product.cardDescription,'Existing copy');assert.deepEqual(product.displaySpecifications,Object.entries({Manufacturer:original.manufacturer,...original.specs}).map(([label,value])=>({label,value})));
assert.equal(storefrontProduct({...original,description:'',shortDescription:'',fullDescription:''}).cardDescription,'');
console.log('Storefront: title fallback, independent short/full copy, paragraph breaks, ordered specifications, technical fallback and unchanged pricing passed.');
