import {installDOMEnvironment} from './fixtures/dom-environment.mjs';
import {installCatalogueFixture} from './fixtures/catalogue-fixture.mjs';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {Window} from 'happy-dom';
import {forgeCircuit,defaultControls} from '../dist/circuit-forge/model.mjs';
import {forgeResponse,responseComponent} from '../dist/circuit-forge/response.mjs';
import {frequencyResponse,responseAt,magnitudeDB} from '../dist/electronics/response/engine.mjs';
import {frequencyResponse as designerLegacy} from '../dist/treble-bleed-designer/engine.mjs';
import {defaults} from '../dist/electronics/response/circuits.mjs';

const controls={neck:{volume:5,tone:4},bridge:{volume:9,tone:8}};
for(const channel of ['neck','bridge'])for(const bleed of ['none','prs','cap','duncan'])for(const toneCap of ['0.022','0.047']){
 const circuit=forgeCircuit({position:channel,bleed,[channel+'Cap']:toneCap},controls).circuit,report=forgeResponse(circuit,61);
 assert(report.supported,JSON.stringify({channel,bleed,toneCap,report}));
 const expected={...defaults,type:bleed==='none'?'none':bleed==='duncan'?'duncan':'capacitor',bleedC:bleed==='prs'?.18:1,volume:controls[channel].volume,tonePosition:controls[channel].tone,toneCap:Number(toneCap)*1000};
 assert.deepEqual(report.state,expected);
 assert.deepEqual(report.points,frequencyResponse(expected,61));
 assert.deepEqual(report.points,designerLegacy(expected,61),'Designer compatibility entry uses identical shared model');
 assert.equal(report.points[30].current,magnitudeDB(responseAt(expected,report.points[30].frequency)));
 assert.deepEqual(report.reference,bleed==='none'?null:frequencyResponse({...expected,type:'none'},61));
 assert.deepEqual(circuit.connections,forgeCircuit({position:channel,bleed,[channel+'Cap']:toneCap}).circuit.connections,'controls do not change topology');
 assert.equal(responseComponent(circuit,channel+'Volume').role,'volume');
 assert.equal(responseComponent(circuit,channel+'Tone').role,'tone');
 if(bleed!=='none')assert.equal(responseComponent(circuit,channel+'BleedCap').role,'bleed');
}
const off=forgeResponse(forgeCircuit({position:'neck'}, {neck:{volume:0,tone:0},bridge:{volume:7,tone:10}}).circuit);
assert(off.points.every(p=>p.current===-100));
for(const choices of [{position:'both'},{position:'neck',wiring:'50s'},{position:'bridge',wiring:'60s'}])assert.equal(forgeResponse(forgeCircuit(choices).circuit).supported,false);
assert.equal(forgeResponse(forgeCircuit({position:'neck'}).circuit).reference,null);
assert.throws(()=>forgeCircuit({}, {neck:{volume:11,tone:10},bridge:{volume:7,tone:10}}));
const missing=forgeCircuit({position:'neck'}).circuit;missing.components=missing.components.filter(p=>p.id!=='neckTone');assert.equal(forgeResponse(missing).supported,false);
assert.equal(defaultControls.neck.volume,7);
for(const bleed of ['none','prs'])for(const volume of [9.9,10]){
 const report=forgeResponse(forgeCircuit({position:'neck',bleed},{neck:{volume,tone:6},bridge:{volume:7,tone:8}}).circuit);
 assert.deepEqual(report.points,frequencyResponse(report.state,201));
 assert.deepEqual(report.reference,bleed==='none'?null:frequencyResponse({...report.state,type:'none'},201));
 assert.equal(/effectively inactive at full volume/.test(report.summary),bleed!=='none'&&volume===10);
}

const html=readFileSync('dist/circuit-forge/index.html','utf8');
const app=readFileSync('dist/circuit-forge/app.mjs','utf8');
for(const id of ['forge-mode-physical','forge-response-lab','forge-response-volume','forge-response-tone','forge-response-graph','forge-response-assumptions'])assert(html.includes(`id="${id}"`));
assert.equal((html.match(/id="forge-response-lab"/g)||[]).length,1);
assert(!html.includes('<details id="forge-response-lab"'));
assert(html.includes('data-forge-mode="physical" aria-pressed="true"')&&html.includes('data-forge-mode="signal" aria-pressed="false"'));
assert(app.includes('circuit.state.controlPositions[channel][name]=Number(event.target.value)'));
assert(app.includes('renderLab()')&&app.includes('updateLabSelection()'));
console.log('Response Lab: shared Designer parity, control state, component link and unsupported boundaries PASS');

const win=new Window({url:'https://apparitioninstruments.co.uk/circuit-forge/',settings:{disableCSSFileLoading:true,disableJavaScriptFileLoading:true,disableJavaScriptEvaluation:true}});
win.document.write(html);
installDOMEnvironment(win);installCatalogueFixture();
await import('../dist/circuit-forge/app.mjs?response-lab-test');
const $=selector=>win.document.querySelector(selector);
const pick=(name,value)=>$(`[name="${name}"][value="${value}"]`).click();
const labPick=value=>$(`[data-lab-pickup="${value}"]`).click();
const selector=()=>win.document.querySelector('#forge-controls').elements.namedItem('position').value;
const mode=value=>$(`[data-forge-mode="${value}"]`).click();
assert(!$('#forge-mode-physical').hidden&&$('#forge-response-lab').hidden,'Physical Circuit is the default workspace');
assert.match($('#forge-response-summary').textContent,/Both pickups/);
mode('signal');assert($('#forge-mode-physical').hidden&&!$('#forge-response-lab').hidden);
assert.equal($('[data-forge-mode="signal"]').getAttribute('aria-pressed'),'true');
assert.equal($('#forge-diagram-title').textContent,'Signal Lab');
assert(!$('#forge-response-actions').hidden&&$('#forge-response-lab').classList.contains('is-unsupported'));
assert.equal($('[data-lab-pickup="both"]').getAttribute('aria-pressed'),'true');
$('[data-analyse="neck"]').click();
assert.equal(win.document.querySelector('#forge-controls').elements.namedItem('position').value,'neck');
assert(!$('#forge-response-controls').hidden&&$('#forge-response-graph svg'));
$('#forge-response-volume').value='4.5';$('#forge-response-volume').dispatchEvent(new win.Event('input',{bubbles:true}));
assert.equal($('#forge-response-volume-value').textContent,'4.5 / 10');
$('#forge-response-tone').value='6.2';$('#forge-response-tone').dispatchEvent(new win.Event('input',{bubbles:true}));
assert.equal($('#forge-response-tone-value').textContent,'6.2 / 10');
assert($('#forge-response-graph svg[role="img"]'));
assert(!$('#forge-response-key').hidden&&!$('#forge-response-key .forge-response-reference').hidden); // V2 explicitly shows the same-volume baseline, including an identical no-bleed circuit.
assert.equal($('#forge-response-key .forge-response-current').textContent,'Current circuit · no treble bleed');
$('select[name="bleed"]').value='prs';$('select[name="bleed"]').dispatchEvent(new win.Event('change',{bubbles:true}));
assert.equal($('#forge-response-volume-value').textContent,'4.5 / 10');
assert.equal($('#forge-response-tone-value').textContent,'6.2 / 10');
assert(!$('#forge-response-key').hidden&&!$('#forge-response-key .forge-response-reference').hidden);
assert.equal($('#forge-response-key .forge-response-current').textContent,'Current circuit · with treble bleed');
assert.match($('#forge-response-key .forge-response-reference').textContent,/Reference · no treble bleed · same Volume 4.5/);
assert.match($('#forge-response-context').textContent,/0.18nF/);
const neckGraph=$('#forge-response-graph').innerHTML;
labPick('bridge');assert.equal(selector(),'bridge');assert.equal($('[data-lab-pickup="bridge"]').getAttribute('aria-pressed'),'true');
assert(!$('#forge-response-controls').hidden&&$('#forge-response-graph svg'));
assert.notEqual($('#forge-response-graph').innerHTML,neckGraph,'new pickup controls recalculate the response');
assert.equal($('#forge-response-volume-value').textContent,'7.0 / 10');
labPick('neck');assert.equal(selector(),'neck');assert.equal($('#forge-response-volume-value').textContent,'4.5 / 10');
assert.equal($('#forge-response-tone-value').textContent,'6.2 / 10');
assert.equal($('#forge-response-graph').innerHTML,neckGraph,'returning to neck preserves its controls and response');
$('#forge-response-volume').value='10';$('#forge-response-volume').dispatchEvent(new win.Event('input',{bubbles:true}));
assert.match($('#forge-response-summary').textContent,/effectively inactive at full volume/);
$('#forge-response-volume').value='4.5';$('#forge-response-volume').dispatchEvent(new win.Event('input',{bubbles:true}));
assert.doesNotMatch($('#forge-response-summary').textContent,/effectively inactive at full volume/);
const component=$('#forge-parts [data-part="neckVolume"]');component.dispatchEvent(new win.MouseEvent('click',{bubbles:true}));
assert.match($('#forge-response-selection').textContent,/affects the displayed response/);
pick('position','both');assert($('#forge-response-controls').hidden);assert(!$('#forge-response-graph svg'));
labPick('neck');assert.equal(selector(),'neck');assert(!$('#forge-response-controls').hidden);
labPick('both');assert.equal(selector(),'both');assert($('#forge-response-controls').hidden);
$('[data-analyse="bridge"]').click();
assert.equal(win.document.querySelector('#forge-controls').elements.namedItem('position').value,'bridge');
assert(!$('#forge-response-controls').hidden&&$('#forge-response-graph svg'));
labPick('both');assert.equal(selector(),'both');assert($('#forge-response-controls').hidden);
labPick('bridge');assert.equal(selector(),'bridge');assert(!$('#forge-response-controls').hidden);
assert.equal($('select[name="bleed"]').value,'prs');
pick('position','neck');assert.equal($('#forge-response-volume-value').textContent,'4.5 / 10');
mode('physical');assert(!$('#forge-mode-physical').hidden&&$('#forge-response-lab').hidden);
assert.equal($('#forge-diagram-title').textContent,'Circuit Lab');
assert.equal($('[data-forge-mode="physical"]').getAttribute('aria-pressed'),'true');
assert.equal(win.document.querySelector('#forge-controls').elements.namedItem('position').value,'neck');
assert.equal($('select[name="bleed"]').value,'prs');
assert.equal($('#forge-parts [data-part="neckVolume"]').getAttribute('aria-pressed'),'true');
mode('signal');assert.equal($('#forge-response-volume-value').textContent,'4.5 / 10');
assert.equal($('#forge-response-tone-value').textContent,'6.2 / 10');
pick('position','both');pick('wiring','50s');
assert($('#forge-response-actions').hidden&&$('#forge-response-controls').hidden);
assert.match($('#forge-response-summary').textContent,/Modern tone wiring/);
pick('wiring','60s');assert($('#forge-response-actions').hidden);
pick('wiring','modern');pick('position','neck');
win.close();
console.log('Response Lab DOM controls, graph and unsupported state PASS');
