import assert from 'node:assert/strict';import {createReference,configureInstrumentDimensions,instrumentCapabilities,normaliseInstrument} from '../dist/electronics/instrument/configuration.mjs';import {makeInstrumentCircuit,instrumentFromCircuit,instrumentFromGeneratorCircuit} from '../dist/electronics/instrument/circuit.mjs';import {conductiveIndex} from '../dist/electronics/circuit-connectivity.mjs';import {circuitResponse} from '../dist/electronics/response/circuit.mjs';import {frequencyResponse} from '../dist/electronics/response/engine.mjs';import {captureCircuitState,readCircuitState,wiringHandoff} from '../dist/electronics/state/circuit-state.mjs';import {workshopGuide} from '../dist/wiring-generator/build-guide.mjs';import {createBuildProgress} from '../dist/wiring-generator/guided-build.mjs';import {drawCircuit} from '../dist/wiring-generator/render.mjs';import {routeDiagram} from '../dist/wiring-generator/routing.mjs';import {endpoint,makeCircuit} from '../dist/wiring-generator/model.mjs';
let cases=0,responses=0,diagrams=0;
for(const selection of [1,2,3])for(const neckCap of ['0.010','0.015','0.022','0.033','0.047'])for(const bridgeCap of ['0.010','0.015','0.022','0.033','0.047'])for(const bleed of ['none','prs','cap','duncan'])for(const shielding of ['yes','no']){
 const i=configureInstrumentDimensions(createReference('hh'),{controlLayout:'1V2T'});i.selector.selection=selection;i.shielding=shielding;i.controls.find(c=>c.id==='neckTone').capacitor=neckCap;i.controls.find(c=>c.id==='bridgeTone').capacitor=bridgeCap;i.controls.find(c=>c.role==='volume').bleed=bleed;i.controls.find(c=>c.id==='neckTone').position=cases%11;i.controls.find(c=>c.id==='bridgeTone').position=(cases+3)%11;i.controls.find(c=>c.id==='bridgeTone').pot=300;
 const c=makeInstrumentCircuit(i),caps=instrumentCapabilities(i),idx=conductiveIndex(c);assert(caps.canGenerateWiring);assert(!caps.canBuildKit);assert(!caps.canCoilSplit);assert(!idx.net('jack.tip').has('jack.sleeve'));assert(idx.net('jack.tip').has('masterVolume.lug2'));assert(!idx.net('neckPickup.hot').has('bridgePickup.hot')||selection===2);assert(idx.net('neckPickup.hot').has('toneCap.a'));assert(idx.net('bridgePickup.hot').has('bridgeCap.a'));assert(idx.net('toneCap.b').has('neckTone.lug2'));assert(idx.net('bridgeCap.b').has('bridgeTone.lug2'));assert(!idx.net('toneCap.a').has('toneCap.b'));assert(!idx.net('bridgeCap.a').has('bridgeCap.b'));
 for(const p of ['neck','bridge']){assert.equal(idx.net(p+'Pickup.hot').has('masterVolume.lug3'),caps.selected.includes(p));assert(idx.net('jack.sleeve').has(p+'Tone.lug1'));}
 assert.deepEqual(instrumentFromCircuit(c),normaliseInstrument(i));assert.deepEqual(captureCircuitState(c).instrument,normaliseInstrument(i));assert.deepEqual(readCircuitState(new URL(wiringHandoff(c),'https://fixture').search).state.instrument,normaliseInstrument(i));assert.equal(instrumentFromGeneratorCircuit(c).controlLayout,'1V2T');assert.equal(createBuildProgress(c,workshopGuide(c)).checkpoints.length,c.connections.length+2);
 const report=circuitResponse(c,21);assert.equal(report.supported,selection!==2);if(report.supported){const ch=caps.selected[0],tone=i.controls.find(t=>t.id===ch+'Tone');assert.equal(report.state.toneCap,Number(tone.capacitor)*1000);assert.equal(report.state.tonePot,tone.pot);assert.equal(report.state.tonePosition,tone.position);assert.deepEqual(report.points,frequencyResponse(report.state,21));responses++;}
 if(cases%60===0)for(const mode of ['build','trace','explain']){const svg=drawCircuit(c,{mode});assert(!/NaN/.test(svg));const routes=routeDiagram(c,{mode});for(const w of c.connections){const a=endpoint(c,w.from),b=endpoint(c,w.to);assert.deepEqual(routes.get(w.id)[0],[a.x,a.y]);assert.deepEqual(routes.get(w.id).at(-1),[b.x,b.y]);}diagrams++;}cases++;
}
const raw=makeCircuit({guitar:'hh',controlLayout:'1V2T'});assert.equal(raw.components.find(p=>p.id==='bridgeTone').value,'500kΩ Audio');assert.equal(instrumentFromGeneratorCircuit(raw).controls.find(c=>c.id==='bridgeTone').pot,500);
const deferred=configureInstrumentDimensions(createReference('hh'),{controlLayout:'2V1T',selector:'3-way-toggle'});assert(!instrumentCapabilities(deferred).canGenerateWiring);console.log(JSON.stringify({newConfigurations:cases,responseComparisons:responses,diagrams,topology:'HH 1V2T independent input-loading tones, 3-way blade; combined response unavailable'}));
