// Additive navigation derived solely from immutable public CMS snapshots.
import {readFile} from 'node:fs/promises';
import {join} from 'node:path';
import {cmsConfig} from '../../dist/hub-cms/config.mjs';
import {documentMetrics as textMetrics} from '../../dist/authoring/document.mjs';
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const marker=(kind,html)=>`<!-- KNOWLEDGE V3 ${kind} START -->${html}<!-- KNOWLEDGE V3 ${kind} END -->`;
export const stripKnowledge=html=>html.replace(/<!-- KNOWLEDGE V3 ([A-Z]+) START -->[\s\S]*?<!-- KNOWLEDGE V3 \1 END -->/g,'');
const topic={potentiometers:'pots','tone-controls':'capacitors','treble-bleeds':'capacitors',wiring:'wiring',pickups:'pickups',troubleshooting:'diagnosis'};
const journeys=[{title:'Understand pickup measurements',ids:['pickups','pickup-dc-resistance-output','pickup-inductance','cable-capacitance'],context:'Separate conductor identity, DC measurements and the frequency-dependent load.'},{title:'Plan a switching change',ids:['lugs','push-pull-dpdt','coil-split-guide','partial-coil-splits','pickup-phase-switching'],context:'Identify terminals and coils before choosing a modification. Tool support remains configuration-specific.'},{title:'Diagnose an interacting control or intermittent output',ids:['troubleshoot','output-jack-faults','lp-controls','independent-dependent-volumes'],context:'Start with the symptom and distinguish a wiring fault from expected circuit interaction.'}];
const toolGuides={signal:['values','pickup-dc-resistance-output','pickup-inductance','cable-capacitance'],wiring:['lugs','push-pull-dpdt','independent-dependent-volumes','output-jack-faults'],bleed:['bleeds','taper','cable-capacitance']};
export async function discoveryOutputs(records,root,discovery){
 const publicRecords=records.filter(r=>r.content.indexable),byKey=new Map(publicRecords.map(r=>[r.guide_key,r])),added=publicRecords.filter(r=>!cmsConfig.guideKeys.includes(r.guide_key)),link=id=>{const a=byKey.get(id);return a?`<a href="/luthier-hub/${esc(a.content.slug)}/">${esc(a.content.title)}</a>`:'';},output=new Map();
 // Existing intent ownership is immutable; only supporting relationships expand.
 for(const intent of discovery.intents){const primary=byKey.get(intent.primary.id);if(!primary)throw Error('Missing primary intent');intent.supporting=intent.supporting.filter(a=>cmsConfig.guideKeys.includes(a.id)||byKey.has(a.id));const extra=added.filter(a=>a.content.related.includes(primary.guide_key));const existing=new Set(intent.supporting.map(a=>a.id));for(const a of extra)if(!existing.has(a.guide_key))intent.supporting.push({id:a.guide_key,canonical:cmsConfig.base+'/luthier-hub/'+a.content.slug+'/'});}
 const graph={version:3,source:'published-cms',guides:publicRecords.map(a=>({id:a.guide_key,title:a.content.title,canonical:cmsConfig.base+'/luthier-hub/'+a.content.slug+'/',category:a.content.category,primary_intent:a.content.primary_intent,related:a.content.related.filter(id=>byKey.has(id)),tools:a.content.tools,components:a.content.components,reading_minutes:textMetrics(a.content.body).minutes})),journeys:journeys.map(j=>({...j,ids:j.ids.filter(id=>byKey.has(id))})),toolGuides};output.set('luthier-hub/knowledge.json',JSON.stringify(graph,null,2)+'\n');
 let hub=stripKnowledge(await readFile(join(root,'luthier-hub/index.html'),'utf8'));
 const cards=added.map(a=>`<article class="hub-card knowledge-index-card" data-knowledge-addition="guide" data-topic="${topic[a.content.category]}" data-search="${esc(a.content.title+' '+a.content.intro)}"><p class="eyebrow">${esc(cmsConfig.categories.find(c=>c.id===a.content.category).title)}</p><h3>${link(a.guide_key)}</h3><p>${esc(a.content.intro)}</p></article>`).join('');
 const anchor='<p id="hub-empty"';const position=hub.indexOf(anchor);if(position<0)throw Error('Accepted Hub search contract missing');const gridEnd=hub.lastIndexOf('</div>',position);hub=hub.slice(0,gridEnd)+marker('CARDS',cards)+hub.slice(gridEnd);
 const journeyHTML=`<nav class="hub-wrap hub-knowledge-access" data-knowledge-addition="journeys" aria-label="Guided reading journeys"><p class="hub-kicker">REFERENCE / NEXT STEPS</p><h2>Follow a question through the library.</h2>${journeys.map(j=>`<section><h3>${esc(j.title)}</h3><p>${esc(j.context)}</p><ol>${j.ids.filter(id=>byKey.has(id)).map(id=>`<li>${link(id)}</li>`).join('')}</ol></section>`).join('')}</nav>`;
 hub=hub.replace('<div class="hub-closing',marker('JOURNEYS',journeyHTML)+'<div class="hub-closing');hub=hub.replace(/All \d+ guides are in the searchable index above\./,`All ${publicRecords.length} guides are in the searchable index above.`);
 const listSchema={ '@context':'https://schema.org','@type':'ItemList',name:'Luthier Hub supporting guides',itemListElement:added.map((a,i)=>({'@type':'ListItem',position:i+1,url:cmsConfig.base+'/luthier-hub/'+a.content.slug+'/',name:a.content.title}))};hub=hub.replace('</head>',marker('SCHEMA','<script type="application/ld+json">'+JSON.stringify(listSchema).replaceAll('<','\\u003c')+'</script>')+'</head>');output.set('luthier-hub/index.html',hub);
 for(const category of cmsConfig.categories){const path='luthier-hub/categories/'+category.id+'/index.html';let html=stripKnowledge(await readFile(join(root,path),'utf8'));const extra=added.filter(a=>a.content.category===category.id),rows=extra.map(a=>`<li data-knowledge-addition="guide"><div><p class="hub-label">${esc(category.title)}</p><h3>${link(a.guide_key)}</h3><p>${esc(a.content.intro)}</p></div><span class="hub-reading">${textMetrics(a.content.body).minutes} min read</span></li>`).join('');if(rows)html=html.replace('</ol></section>',marker('CATEGORY',rows)+'</ol></section>');output.set(path,html);}
 for(const [id,ids] of Object.entries(toolGuides)){const path=cmsConfig.tools[id].path.slice(1)+'index.html';let html=stripKnowledge(await readFile(join(root,path),'utf8'));const aside=`<aside class="category-learning" data-knowledge-addition="tool" aria-label="Related technical reading"><details><summary>Understand the circuit behind this tool</summary><p>Read the relevant principles alongside the tool’s supported configurations and stated limits.</p><ul>${ids.filter(key=>byKey.has(key)).map(key=>`<li>${link(key)}</li>`).join('')}</ul><a href="/luthier-hub/">Explore Luthier Hub →</a></details></aside>`;if(!html.includes('</main>'))throw Error('Tool main contract missing');html=html.replace('</main>',marker('TOOLS',aside)+'</main>');output.set(path,html);}
 return output;
}
