// Only public published CMS snapshots. Draft/revision APIs are never build inputs.
import {readFile,writeFile,mkdir,rename,mkdtemp,rm} from 'node:fs/promises';import {join,resolve} from 'node:path';import {tmpdir} from 'node:os';import {fileURLToPath} from 'node:url';import {renderArticle} from '../dist/hub-cms/render.mjs';import {publicBackendConfig} from '../dist/backend/public-config.mjs';
export async function generateCMS({records,root='dist'}={}){
 if(!Array.isArray(records)||records.length<22)throw Error('CMS published seed is incomplete. Previous public deployment retained.');const ids=new Set(),slugs=new Set(),output=new Map();
 // Stage every output before replacing any route. Any validation failure aborts deployment.
 for(const record of records){if(ids.has(record.id)||slugs.has(record.content?.slug))throw Error('Duplicate CMS identity/slug.');ids.add(record.id);slugs.add(record.content.slug);if(!/^[a-z0-9-]+$/.test(record.template_key))throw Error('Invalid CMS presentation authority.');const frame=JSON.parse(await readFile(join(root,'hub-cms/presentation',record.template_key+'.json'),'utf8'));const html=renderArticle(record.content,frame,records);if(!html.includes('href="https://apparitioninstruments.co.uk/luthier-hub/'+record.content.slug+'/"'))throw Error('CMS canonical mismatch.');output.set(join('luthier-hub',record.content.slug,'index.html'),html);}
 let map=await readFile(join(root,'sitemap.xml'),'utf8');for(const record of records){const url='https://apparitioninstruments.co.uk/luthier-hub/'+record.content.slug+'/',tag='<url><loc>'+url+'</loc></url>';if(record.content.indexable&&!map.includes('<loc>'+url+'</loc>'))map=map.replace('</urlset>',tag+'</urlset>');if(!record.content.indexable)map=map.replace(new RegExp('<url>\\s*<loc>'+url.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'</loc>[\\s\\S]*?</url>','g'),'');}output.set('sitemap.xml',map);
 // Discovery V2 intent nominations are fixed by server validation. Update only
 // their published structured fields; no additional primary families are invented.
 const discovery=JSON.parse(await readFile(join(root,'luthier-hub/discovery.json'),'utf8'));for(const intent of discovery.intents){const primary=records.find(r=>r.content.primary_intent===intent.id);if(!primary)throw Error('Discovery primary authority missing.');const p=primary.content;intent.canonical='https://apparitioninstruments.co.uk/luthier-hub/'+p.slug+'/';intent.primary={id:primary.guide_key,canonical:intent.canonical};}output.set('luthier-hub/discovery.json',JSON.stringify(discovery,null,2)+'\n');
 const stage=await mkdtemp(join(tmpdir(),'hub-cms-'));try{for(const [path,text] of output){await mkdir(join(stage,path,'..'),{recursive:true});await writeFile(join(stage,path),text);}for(const [path,text] of output){const target=join(root,path);let old;try{old=await readFile(target,'utf8');}catch{}if(old!==text){await mkdir(join(target,'..'),{recursive:true});await rename(join(stage,path),target);}}}finally{await rm(stage,{recursive:true,force:true});}
 return {articles:records.length,output};
}
if(process.argv[1]&&resolve(process.argv[1])===fileURLToPath(import.meta.url)){const r=await fetch(publicBackendConfig.url+'/rest/v1/rpc/public_hub_articles',{method:'POST',headers:{apikey:publicBackendConfig.publishableKey,'Content-Type':'application/json'},body:'{}'});if(!r.ok)throw Error('CMS publication unavailable; previous Pages deployment retained.');const result=await generateCMS({records:await r.json()});console.log('Validated and generated '+result.articles+' published CMS articles.');}
