// Server-only template from the persisted, paid and fulfilled Order snapshot.
const escape=(value:unknown)=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]!));
const money=(p:number)=>'£'+(p/100).toFixed(2);
export function buildPaidOrderConfirmation(order:any){
 if(order?.payment_status!=='paid'||!order.paid_at||!order.fulfillment_applied_at||!/^AI-\d+$/.test(order.reference||''))throw new Error('Confirmed paid Order required');
 if(!order.customer?.email||!order.customer?.name||!order.delivery?.line1||!Array.isArray(order.items)||!order.items.length)throw new Error('Paid Order contact or items unavailable');
 if(order.items.some((item:any)=>!Number.isSafeInteger(item.quantity)||item.quantity<1||!Number.isSafeInteger(item.unitPrice)||item.unitPrice<0||item.quantity*item.unitPrice!==item.lineTotal))throw new Error('Invalid persisted item');
 const subtotal=order.subtotal_pence,delivery=order.delivery_pence,total=order.total_pence;
 if(![subtotal,delivery,total].every(Number.isSafeInteger)||subtotal<0||delivery<0||subtotal+delivery!==total||order.items.reduce((n:number,item:any)=>n+item.lineTotal,0)!==subtotal)throw new Error('Invalid persisted total');
 const address=[order.delivery.recipient,order.delivery.line1,order.delivery.line2,order.delivery.city,order.delivery.region,order.delivery.postcode,order.delivery.country==='GB'?'United Kingdom':order.delivery.country].filter(Boolean);
 const fulfilment=({pending:'Awaiting Fulfilment',awaiting_fulfilment:'Awaiting Fulfilment',in_production:'In Production',ready_to_dispatch:'Ready to Dispatch',dispatched:'Dispatched',completed:'Completed'} as Record<string,string>)[order.status]||'Awaiting Fulfilment';
 const firstName=String(order.customer.name).trim().split(/\s+/)[0];
 const lines=order.items.map((item:any)=>`${item.quantity} × ${item.name} — ${money(item.lineTotal)} (${money(item.unitPrice)} each)`);
 const htmlItems=order.items.map((item:any)=>`<tr><td style="padding:12px 0;border-bottom:1px solid #3e4248;overflow-wrap:anywhere">${escape(item.name)}</td><td align="center" style="padding:12px 6px;border-bottom:1px solid #3e4248">${item.quantity}</td><td align="right" style="padding:12px 0;border-bottom:1px solid #3e4248;white-space:nowrap">${money(item.lineTotal)}</td></tr>`).join('');
 const text=['APPARITION INSTRUMENTS','Your Guitar. Your Vision. Precision Crafted.','','ORDER CONFIRMED','Hi '+firstName+',','Thanks for your order. Your payment has been confirmed.','',`ORDER ${order.reference}`,...lines,'',`Subtotal: ${money(subtotal)}`,`Delivery: ${money(delivery)}`,`TOTAL PAID: ${money(total)}`,'','DELIVERING TO',...address,'','WHAT HAPPENS NEXT',"We'll prepare your order and let you know when it's on its way.",'Payment: Paid','Fulfilment: '+fulfilment,'','Apparition Instruments','https://apparitioninstruments.co.uk','https://apparitioninstruments.co.uk/contact/'].join('\n');
 const html=`<!doctype html><html lang="en"><head><meta name="viewport" content="width=device-width,initial-scale=1"></head><body style="margin:0;background:#14181d;color:#f4f0e8;font-family:Arial,Helvetica,sans-serif"><table role="presentation" cellpadding="0" cellspacing="0" width="100%" style="background:#14181d"><tr><td align="center" style="padding:20px 12px"><table role="presentation" cellpadding="0" cellspacing="0" width="100%" style="max-width:600px;background:#23282f;color:#f4f0e8"><tr><td style="padding:28px 24px;border-bottom:2px solid #b89055"><p style="margin:0;color:#d5aa69;font-size:14px;font-weight:bold;letter-spacing:2px">APPARITION INSTRUMENTS</p><p style="margin:10px 0 0;color:#c8c3b8;font-size:12px">Your Guitar. Your Vision. Precision Crafted.</p></td></tr><tr><td style="padding:28px 24px"><h1 style="margin:0 0 18px;color:#f4f0e8;font-size:26px">Order confirmed</h1><p style="line-height:1.6">Hi ${escape(firstName)},</p><p style="line-height:1.6">Thanks for your order. Your payment has been confirmed.</p><h2 style="font-size:17px;color:#d5aa69;margin:30px 0 12px">Order ${escape(order.reference)}</h2><table role="presentation" cellpadding="0" cellspacing="0" width="100%" style="table-layout:fixed;color:#f4f0e8;font-size:13px"><tr><th align="left" style="width:64%;padding:8px 0">Item</th><th align="center" style="width:12%">Qty</th><th align="right" style="width:24%">Price</th></tr>${htmlItems}</table><table role="presentation" cellpadding="0" cellspacing="0" width="100%" style="color:#f4f0e8;font-size:14px;margin-top:20px"><tr><td style="padding:5px 0">Subtotal</td><td align="right">${money(subtotal)}</td></tr><tr><td style="padding:5px 0">Delivery</td><td align="right">${money(delivery)}</td></tr><tr><td style="padding:12px 0;border-top:2px solid #b89055;font-weight:bold">TOTAL PAID</td><td align="right" style="border-top:2px solid #b89055;font-weight:bold">${money(total)}</td></tr></table><h2 style="font-size:16px;color:#d5aa69;margin:28px 0 8px">Delivering to</h2><p style="line-height:1.6;margin:0">${address.map(escape).join('<br>')}</p><h2 style="font-size:16px;color:#d5aa69;margin:28px 0 8px">What happens next</h2><p style="line-height:1.6">We'll prepare your order and let you know when it's on its way.</p><p style="line-height:1.6">Payment: <strong>Paid</strong><br>Fulfilment: <strong>${escape(fulfilment)}</strong></p></td></tr><tr><td style="background:#1a1e24;padding:20px 24px;color:#c8c3b8;font-size:12px;line-height:1.6"><strong style="color:#d5aa69">Apparition Instruments</strong><br>Your Guitar. Your Vision. Precision Crafted.<br><a href="https://apparitioninstruments.co.uk" style="color:#d5aa69">apparitioninstruments.co.uk</a> · <a href="https://apparitioninstruments.co.uk/contact/" style="color:#d5aa69">Contact us</a></td></tr></table></td></tr></table></body></html>`;
 return {to:order.customer.email,subject:`Apparition Instruments order ${order.reference} confirmed`,text,html:html.replace(/></g,'>\n<')};
}
